### ISSUE TITLE
Crash when scanning MIDI devices (was announcement for beta test 0.8.0)

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#100]
Huge number of changes in this new version. See [version history](https://github.com/rsjaffe/MIDI2LR/wiki/Version-History) for details. Also many behind-the-scenes changes that will make this easier to maintain and improve in the future.

Please take a try -- particularly those on Macs! I think I have the build settings correct this time but we'll see. :pray:

**Comment by rsjaffe** [comment]
There are several bugs to be addressed before final release.

**Comment by rsjaffe** [comment]
I've reuploaded the release after taking care of two bugs:

*selective copy/paste not working
*returns to develop module with every picture change

**Comment by mischnic** [comment]
I have two problems:
- In Lightroom, everything is still English, although I have set it to German.
- The Options windows is way too large for my 13" Macbook Pro. ![bildschirmfoto 2015-12-20 um 19 36 02](https://cloud.githubusercontent.com/assets/4586894/11919363/ee50bac2-a750-11e5-839c-b1f171a46fbc.png)

**Comment by rsjaffe** [comment]
Thanks. I'll look into those issues.

**Comment by rsjaffe** [comment]
Figured out the problems. I have reshaped the Options window--hope it fits better. Also, I had incorrectly named the translation files--fixed that as well.

Thanks for looking at this--you can download the fixed release at the same location as before.

**Comment by krakozavr** [comment]
"Rescan MIDI devices" option causing the app's crash.
After plugin reload (from Plugin Manager) the message "*.xml: profile changed" but I did not performed any changes and I can't found any changes in my setting"

BTW, after update motorized sliders (BFC2000) are stopped working; plugin's reloading, LR restart and the device turning OFF-ON didn't help. But after re-scanning MIDI they got back to business, although the app was crashed.

**Comment by rsjaffe** [comment]
Hmm. Don't know what to say about the scan crash. That section of code hasn't been changed since I took over development. As to the "profile changed" message, that appears whenever a profile is loaded, including at program start. Maybe the wording should be changed to something like "profile loaded".

**Comment by krakozavr** [comment]
@rsjaffe - probably yes, "profile loaded" would be better :)
what about the crash. I did scanning many times before this update and all was OK. Not, I can't rescan the device without crash. Nothing other was changed. 
I just recreate it and save the logs (attached)
[temp.zip](https://github.com/rsjaffe/MIDI2LR/files/68208/temp.zip)

**Comment by rsjaffe** [comment]
Here's a debug build of the app. If you could run it and send the crash log that would be very helpful.

https://www.dropbox.com/s/5jks8rx8figf26x/MIDI2LR.exe?dl=0

**Comment by rsjaffe** [comment]
"profile loaded" will be the message, but won't be in the 0.8.1 release, as that will be out in a day or so. Will be in next release after that.

**Comment by krakozavr** [comment]
@rsjaffe - I have same crash issue with the new 0.8.1 version.
Also, some issues with 8.0.1:
- after update, i see the version 0.8.1 in the LR Plugin Manager, but the MIDI2LR app still reported itself like 0.8.0
- the window "new version 8.0.1 is available" appeared at each plugin start/reload

I downloaded the debug build and the crash was reproduced with this one, too. the crash log is attached.
[debug.zip](https://github.com/rsjaffe/MIDI2LR/files/69235/debug.zip)

**Comment by rsjaffe** [comment]
arrgh. Well, I fixed the version issue. I'll look at the debug log. Thanks.

**Comment by krakozavr** [comment]
@rsjaffe - I saved the log from Windows Event Viewer -> Event Log -> Applications, and attached additional files listed in the log description (which I was able to found: files expected to be in the c:\temp folder did not really appeared there). Please let me know is it OK, or I have to do something else :)

**Comment by rsjaffe** [comment]
The missing files would have helped. They weren't under a subfolder beneath the .wer file were they?

**Comment by krakozavr** [comment]
yohooo! I cathed them :) they was appeared in the TEMP folder after crash but disappeared when the error message had closed. So, until the error message still active, you can found and rename they :)
two sets are attached: one for debug version and another one for the released ver 8.0.1

I hope it will help :)

[WERF322.tmp.WERInternalMetadata-for-released-version-081.zip](https://github.com/rsjaffe/MIDI2LR/files/70172/WERF322.tmp.WERInternalMetadata-for-released-version-081.zip)
[WERB82A.tmp.WERInternalMetadata.for-debug-version.zip](https://github.com/rsjaffe/MIDI2LR/files/70173/WERB82A.tmp.WERInternalMetadata.for-debug-version.zip)

**Comment by rsjaffe** [comment]
There is a bug in the Juce C++ framework used by the app. The bug first appears in the version of Juce used in 0.8.0. It was just discovered a few days ago and the developers are working on a fix. I'd suggest either going back to a pre-0.8.0 version or hanging in there until Juce is updated.
