### ISSUE TITLE
Selective copy and paste problem (on 0.8.0 version)

### ISSUE THREAD

**Issue by rojmagd** [rsjaffe/MIDI2LR#101]
Hello. As always, thank you very much for your work.

I have tested the 0.8.0 version and selective copy and paste option and it dosen't work well. First of all, I click all the parameters in the paste options dialog. Then, I copy and paste selected settings, and the next parameters doesn't copy and paste:

Temperature
Tint
Exposure
Contrast
Highlights
Shadows
Whites
Blacks
Clarity
The other parameters copy and paste correctly.

Thanks.

**Comment by rsjaffe** [comment]
Found another bug as well. Consider the current 0.8.0 on the site as a pre-release. I've marked it as such.

**Comment by rsjaffe** [comment]
Think I've fixed the paste selected settings bug. Will upload fixed version soon.
