### ISSUE TITLE
Version 0.7 and up crashes LR

### ISSUE THREAD

**Issue by sandyfsx** [rsjaffe/MIDI2LR#102]
When I installed 0.7 it crashed LR immediately, I thought this might just be that version but I've now tried 0.8 as well and the same thing happens.

I add through the plugin manager and it says it has added fine but then the whole program crashes and I have to close it through task manager. Any idea why this is happening and what I can do about it? Version 0.6 works fine.

**Comment by sandyfsx** [comment]
I take that back, 0.6 now crashes as well. I had just updated to 2015.3 from 2015.1 as I thought that might be causing it but clearly not. This is a fairly major problem for me as I'm a wedding photographer with unprocessed shoots backing up.

**Comment by sandyfsx** [comment]
Hmm, so after removing all traces of 0.8 I have got 0.6 working on 2015.3. Still no clue why 0.7 and 0.8 don't work though.

**Comment by rsjaffe** [comment]
Well, 2015.2 had major problems with MIDI2LR on my machine, so I wonder if what happened has to do with the upgrade. The instability went away shortly after installing 2015.3. I'm running MIDI2LR 0.8.0 with LR 2015.3 on Windows 10 with a BCF2000 without any problems.

Try the following. Within plugin manager, disable MIDI2LR.

Close Lightroom, erase the contents of the MIDI2LR.lrplugin and replace with the contents of the MIDI2LR.lrplugin folder from the 0.8.0 distribution. Start Lightroom.

Since you've disabled the plugin, Lightroom isn't loading MIDI2LR, and any issues are unrelated to the plugin. Now, assuming all is fine, enable the plugin in LR's plugin manager. If enabling the plugin crashes Lightroom then we have a problem with MIDI2LR.

**Comment by sandyfsx** [comment]
Ok I did that but removing the contents of 0.6.0 and replacing with 0.8.0 removed MIDI2LR from my plugin list after I re-opened LR rather than just disabling it. When I went to add it back in it crashed in the same way as before. LR worked fine before attempting to load the plugin.

Where are you storing the MIDI2LR files? I've just been loading them from when I unzip them, could that make a difference?

**Comment by sandyfsx** [comment]
When I put the files for 0.6.0 back in, plugin manager loads with MIDI2LR disabled. Once I enable it, it works fine.

**Comment by rsjaffe** [comment]
Also, the plugin files are stored a bit differently. One more suggestion: delete the MIDI2LR.app directory from the plugin folder--I wonder if your system is somehow trying to run the Mac app.

I'd store the files in a subdirectory of your "Documents" folder. I use the following structure, as I have other things I've loaded into LR and other adobe products:

- Documents
  - Adobe Data
    - Develop Plugins
      - MIDI2LR.lrplugin

**Comment by rsjaffe** [comment]
I've gone back to splitting the OSX and Win distributions in the latest version (0.8.1) just in case the problem was that your system was trying to run the OSX app.

**Comment by sandyfsx** [comment]
I have 0.8.0 working now, thank you :-)

It was still crashing when I was loading it from it's unzipped location even after deleting the app folder, and downloading the windows version didn't work but as soon as I moved it to it's own directory (Documents > MIDI2LR > 0.8.0) everything started working again. I guess that will teach me to be lazy with my file structure!

BTW, 0.8.1 doesn't seem to have a folder named MIDI2LR.lrplugin so I couldn't load that either.

Thanks again for all your help.

**Comment by sandyfsx** [comment]
Le sigh, after a reboot the issue is back with 0.8.0. Tried disabling it and LR runs fine, as soon as I enable it again it crashes LR.

**Comment by sandyfsx** [comment]
So I think this might be something to do with it not shutting down properly. I went to go and delete the folder so I could add it fresh and got a file in use error: 'The action can't be completed because the file is open in System. Close the file and try again.

The thing is it doesn't show up in task manager so I can't close it.

**Comment by rsjaffe** [comment]
Which file was open in the system?

What directory is the plugin in? What are the permissions for the folder? Windows 10 made major changes in file and folder permissions. You may have to read information about that to diagnose the particular error.

**Comment by sandyfsx** [comment]
Just to update on this. I pretty much ignored everything over Christmas and New year and when I came back an installed 8.2 everything worked again. Thanks :)
