### ISSUE TITLE
Error Assertion failed: err == noErr

### ISSUE THREAD

**Issue by commodorecrush** [rsjaffe/MIDI2LR#103]
OS X 10.11.2 and MIDI2LR 0.8.1, I get an error:

Assertion failed: err == noErr

**Comment by rsjaffe** [comment]
Not again! You can fix that by navigating to MIDI2LR.lrplugin\MIDI2LR.app\Contents\MacOS and then chmod +x MIDI2LR.

I'll try to upload a fixed version in a few minutes.

**Comment by rsjaffe** [comment]
Corrected version now available at https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.8.0

**Comment by commodorecrush** [comment]
Jesus, you're fast. Ha! Thanks!
