### ISSUE TITLE
Am I doing something wrong.

### ISSUE THREAD

**Issue by wockawocka** [rsjaffe/MIDI2LR#104]
I'm still stuck with using V6, throughout all the builds the one thing I'm having problems with is the temperature settings.

I edit wedding photos and V8 (Whilst fast, responsive and a great build) causes me a problem in that a tiny movement of either the slider or a dial will make a +/- 300 movement. This is too much for subtle changes across 700 files.

A configurable range, is this something I can implement from my end as before the temp slider would bottom out at 3000 but I need a range of 2000-8000 and with a much more subtle gradient. 

Is it even possible to get this fine a control on the controller. I know I could with my previous now unusable plugin (Paddy).

Thanks!
Chris

**Comment by sandyfsx** [comment]
you can change the range the slider affects by going to file > plugin extras > set options > other settings. 

The default is 3000 - 9000 which I find works for most images (I'm also a wedding photographer) making the finest adjustment about 25

**Comment by wockawocka** [comment]
OMG THANK YOU
