### ISSUE TITLE
Something new about motorized sliders 

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#106]
Hello!
I found very odd behavior of MIDI2LR with motorized sliders (BFC2000, MIDI2LR 8.0.1, WIN10)
Generally, I shooting RAW only.
But the last shoot I did both RAW and JPEG photos (Sony A7R-II, if it is matter).
I found that motorized sliders working properly only for RAW, but ignore JPEGS.

Hey friends who have problems with motorized sliders, can you please check / recreate / confirm this?

**Comment by rsjaffe** [comment]
Switching from ARW to JPG could cause the sliders to stop working until you use them again, as the ranges for corrections are so different that it could confuse the pickup mode. I have some ideas about how to fix that in the future, but it will require significant changes to the program logic regarding pickup mode.

**Comment by rsjaffe** [comment]
See if the latest release fixes this.
