### ISSUE TITLE
Please add option to switch crop crop orientation

### ISSUE THREAD

**Issue by igpo3737** [rsjaffe/MIDI2LR#109]
Great work on MIDI2LR, really appreciate everything you do.

One thing I cant figure, but is extremely useful is to how to get MIDI2LR switch crop orientation.

Usually when I am in Crop mode I would press "X" key and LR will switch crop orientation from horizontal to vertical and vice versa. Outside of crop mode "X" usually marks photo as "REJECT", I tried selecting this option in MIDI2LR  but it still rejects photo even if I am in Crop mode.

Can you please, please, please add this option? or maybe point me in the right direction?

**Comment by rsjaffe** [comment]
This is what I think you want--please correct me if I'm wrong.

Current crop has more pixels horizontally than vertically. You want to change to having more vertically than horizontally.

I can think of a way to program that. However, it would be difficult to maintain the pixel counts. Would it be ok just to have a crop that went from horizontal to vertical without necessarily being the exact same size?

**Comment by igpo3737** [comment]
Oh yes, very simple crop change from horizontal to vertical and vice versa.

I dont thing pixel count matters, it is obviously going to change.

One simple way is to pass keyboard "X" key and assign it to nanoKONTROL2 button through MIDI2LR,

**Comment by rsjaffe** [comment]
I have a request for help out for key press programming--I don't know how to do that in a cross-platform compatible way. If anyone can help I'd appreciate it.
