### ISSUE TITLE
Rotate crop rectangle

### ISSUE THREAD

**Issue by e-savarese** [rsjaffe/MIDI2LR#110]
Hello rsjaffe,

I just wanted to say a massive thank you for your fantastic work... Version 0.8 has the feature I have been waiting for a long time.. Rotate crop rectangle!! :+1: 

However I seem to having a problem with the feature. When I change the crop angle with a knob it also changes the aspect ratio.. regardless of what parameters I set...  eg lock aspect ratio. constrain to images... 

I would just like to change the angle keeping the same aspect ratio. Please let me know If I have misunderstood the feature :)

I have added some screenshots... I hope I have missed something - any help would be greatly appreciated!! 

Regards

Ernie

![before rotation](https://cloud.githubusercontent.com/assets/7021901/11975712/8815c5e4-a968-11e5-96d3-cb8b782fbd6a.jpg)
![after rotation 1](https://cloud.githubusercontent.com/assets/7021901/11975711/8814e08e-a968-11e5-9f03-f7ec9a30c978.jpg)
![after rotation 2](https://cloud.githubusercontent.com/assets/7021901/11975713/8817caec-a968-11e5-9b14-aa98292b8e29.jpg)

**Comment by rsjaffe** [comment]
First, thanks for the screen captures. That's a huge help.

I'll look into it. The crop controls that we added in 0.8.0 are undocumented in LR SDK. Which means several things:
1. No documentation! We'll have to experiment to see what works.
2. There may be bugs in LR that caused Adobe to avoid documenting this control. 

So I don't know if it's fixable or not. In your screen captures the crop is constrained to the image even when you've disabled "constrain to image".

**Comment by rsjaffe** [comment]
I've now taken a look at that issue. It's worse than I thought. Lightroom changes the dimensions of the crop rectangle even when the rectangle isn't touching the image edges. I suspect it's something to do with how the crop values are being handled by Lightroom. There's nothing I can do about it at this time. 

You'll have to adjust crop angle before final adjustments of crop boundaries when using MIDI2LR. I'll update You're also going to be constrained to the image.

You also might want to try Lens Perspective Rotate in combination with the crop controls. Lens Perspective Rotate doesn't affect the crop borders and doesn't have quite the same constraints with the image boundaries.

**Comment by e-savarese** [comment]
Thanks very much for the update... I really appreciate you looking into it... Its a real shame because it actually does rotate the image... but it had a nasty side effect of changing other parameters too!! 

I will try your suggestion too...

Thanks again for your awesome software!!!

**Comment by Wolfkc** [comment]
I just ran across a case where i wanted the crop to not be constrained and found lightroom 6.7 is broken. Once you click constrain to image you can never again get lightroom to stop constraining the image. I'm going to have to export everything and then do my cropping in another program. Very disappointed in adobe.
