### ISSUE TITLE
Control settings not saving

### ISSUE THREAD

**Issue by EugeneMichel** [rsjaffe/MIDI2LR#111]
Up until version 0.7 every time I Started LR, MIDI2LR would auto load all my settings from last time. The new version 0.8 doesn't, I need to manually load the settings each time after restart. Anyway to fix this? I tried reinstalling and moving the setting to different drives. Thanks!

**Comment by rsjaffe** [comment]
Next time you run it, after loading settings, try saving it to the same place where it is. That may refresh the plugin's memory.

**Comment by EugeneMichel** [comment]
still doenst work, but not too much of a bid deal to open each time
