### ISSUE TITLE
Alt+Slider?

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#112]
Hi!
Probably I want too much.. But:
How about handling Alt+Slider combination?

When I use Alt+Conttol like Exposure, White-Black etc., in LR I have visual suggestion about clipping, but with MIDI controls it is not working.

**Comment by rsjaffe** [comment]
That seems to be a LR bug. I don't see any way to fix it.

**Comment by rsjaffe** [comment]
I'll add this to the wiki.
