### ISSUE TITLE
Toggle variable and if else support

### ISSUE THREAD

**Issue by INVITR0** [rsjaffe/MIDI2LR#113]
I know this might have a horrible impact on the ease of use, but it would be absolutely amazing to have the ability of using the same slider for different things based on a variable set by another button. This could work e.g. for holding one button down while using a slider (the variable would be 127 while pressed and 0 when released) or having the button light with the toggle-on mode show whether the variable is 0 or 127.

**Comment by INVITR0** [comment]
Sorry pressed submit before I was done. I hope it's clear what I mean. I know it could completely clutter the UI, but it would just be grate, I for example have a button each for the sliders that would fit perfectly for that. Keep up the great work!

**Comment by krakozavr** [comment]
@INVITR0 - I agree, it may be cool in many situations and will allow to create compact and powerful layouts.

Other side, for now you can use two workarounds:
1. You can set different layouts at your device (for BFC2000, for examle, it is possible) and switching layouts by the system PRESET buttons. If you want to keep some controls for same functions trough all presets, you can set a channel for them to your "default" preset's channel, so when you will switch presets, these controls will still at the place and other will be changed. I did it in my layouts published here.
2. As far as I understand, you can define different presets in MIDI2LR and save them with different names, then use dedicated button to switching between. The result will be same, it may be useful for a devices which doesn't support a hardware presets.

**Comment by rsjaffe** [comment]
new profiles feature should address this.
