### ISSUE TITLE
Motorized sliders (again) and B&W conversion

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#114]
When you are switching between photos, the sliders assigned for B&W conversion aren't catch up default settings for photos which was not previously touched with B&W tuning. 
For photos which was previously touched with B&W sliders are working normally, but when you are switching to a neighbor unedited photo they still stay at the last position. Then, all sliders will move to a correct positions as soon as you will move at least one of them.

P.S. Merry Christmas!

**Comment by rsjaffe** [comment]
new release should fix this
