### ISSUE TITLE
Bug: MIDI2LR 0.8 keeps switching develop/library

### ISSUE THREAD

**Issue by PhantomLordM** [rsjaffe/MIDI2LR#116]
Hello,

I encountered problem with plugin in 0.8 version. When in Library module I switch to other folder or collection, Lightroom start switching very very fast between Develop and Library Module, making it unusable. Of course when I remove MIDI2LR plugin, everything works fine, as well as with MIDI2LR 0.7 plugin.
I would appreciate your help as 0.8 version is simply fantastic and is exactly what I was hoping MIDI2LR will become.

**Comment by rsjaffe** [comment]
I'm not seeing that, but.. a quick way to debug this is for you to open up "Utilities.lua" in a text editor and replace, at the bottom of the file,
```lua
return { --table of exports, setting table member name and module function it points to
  wrapFOM = wrapFOM,
  wrapFCM = wrapFCM,
  execFOM = execFOM,
  execFCM = execFCM,
}
```
with
```lua
return { --table of exports, setting table member name and module function it points to
  wrapFOM = wrapFOM,
  wrapFCM = wrapFOM,
  execFOM = execFOM,
  execFCM = execFOM,
}
```
Note that the only changes are to the right of the equals sign, where **FCM** is replaced with **FOM**. Save the revised file and restart Lightroom. This should stop the switching.

**Comment by PhantomLordM** [comment]
Thank you very much for such quick reply, however it didn't make any change.
Lightroom starts normally, when plugin is loaded, it switches do develop and after a while to library. Then when I touch anything in Library module it starts switching between Library and Develop quickly (about 5-6 changes in one second) and Lightroom is unusable, need to be killed.
I don't know if that's relevant, but Library and Develop are the only modules that I have active (I don't use Map, Book and other stuff so I switched them off). I'm on Windows 7 and Lightroom 6 64bit.

**Comment by rsjaffe** [comment]
OK, some more surgery. The plugin needs to retrieve certain data in the Develop Module, then switches back to the prior module. The following removes most of the rest of those switch-backs. (**--** starts a comment in Lua).
Edit Limits.lua, do search and replace
search for: `    LrApplicationView.switchToModule(currentModule)`
replace with `--     LrApplicationView.switchToModule(currentModule)`
Edit MIDI2LR_Client.lua, do search and replace
search for: `    LrApplicationView.switchToModule(currentMod)`
replace with `--     LrApplicationView.switchToModule(currentMod)`

Close Lightroom and restart.

**Comment by PhantomLordM** [comment]
Hello,

It did make a difference, however now every time I click on photo in Library module, it switches me automatically do develop, which is obviously a bit distracting.
I've decided to make inactive another part of code:
"LrApplicationView.switchToModule('develop')" in Limits.luwa and MIDI2LR_Client.lua (by adding -- before it), and it helped with switching between modules problem, but obviously generate some side effects:
1) plugin welcomed me with: "An internal error has occurred: [string "Limits.lua"]:108: table index is nil" 2) custom limits work for both tiff and dng files simultaneously (except Temperature which works separately for tiff and dng). 
I understand I switched off important part of the code which was some step in determining type of file and selecting corresponding limits that has been set accordingly.

I've added my custom limits (for Contrast, Clarity, Saturation, Tint, Temp and Exposure) in 0.7 version with additional buttons "For Tiff" and "For DNG" next to "Set to default" one, but it was easy to do by some copy/pasting/writing in Options.lua and since I'm not a programmer and I know almost nothing about programming I cannot diagnose problem why 0.8 ver is misbehaving at my computer and I could only rely on your help.

**Comment by EugeneMichel** [comment]
I have the same issue. I could solve it by opening LR and immediately going to being in Develop module for around 10 seconds and then going back to Library module. Works most of the time. Win 10 64bit

**Comment by rsjaffe** [comment]
What we have is a sticky issue dealing with limitations of the Lightroom SDK. Certain functions of MIDI2LR require getting information that Lightroom will only provide when in the Develop module.

I have some major changes in the works (branch [Preferences-Refactor](https://github.com/rsjaffe/MIDI2LR/tree/preferences-refactor) ) that will address some most of the issues. 

To @PhantomLordM, I suggest the following: undo your improvised inactivation of the switch to develop code that you did. Also try undoing the edit I suggested to MIDI2LR_client.lua--that's what is causing the switch to develop every time you change pictures. See if that works.

**Comment by PhantomLordM** [comment]
Hi  rsjaffe,

I did what you've told - restore original MIDI2LR_client.lua and only did changes you've wrote to Limits.lua, but the problem still exist. If picture is selected in Library, it automatically changes to Develop module.

**Comment by rsjaffe** [comment]
OK, could you please then add back the changes to MIDI2LR_client and remove the changes from Limits?

**Comment by rsjaffe** [comment]
See #118 for a solution.

**Comment by rsjaffe** [comment]
You can also download the latest version at https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.8.2. That has the fix included.

**Comment by PhantomLordM** [comment]
Hello,

I've tried 0.8.2 earlier on today and it made no difference in plugin
behaviour.
Did you change anything in 0.8.2 after releasing it?

Cheers
Mateusz
28 gru 2015 22:51 "rsjaffe" <notifications@github.com> napisał(a):
