### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by TheFrogGitHub** [rsjaffe/MIDI2LR#117]
First: Thanks for the great tool, it helps a lot.

After using it for a day now with my Korg nanoKontrol2, I have some suggestions for consideration:
1. **Assigning profiles to a button.** 
I have three buttons next to each slider and it would be great if I could use them to assign different functions to the sliders by loading a specific profile. This would enable me to use the sliders for hue/saturation/luminance according to the button I pressed. Using next/previous profile isn't very handy for this task.
I don't know if this feature is the same as "#26 Toggle/select specific profiles (i.e. layers)" in the consolidated listing.
2. **Allow macros for buttons.**
I think this extends "#9 Assign sequence of actions to button". My thought here is that you could use this to do one or more actions and then switch to a different profile (like in the previous point to assign different functions to buttons and/or sliders). Usually you do specific tasks like adjusting exposure and then correcting colours where you could use the same sliders/knobs but tailored to the task. 
Example for the use of this feature: B&W conversion - "Convert to grayscale" + "Use Preset 1" + "Load Profile B&W" (for setting the sliders to Gray Mixer Red, Blue, etc.)
3. **To facilitate the recording of actions** - what if the UI for assignments was changed to buttons instead of menus? Would that be feasible?

**Comment by WaellerKlaus** [comment]
Allow me to join in here. I'd like to vote for the very useful enhancement request "1. Assigning profiles to a button." as suggested above. Using the famous BCF2000 I found that it already allows for switching the controls by "prev" / "next" buttons, however that defeats the idea of direct access, for which purpose I have added another MIDI Controller, the behringer CMD LC-1 which features another 52 keys. I'd like to be able to assign keys to switch the assignment of controls, which could be easily achieved by being able to load a profile by a key while the MIDI2LR's profile file-name could be assigned to the key and another profile to another key. This way the mapping of all sliders and controls to the limited number of hardware faders would be much more flexible and switching among layouts (as profiles) would get more direct.
Anyway, many thanks for your great work!

**Comment by rsjaffe** [comment]
https://github.com/rsjaffe/MIDI2LR/tree/feature-change-profiles shows my progress on this feature. Hope to have it soon, if bugs don't get in the way.

**Comment by WaellerKlaus** [comment]
Great to see your progress in this. As much as I would like to support, at least in testing, I'm afraid I'm new to GitHub, Visual Studio and XCode. As soon as you're able to release a build, even beta I'm going to test.
Just wanted to make sure it is not about camera profiles (yet) but MIDI-controller profiles. My target would be at least one per palette in the LR-develop-module, as much as LR allows. However I can't find the control-handles for the correction sliders of the graduate filter, the radial filter and the adjustment brush (probably not supported by LR?). Seeing that it seems 10 profiles could be sufficient (seen that in the code?), however if profiles are identified by their filenames there would be no hard limit.

**Comment by rsjaffe** [comment]
Yes--MIDI control profiles. Look at Profiles.lua in the [feature-change-profiles branch](https://github.com/rsjaffe/MIDI2LR/tree/feature-change-profiles) -- under Source\LRPlugin\MIDI2LR.lrplugin directory to get an idea of the types of profile triggers I'm looking at.

**Comment by lukasradek** [comment]
Add the ability to move zoomed image, if possible. In TouchOSC would be a great control for it XY Pad.

**Comment by rsjaffe** [comment]
Moved to #31
