### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#12]
_From @clearminds on August 24, 2015 18:18_

A nice feature would be to be able to map a button to a keyboard shortcut. One example is CTRL+ALT+V (Copy settings from previous photo). Would make the start of some photos a lot easier.

_Copied from original issue: thegouger/MIDI2LR#29_

**Comment by rsjaffe** [comment]
_From @thegouger on August 26, 2015 22:51_

I'll see if I this can be done through the plugin API.

Keyboard shortcuts might come further down the line (but it would take a while to implement as it's somewhat complex and not consistent across platforms).

**Comment by rsjaffe** [comment]
_From @micksh6 on August 30, 2015 21:52_

I also support this request. This would be very useful.

I'm a Windows C++ programmer, but I know nothing about Lightroom SDK or OS X. Since your code is C++ and you make .exe file I assume you can call Win32 API.
If you don't mind to make non-portable calls you can probably use Win32 API SendInput() method to simulate any keyboard input.
OS X probably has something like that. I would understand if you don't want to create OS-specific branches in your code, though.

But, this would open endless possibilities even beyond Lightroom. Windows allows to assign keyboard shortcuts to a lot of actions, and there is 3rd party software to automate everything with keyboard. NanoKontrol2 and probably other MIDI controllers have lots of buttons that are currently unused.

**Comment by rsjaffe** [comment]
_From @Henk72 on September 7, 2015 21:45_

Maybe use Autohotkey for the keyboard shortcuts

**Comment by rsjaffe** [comment]
_From @amycastell on September 22, 2015 19:50_

Palette (palettegear.com) incorporates keyboard shortcuts in their software already

**Comment by rsjaffe** [comment]
_From @stevejmu on September 25, 2015 18:59_

Did you see that VSCO Keys is now open source?! Once a premium Lightroom plugin, they're no longer supporting it after November 2, 2015. But thankfully they're not killing it altogether. Can you use their code to implement keyboard shortcuts into MIDI2LR?  https://github.com/vsco/keys

**Comment by fldutch** [comment]
Would be great if this could be done somehow - using a Logitech G13 here with paddy for lightroom and sticked to lr 5.7 at the moment.

The way i use it in development mode is:
- push a button to select a slider (like exposure, contrast, whatever)
- use mini joystick to move slider (increase/decrease by a certain amount)
- use other keys to move slider with smaller amounts

In addition to this, it would be nice to beeing able to use all the layers of the G13 (which are 3).

**Comment by rsjaffe** [comment]
see #31
