### ISSUE TITLE
Translations--quick help wanted

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#121]
In a future release, the need for custom translation will be reduced dramatically, as I've found the translation dictionary used by Lightroom and hijacked that one. So only 6 words and phrases need to be translated, and they are listed below. If you have translations for them, please reply to this message with your translation, and include the name of the language you translated to.

Languages still needed are: Spanish (es), Italian (it), Japanese (ja), Korean (ko), Dutch (nl), Portuguese (pt), Swedish (sv), Chinese simplified (zh_cn) and Chinese traditional (zh_tw).

**Important note**: the first phrase "Paste selections" is adjective+noun, not verb+noun. This is the title of the text box where you select the parameters that you want to use in a "paste selected settings" action. 

=Paste selections
=Set MIDI2LR options
=Limits
=About
=How to use: connect a MIDI controller, launch MIDI2LR, and begin editing! See https://github.com/rsjaffe/MIDI2LR/wiki for details.
=Unable to load preferences. Using default settings.

**Comment by Polekso** [comment]
I think i can ask for swedih and italian to friends. I'keep you in touch soon.

**Comment by evertsjh** [comment]
I will translate the Dutch and if you want i can translate it also to the German language. Where most I post or send the translation?

**Comment by rsjaffe** [comment]
You can post them in this discussion thread. Thanks. We will have a few more translation requests, but they will be very few, as most of the translation is being handled by Lightroom's builtin translation facilities.

**Comment by evertsjh** [comment]
The one with the + sign and not in bold is the Dutch translation. I will translate the empty one's later this week. I translate this on my work :)

### Dutch (NL)
**=Paste selections**
+

**=Set MIDI2LR options**
+Stel de MIDI2LR opties in

**=Limits**
+Limieten

**=About**
+Over

**=How to use: connect a MIDI controller, launch MIDI2LR, and begin editing! See 
https://github.com/rsjaffe/MIDI2LR/wiki for details.**
+Hoe gebruik je; Sluit een MIDI controller aan, start MIDI2LR, en begin met bewerken! Zie https://github.com/rsjaffe/MIDI2LR/wiki voor meer gegevens.

**=Unable to load preferences. Using default settings.**
+Het is niet mogelijk om de voorkeursinstellingen te laden. De standaard instellingen wordt gebruikt.

### German
**=Paste selections**
+

**=Set MIDI2LR options**
+Stel de MIDI2LR opties in

**=Limits**
+Grenzen

**=About**
+Über

**=How to use: connect a MIDI controller, launch MIDI2LR, and begin editing! See 
https://github.com/rsjaffe/MIDI2LR/wiki for details.**
+Wie zu verwenden: einen MIDI-Controller anschließen , starten MIDI2LR und beginnen Bearbeitung ! Sehen https://github.com/rsjaffe/MIDI2LR/wiki für Weitere Informationen..

**=Unable to load preferences. Using default settings.**
Es ist nicht möglich, die Vorlieben zu laden. Die Standardeinstellungen wird verwendet.

**Comment by mischnic** [comment]
The German Translation is already done, yours isn't quite correct.
See here:
https://github.com/rsjaffe/MIDI2LR/blob/master/Source/LRPlugin/MIDI2LR.lrplugin/TranslatedStrings_de.txt

**Comment by evertsjh** [comment]
Its the way from with language you translate. I have translated from Dutch to German and the Translation that's all ready be done is translated from English to German ;)
