### ISSUE TITLE
Copy and paste problem on 0.8.2

### ISSUE THREAD

**Issue by rojmagd** [rsjaffe/MIDI2LR#123]
First of all, thank you for your work.

I have tested the new version and the following parameters doesn't paste:

- Temperature
- Tint
- Whites
- Blacks
- Clarity

The others copy and paste perfectly.

Bye.

**Comment by rsjaffe** [comment]
For those, you also need to select 
Temperature2012
Tint2012
Whites2012
Blacks2012
Clarity2012

See the Paste Selected in the [Options Dialog](https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog) section of the wiki for a detailed explanation.

**Comment by rojmagd** [comment]
Ok perfect, thank you very much.
