### ISSUE TITLE
Next steps for development--proposed

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#124]
As always, your support is appreciated--either in contributing to the code base, [contributing money to the effort](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=YWHT4JMA42RXN), identifying and posting bugs, or providing helpful feedback. I'm only working on this because I love photography, want to be able to easily edit pictures, and couldn't find anything out there (particularly for Windows computers) that would help. I'm not a professional programmer. Your support will help me keep this effort going.

I've taken advantage of some down-time from my real job to identify areas needing improvement. Please reply to the following with any suggestions/comments you may have. 

In an effort to make things more reliable and modifiable, the code is being modularized and tested. If you look at the branch https://github.com/rsjaffe/MIDI2LR/tree/preferences-refactor, you will see where it is headed. 

I'm also making extensive use of LR's built-in language translation capabilities, so the plugin will be more multilingual in the future. Passing that on to the application may have to wait for a few more releases.

As for next steps, there is lots of interest in having the MIDI controller change modes in certain situations--e.g., when starting to use the HSL mixer. My initial thinking is to use the "profiles" mechanism in the app to change mapping of controls. But this will wait until the code has been modularized and cleaned up. Modularization/clean-up is going well, and should be ready by the next release mid-late January. Profiles may be ready by then as well--we'll see.

**Comment by C0d3Rush** [comment]
<b>Thanks so much for all your efforts.</b> 

I can relate to what you said...was also searching for something reliable and fast on windows myself. Since the LR Develop module API is open it seems to make things easier. Once I am up to speed with C++ and Lua I will join your efforts.
