### ISSUE TITLE
Ensure "zero" is achievable for +- ranges

### ISSUE THREAD

**Issue by hzamir** [rsjaffe/MIDI2LR#125]
If I fiddle with a slider, especially one that started with a value of zero, I cannot get it back to zero, due to current midi resolution restrictions.

The best way to fix this would be to change the interpolation for all lightroom parameters that are centered around zero to guarantee that zero is reachable. So instead of a simple min-max. You could pick a center point e.g. 64 = 0, and interpolate values 65-127, and 0-63 separately.

**Comment by rsjaffe** [comment]
That's where the "reset" buttons come into play. That's what I use to get back to zero, rather than fussing with a control.
