### ISSUE TITLE
Offer better 0,127 to -100,+100 mapping

### ISSUE THREAD

**Issue by hzamir** [rsjaffe/MIDI2LR#126]
For those parameters that are adjustable around zero, it makes sense to offer a weighted interpolation option so more of limited resolution can be dedicated to subtler changes. If I'm going to pump up a parameter, the further I am from "neutral" the less precise it needs to be.

Instead of generic interpolation, the best overall way to map 0-127 t0 -100-100 would be

(I know this looks ugly, but it produces beautiful values) you get 1's precision from 36-90 and 2's precision outside. Using 64 for zero.

if(input >= 36) {
  output = (input <= 90)? input - 64 :  (input - 90)*2+26;
} else {
  output = (input - 36) * 2 - 28;
}

**Comment by rsjaffe** [comment]
non-linear mapping is a possibility. We'd have to have an option to enable/disable it for a given parameter.

**Comment by hzamir** [comment]
Ok, in the interim, since it was just a lua file and didn't require building anything I rigged up my own. It's working great. I just have to fiddle with some other ranges.

**Comment by rsjaffe** [comment]
Thanks. I'd like to see your code when you're happy with it.
