### ISSUE TITLE
Rewriting default.xml upon exit

### ISSUE THREAD

**Issue by DavidWeaverPhoto** [rsjaffe/MIDI2LR#132]
MIDI21LR (0.8.2) now does some sort of maintenance when closing LR (2015.3).  It appears to either overwrite default.xml or clears the instructions out of the file.  So when I'm rebooting or relaunching LR+MIDI2LR there is no command set.   (Win10pro, LR 2015.3, MIDI2LR 0.8.2, BCF2000)

**Comment by rsjaffe** [comment]
Hmm. Could you try loading your profile set then saving it? Then close LR, reopen LR, and see if that fixes it?

**Comment by DavidWeaverPhoto** [comment]
It happened multiple times.  When I save the default set to 'default1.xml' then there is no problem.  However, it would still overwrite/replace default.xml with a basic unfilled template.  
I moved to the beta and the issue went away.  so????

**Comment by rsjaffe** [comment]
OH--don't use default.xml for your settings! I'll put that in the FAQ. The app stores a default.xml in the plugin directory just in case it can't find the correct settings next time.
