### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by OzzyDevil69** [rsjaffe/MIDI2LR#133]
Hi i just wanted to know how many presets can you use as in P-1 ? i have lights showing P-1 P-2 P-3 thats all ?

**Comment by OzzyDevil69** [comment]
Hi Scratch that i worked it out in BC :)

Is there anyway we could have a button that edits in PS or an exit button and buttons to crop like 4X6 or 8X10...if not it doesn't matter just throwing things out there :)

**Comment by rsjaffe** [comment]
Things like that have been requested--can't see a way of doing it yet. Sorry.
