### ISSUE TITLE
The noise reduction data is not send to the midi device(BCF2000 )

### ISSUE THREAD

**Issue by Jewest** [rsjaffe/MIDI2LR#138]
Using the BCF2000 and channel 8 for the luminance noise reduction.
The slider is not updating while the rest is.
Going from 50% to 0% reduction.
Using Latest commit b7c5710.

**Comment by rsjaffe** [comment]
First thing I wondered is if there was a misspelling either in the app or the plugin. But it doesn't look like there is--all three luminance noise reduction controls appear correct. I'll have to dig a bit, and my main computer is on the fritz, so it may be a while. I checked in the code--in the C++ it is listed as
```C++
"LuminanceSmoothing",
"LuminanceNoiseReductionDetail",
"LuminanceNoiseReductionContrast",
```
and in Lua
```lua
  LuminanceSmoothing = {LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceSmoothing=Luminance Smoothing"), 600, 'detailPanel'},
  LuminanceNoiseReductionDetail = {LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionDetail=Luminance Noise Reduction Detail"), 610, 'detailPanel'},
  LuminanceNoiseReductionContrast = {LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionContrast=Luminance Noise Reduction Contrast"), 620, 'detailPanel'},
```

**Comment by rsjaffe** [comment]
Do you have more than one control mapped to luminance noise reduction? There is an issue with the current way controls are mapped in the app--the mapping assume that for each profile there is only one control for a given command--I haven't tackled it yet as I learned my C++ long before the standard library came out and I'll have to get more comfortable with the various data structures now available.

**Comment by rsjaffe** [comment]
Also, the latest commit in develop (c686b8e), has a configurable profile change notification--in response to your challenge tracking profile changes on the Mac. Look for the checkbox in the Profile section of the Options dialog.

**Comment by rsjaffe** [comment]
I wonder if this is related to #151.  See that issue for a possible fix.
