### ISSUE TITLE
previous/next profile not working correctly: will be fixed in next release

### ISSUE THREAD

**Issue by mannix0815** [rsjaffe/MIDI2LR#141]
Hi there. I'm using the Korg nanoKONTROL2 with the library and trying to put next profile on a track-button. Well, when the button is down, the prog is loading the other profile in the profiles-dir, when it's up again it switches back.

I walked through the code of ProfileManager and found line 111:
if ((value != 0 && value != 127) || !CommandMap::getInstance().messageExistsInMap(cc))

That means, when either the button is pressed down (value 127) or the button is released (value 0), a switch of the profile is done... so with every press (and releas) two steps are made.
Changing the line to eg.
if (value != 127 || !CommandMap::getInstance().messageExistsInMap(cc))

solves this "problem".

**Comment by rsjaffe** [comment]
Thanks. WIll fix. I hadn't paid much attention to the previous/next profile code (inherited the app) and forgot that it was originally coded for toggle switches (which don't work well with most of the parameters).

Already fixed in the code, will be out in next release.

**Comment by rsjaffe** [comment]
release out
