### ISSUE TITLE
Win7 error upon startup

### ISSUE THREAD

**Issue by superpsych0** [rsjaffe/MIDI2LR#142]
Just installed 0.93, now getting this error where before it worked just fine with my BCF2000: http://imgur.com/lGO4O7l (can't upload image here for some reason).

Am I missing some MS C++ redistributable, or something like that?

After error is displayed and clicked through, I can see the File->Plugin Extras submenu, and can open Options, but Start Server throws the same error.

When shutting Lightroom (6.3, non-CC) down, it exits cleanly.

**Comment by rsjaffe** [comment]
I believe it can't find the app. midi2lr.exe should be in your plugin directory. Is it there?

**Comment by superpsych0** [comment]
Yep, the executable was missing. Maybe my antivirus nuked it from orbit for some reason, though I white-listed it.

Working fine upon re-download & extracting to same folder as initial, thank you!
