### ISSUE TITLE
Wish: device detection + settings

### ISSUE THREAD

**Issue by Jewest** [rsjaffe/MIDI2LR#143]
At the moment there is no detection for a specific device.
All devices are 1, but if my BCF2000 is not turned on, 80% of the commands in develop mode do not need to be send.
During selection I often crop a picture to see if it improves.
Now the plug in is slower than it can be.

**Comment by rsjaffe** [comment]
Should the app send a message to the plugin when attached device status changes? E.g., "ControllerDisconnected", "ControllerConnected" so that the plugin just idles when a controller isn't present.

**Comment by StevenKersting** [comment]
I think this would be good, especially since the plugin loads whether you plan on using it or not (by default).I think that would remove the need to rescan midi if a controller is connected after the plugin is loaded. And I think it would also be good if LR automatically shut down the plugin/app when it shuts down.

**Comment by rsjaffe** [comment]
Looked into it. I can detect if a device is not connected at startup, but cannot identify if a MIDI device is initially connected then later shut down, or if a device is initially off but later turned on, unless I continually poll the operating system and run a check on attached MIDI devices--a number of people have wanted this option in Juce, but it hasn't been implemented yet. So, it's easy to start in the right mode (device off/on) but hard to change if the status changes later.

That's also why the "rescan MIDI" button is there and why there isn't a MIDI status indicator on the app interface.

**Comment by rsjaffe** [comment]
Added to #31
