### ISSUE TITLE
Copy & Paste Selected Develop-Settings sets Clarity always 0.

### ISSUE THREAD

**Issue by WaellerKlaus** [rsjaffe/MIDI2LR#144]
This happens while Clarity is enabled in the copy Options and 0 is not the default value. MIDI2LR release 0.9.3 on Mac OS X 10.10.5 (14F1021) using Lightroom 6.3 [ 1052427 ].
MIDI2LR release 0.9.0 did not show this issue.

**Comment by rsjaffe** [comment]
Questions:

*Paste all or paste selected?
*What is the clarity setting in the source photo?

**Comment by WaellerKlaus** [comment]
It happens with paste selected. Don't know if pasta all shows the same issue. The clarity setting of the source photo is > 0.

**Comment by WaellerKlaus** [comment]
Just confirmed the Windows version shows exact the same issue (clarity pasted always = 0, independent of source value), however only using paste selected. Paste all works correctly, i.e. the correct clarity setting gets pasted.

**Comment by rsjaffe** [comment]
What process version are the photos using?

**Comment by WaellerKlaus** [comment]
It's the latest, the 2012 version.

**Comment by WaellerKlaus** [comment]
Just tried the 2010 process version and found the clarity setting is getting pasted correctly even using paste selected. So it seems an issue related with the 2012 process version only.

**Comment by rsjaffe** [comment]
The fix is out. I needed to ensure that process version 2012 parameters are always pasted after version 2010. https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.3.2

**Comment by WaellerKlaus** [comment]
Many thanks for the quick fix - confirmed 0.9.3.2 fixes the issue (at least on Windows - will update as soon as I can confirm on MAc as well).

**Comment by WaellerKlaus** [comment]
Many thanks for the quick fix! I've confirmed 0.9.3.2 solves the issue (tested on Windows, will update as soon as I can test on a Mac as well).

**Comment by rsjaffe** [comment]
0.9.4 released for general use, incorporating this fix.
