### ISSUE TITLE
Profiles 1 to 10 not work

### ISSUE THREAD

**Issue by alangsr12** [rsjaffe/MIDI2LR#145]
Hi, I´ve a Korg Nanokontrol 2. this plugin works in all parameters, great, but when I need to you use different profiles from 1 to 10 profiles, nothing happens, but when I use "next/prev profile" I don't have problem.
Thank you for this useful program

**Comment by rsjaffe** [comment]
Did you assign a profile to them in the Options menu? See https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog#profiles

**Comment by rsjaffe** [comment]
Did that fix it? Closing this issue tomorrow if I don't hear back.

**Comment by alangsr12** [comment]
I´m working for, and later I will create a template printable with xml confg to share!!!
Sorry my english is so bad!!!. I try to understand the wiki.

**Comment by alangsr12** [comment]
Yeah... I found the options panel. I did not find it earlier. because it was in Extras Plugin in Lightroom, Menu File.
