### ISSUE TITLE
The "others" dialog is empty

### ISSUE THREAD

**Issue by marcelstreicher** [rsjaffe/MIDI2LR#146]
The "other" dialog is empty. 

![others](https://cloud.githubusercontent.com/assets/16777632/12418786/a21714d0-be98-11e5-810f-82acf3c1539d.png)

**Comment by rsjaffe** [comment]
Yes, the "other" dialog will be empty in the current version of MIDI2LR unless you are in the develop module and a picture is selected. See https://github.com/rsjaffe/MIDI2LR/wiki/Version-History#version-090 . I'll add that information to the WIKI.
