### ISSUE TITLE
Lights for Color, Rating, and Stars

### ISSUE THREAD

**Issue by allengambrell** [rsjaffe/MIDI2LR#147]
I am in the process of building a custom midi controller for Lightroom with a button layout designed for Lightroom and not music.

As of right now I Midi2Lr reports back to the controller when the sliders are changed in Lr, so I can use that value to update the display on the controller.
The problem I am having, is that I Midi2Lr is not sending a message back (note) to the controller when the color, rating, or star is changed in Lightroom. I would like to have indicator lights on the controller for each one of these but have to be able to get the changes from lr when moving to another photo.

I tried sending a note on message from the controller to mark the image red and then note off to turn off the red. This may not be the ideal way so their are 2 other ways I thought about.

add the ablity to set a monitor note for each color, rating, flag. This would use alot of notes

Use a CC and set value ranges for each option. So 3 CC in total (my math my be off)
CC for Rating (0-42 = X, 44-85 = UnFlaged, 86-127 = Flagged
CC for Color (0-21 = Red, 22-42 = Yellow, 43-63 = Green, 64-84 = Blue, 85-105 = Purple, 106-127 = None)
CC for Stars ((0-21 = 0 Star, 22-42 = 1 Star, 43-63 = 2 Star, 64-84 = 3 Star, 85-105 = 4 Star, 106-127 = 5 Star)
This way would also allow us to use knobs or sliders to set these values instead of just buttons.

**Comment by rsjaffe** [comment]
The plugin is notified by Lightroom when a develop value is changed. Ratings and flags are not part of the notification system, so the plugin would have to repetitively check for changes (e.g., 1-2 times per second). This seems like a lot of computer activity for small gain. If you have some ideas that wouldn't require repetitive checks I'd be interested in hearing them.

**Comment by DavidWeaverPhoto** [comment]
Reporting flags, colors and ratings seems to be out of scope for a controller. LR shows these in various windows in different modules.  Changing them is easily done in Library and Develop modes with simple keystrokes.  Lightroom is rich in keytboard shortcuts and controllers seem to do best at controlling image manipulations.  Using keys to set ratings and colors and flags is very straight forward in LR (unlike some other commands).

**Comment by allengambrell** [comment]
I guess you are using the AdjustmentChangeObserver to detect when the value changes. Does this get called when the user changes images?  If so could you then report back to the controller the values for the ratings, flags and colors? It would not be ideal, but would be better than nothing.

I do think the ability to use knobs or sliders to set these values would be a nice feature to add as I explained above.

**Comment by rsjaffe** [comment]
Could do that, but the controller would still get out of sync with Lightroom if the user changes those values in the Lightroom interface. Many people (myself included) switch from keyboard/mouse to MIDI controller and back, depending upon which is more convenient at the moment.
