### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by lukasradek** [rsjaffe/MIDI2LR#148]
Ability to send MIDI/OSC messages back to device. Possibly as a reaction to incoming midi message.

**Comment by rsjaffe** [comment]
Messages to do what? The plugin does send messages back to the controller when develop values change.

**Comment by lukasradek** [comment]
Right, sorry for not clarifiing before. I am using it with TouchOSC and want the ability to use push buttons (or other) as custom-positioned buttons to switch between pages.

Unfortunately TouchOSC does not offer that feature (as far as I know), but allows to change tabs via incoming OSC (maybe midi) message. Therefore it would be great if I can assign a message to send back to TouchOSC. For example in the main MIDI2LR window there could be three columns (MIDI Command, LR Command, Return message). And "Return message" can be assigned some message - like the one to change page. It would be handy even for let's say "Convert to BW" and simultaneously switch to appropriate page.

(If someone is interested, until there is a solution from TouchOSC or MIDI2LR, I have a working workaround.)

At the end I would say, that I am very TouchOSC centric, so even though it might seem ignorant to other issueses, it is not true. I am more than aware, that there are other and more important things to do and I post this feature request only as a suggestion to postpone to later, when there is nothing of bigger importance. Just want to help the great community :).

Thanks rsjaffe for what you do :).

**Comment by StevenKersting** [comment]
I would also like the ability to send CC's back to the controller. I've switched to a DJ TechTools MidiFighter Twister which has the ability for a single knob to control two develop settings. It also has the ability for the knobs LED to change color, change brightness, or turn on/off with midi signal. 

The ability for the program to send back on/off or user set signals (value/channel) would allow the indicator LEDs to change to indicate their current status/what they are controlling.

**Comment by rsjaffe** [comment]
Added to #31.
