### ISSUE TITLE
Controller? Custom? Ideas?

### ISSUE THREAD

**Issue by allengambrell** [rsjaffe/MIDI2LR#149]
I have tried lots of controller to control Lightroom and have yet to find a great one. So I am in the process of building a custom midi controller designed just for Lightroom and not for music. I was wondering if anyone has any good ideas or types of controls to use.

I am trying to design it is that you never have to take your left hand off of it. The buttons would have a tactile feel so you know what you are doing from just the feel. In my opinion if you have to take you hand off the controller to do something, other than typing, then the controller is setup wrong. 

Here is a list of the controllers I have used

Pallet Controller - Works great, but not enough controls, sliders are useless without motors, way to much money. $35 for 1 more knob!  The Apple of controllers

Numark Orbit - If you want to sit back and do lite editing this is the one! Only $40 for the whole controller.  Wireless, lots of buttons, but only one wheel and it is hard to turn and you have to turn it alot, 

BCF2000 - To Big and controls are way to far apart, all buttons feel the same.

ARTURIA Beatstep - The buttons are way too soft, slow and you cannont tell when you press them.

Logitech G13 with Paddy -  Worked OK, but no more paddy and had no knobs or sliders

G510 keyboard Paddy - Worked for simple quick commands

Anyone have any others

**Comment by DavidWeaverPhoto** [comment]
Ha!  I just realized that since I'm left-handed I use the BCF2000 wiith my rikght hand so the sliders and dials are closest to the keyboard and that's great (for me).  :-)

**Comment by Waytao** [comment]
I use the DjTechTool Midi Fighter Twister 

https://store.djtechtools.com/products/midi-fighter-twister

It's worked extremely well for me. The buttons are very close together and its quite comfortable to hold as its has a rubber coating and the bottom is indented and makes it easy grip.

**Comment by rsjaffe** [comment]
I agree the BCF2000 is very large, but in my workflow, I use the keyboard mouse for everything outside of the develop module. So, my keyboard is in a keyboard holder, slightly below the level of my desk, and my MIDI controller is on the edge of the desk, so I reach up from my keyboard to the controller. Works for me.

My mouse is on the desk.

**Comment by lastinglight** [comment]
@Waytao - glad to hear you're having success using the DjTechTool MIDIFighter Twister.  I am using it as well, and wanted to ask you a quick question:

Have you been successful in configuring the controller to use a mid-point detent (in Midifighter Utility)?  Ideally, I'd like the LED to default to the mid-point (similar to the slider position) and then move clockwise or counter-clockwise in proportion to the adjustment in Lightroom (e.g., the slider position).

If you have any advice about how to configure the MidiFighter in the Utility, or a Lightroom mapping template that works well on the MidiFighter Twiser, I'd love to hear more about what you did.

Thanks!

**Comment by Waytao** [comment]
@lastinglight great question. I'm really not sure I haven't done too much experimentation with it the Leds to be honest. 

I make the adjustments per photo and while it sucks that there is no reset to 0 after moving to a new image. I just have to match the previous setting then go from there. If you do figure it out would love to see the set up.

**Comment by krakozavr** [comment]
I use BFC2000. Yes, it's big... But it's very comfortable for me. I'm right-hand person, abd I keep it at the RIGHT side. I don-t use a mouse (now, I even haven't it at all); I use keyboard and tablet. So, I keep the pen, and it is not a problem to use the pen and the controller together. I use the keyboard most for hotkey-rating and flagging; and almost ALL developing I do with the controller, except curves - when tablet is more comfortable for me, and the main lens correction - when MIDI2LR don't provide enough of controls, especially with upright recalculating and profile selection. My profiles (the first version) was posted here; now, with the new MIDI2LR possibilities, I changing them constantly, step-by step. If somebody will have interest, I will post the updated version, when it will be ready :)
