### ISSUE TITLE
Button inputs not working

### ISSUE THREAD

**Issue by StevenKersting** [rsjaffe/MIDI2LR#150]
OSX 10.11.2, LR CC 2015.3, Midi2LR v0.9.4

The buttons are recognized and show a toggle state (switches between 0 and 100 with each press). But regardless of what function I assign them (previous/next, rate/flag, profile, reveal panel) they have no affect.

I've tried rebooting computer, restarting LR, and reloading profile/Midi2LR with no luck.

**Comment by rsjaffe** [comment]
The plugin expects the button to send 127 when it is pressed. Can you reprogram your controller to do that? That’s the best way of handling this issue. If you cannot reprogram the buttons, you can change BUTTON_ON from 127 to 100 (it's near the top of the Client.lua file).


What MIDI controller are you using?

**Comment by StevenKersting** [comment]
Thanks!
I have no idea if I can reprogram the controller, but I'll look into it.
I'm using an evolution x-session pro I picked up on Ebay.

**Comment by rsjaffe** [comment]
Normally, MIDI buttons transmit a zero for off and 127 for on, so I suspect your controller was reprogrammed.

**Comment by rsjaffe** [comment]
See http://c3.zzounds.com/media/xsession_adv_user_eng-b9df9f85e02718ea40e1e0346ec7bf58.pdf for programming instructions.

**Comment by StevenKersting** [comment]
I appreciate the extra effort! 
I had already found the PDF and now I have the buttons programmed to transmit 127 high and low. It's working now and I don't have to press buttons twice.
