### ISSUE TITLE
Multiple entries of Midi2LR in notification Center

### ISSUE THREAD

**Issue by exb53** [rsjaffe/MIDI2LR#155]
by accident i discovered many instances of a "Midi2LR" symbol under:
Windows Settings, System, notifications & Actions

Midi2LR works fine, no issues with my system (Win 10 64 bit, Lr 6, Midi2LR latest release)

Thank you fro this excellent program!

Eckart

**Comment by rsjaffe** [comment]
Wow. I see that too. Looks like it adds a new entry to the notification center on occasion, though I don't know what triggers that. Only one of those entries is functional, don't know why the others stick around.

**Comment by rsjaffe** [comment]
This discussion has a lot more about the issue. Seems to be a Windows 10 quirk.

http://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/remove-an-uninstalled-app-from-the-notification/6cb57f86-23fd-4261-8922-e49f344095e5?auth=1

**Comment by rsjaffe** [comment]
Added to FAQ in wiki.
