### ISSUE TITLE
Suggestion for tray icon when switching profiles

### ISSUE THREAD

**Issue by losinternet** [rsjaffe/MIDI2LR#156]
Personal preference here..  You may have already tried the following suggestion and have decided to use the tray icon notification instead.

I was wondering if you had considered using the LrDialogs.showBezel( message, fadeDelay ) function to display the current profile that is loaded when switching profiles.  This function displays the same type of format that you would see when you switch modules or pick or star photos.

I know that you use the system tray icon bubble to update the program.  I modified the code to use the showBezel command when the plugin receives a ChangedToFile message to make it appear as though the LR2MIDI is more integrated within Lightrooom and to remove the popup balloons.

I am on Windows, so am not sure how the notification appears on OSX, but at least this may show some consistency between the two platforms.

At the end this really comes down to a user preference, would you rather see the profile in a popup tray bubble or inside Lightroom.

**Comment by rsjaffe** [comment]
You've been reading my mind. The development branch already includes a showBezel for profile changes and for control changes. Both are configurable by the user. Will be out in the next release--the test version should be out very soon.

On OSX, the app doesn't notify of changes--this was my motivation for adding the LR notification.
