### ISSUE TITLE
Two or more midi controllers?

### ISSUE THREAD

**Issue by alangsr12** [rsjaffe/MIDI2LR#158]
It may be possible to use two or more midi controls with the same software? ...
like a Korg NANOCONTROL for sliders/faders and nanoPAD for buttons or presets.

Thanks

PD: I apologize. if this is not the place to evacuate these questions, if not, can you tell me where?.

Thank you.

**Comment by rsjaffe** [comment]
You should be able to, but I haven't tested that. If you have problems, reply back. There are several ways to make this work, so if the obvious steps don't work, we can try some more complicated work-arounds.

**Comment by evertsjh** [comment]
I have place a order for a second midi controller. I hope that I can tested this weekend.

**Comment by evertsjh** [comment]
@alangsr12 and @rsjaffe It works fine with two controls. 
I have now a Korg nanoKONTROL2 and a nanoKEY2. 
The nanoKEY I use for the presets and ranking from the photos. In the picture you see the keys with a red dot for the ranking. The other keys has the configuration for the 20 presets you can choose in MIDI2LR

The nanoKONTROL has the configuration for the Develop Module. With all the Basic and Tone Curve
[See the picture](https://flic.kr/p/DPzSdY)
