### ISSUE TITLE
Past selected settings with "ask each time"

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#161]
It's work, thank you very much!
But can you please make the pop-up screen more structured (with grouping of the settings, as close as possible to the original LightRoom screen? It's pain to search needed option to check-uncheck :)

**Comment by rsjaffe** [comment]
I agree. The next version will have buttons to check/uncheck groups similar to how LR does it. That's already in the next version and tested. Should be out soon.
