### ISSUE TITLE
Preview of 0.9.5 now available (preview is numbered 0.9.4.2)

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#162]
A preview of the next release is now availlable: https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.4.2 . Feel free to try out the new features and help with debugging--this preview has been tested, but you all do things to it that I can't anticipate, so your assistance is welcome.

This is a preview release, to allow you to try out the new features and locate bugs. It works well on my system, but, given past experience, I know some quirks will be found. Much of the work in this release has been to improve reliability and maintainability. One planned item is present but incomplete in this preview: the selective paste dialog now has buttons to toggle groups of settings, but doesn't have buttons for all the groups yet.

Changes:
* Significant under-the-hood changes to increase reliability. For example, recursion guard for change observer, use of cross-platform string and file system Lightroom functions in place of Lua built-ins.
* Application switched to database-driven model: this tames the complexity and allows for more program logic verification.
* Documentation is also driven by the database, for consistent terminology and ease of updating.
* Show notification in Lightroom window when profile changed (configurable in Options dialog).
* Selective paste group toggle buttons added (Basic Tone, Color, Noise Reduction, Lens Corrections, Effects).
* Actions added: Extend selection one to the left or right.
* Action handling modified to increase application speed. (mainly by going to hash table for command mapping).
* Application startup sped up by putting startup completely inside asynchronous task.
* Parameters added: Local adjustments (for brush, radial filter, gradient filter). These only work when the applicable tool is active.
* Show notification in Lightroom window of parameter and value when changed (configurable in Options dialog).
* Icon updated (thank you Brad Siefert).
* Application in midst of major restructuring by Jeffrey Westgeest, to implement [observer pattern](https://en.wikipedia.org/wiki/Observer_pattern), intended to make the app more dynamic and flexible.

**Comment by StevenKersting** [comment]
How did Midi2LR pick up all of my option settings when I switched plugin versions/locations?

**Comment by rsjaffe** [comment]
The plugin has preference load logic that is backwards-compatible. If it can't find settings for the current version, it looks for earlier versions and translates them into the current version. See the functions load0 and load in https://github.com/rsjaffe/MIDI2LR/blob/develop/Source/LRPlugin/MIDI2LR.lrplugin/Preferences.lua for the details.
