### ISSUE TITLE
Feature request, switchable preferences/options

### ISSUE THREAD

**Issue by StevenKersting** [rsjaffe/MIDI2LR#163]
The controllers I have used all have the ability to store/switch between multiple programs with a button push (CC calls). I'm currently using two.

One program is for detailed editing and allows for control of almost every feature in LR. In order to achieve this I have xml files associated with all 8 panels and 9 of the ten profiles. This works great.

The second program is for basic/common edits and only uses one xml (currently). This also works well. The problem is that when a control causes another panel to open that panel's associated xml overwrites/replaces the one I want to be using. To overcome this I have moved the "stand alone" xml into it's own folder and I have to change the profile folder setting in order to use it. It would be much easier/better if I could switch between the configurations on the fly. I.e. doing basic edits and decide to switch to the other profiles/settings for more involved edits of an image, and then switch back to the quicker basic edits profile for additional images/quicker edits.

I was able to enter the full file path for the xml in the sub folder into one of the option profiles and get it to switch to that profile. But that didn't work as it still jumped back out of the subfolder when a panel opened and called for a different xml. I think there needs to be a way for a profile to change the profile folder setting.

**Comment by rsjaffe** [comment]
You may be better off assigning the profiles to buttons that to develop panels. That way you'd have more control over which profile shows up when.

**Comment by StevenKersting** [comment]
Well, that is somewhat problematic. I have 13 develop profiles and only 10 slots (I'm using 9 slots assigned to buttons already)... but the main issue is that assigning a profile to a button doesn't work as well as assigning it to a panel opening.

When I have a panel open w/ a profile assigned all related encoders pick up their slider positions (not using pickup mode) and indicate their setting. With a profile assigned to a button/knob it doesn't work that way, at least for the first encoder. It needs to run in pickup mode which I find more problematic as you have to "search" for the setting, or you get large setting jumps if not run in pickup mode.

**Comment by StevenKersting** [comment]
Perhaps it is possible to make profile switching paths relative instead of absolute. I.e. initial profile loading is based on the folder setting. Switching profiles is then relative (within current folder). I can then assign a profile to an xml within another folder using an absolute path and subsequent profile switches would revert to being relative (i.e. w/in new folder location).

**Comment by rsjaffe** [comment]
see #173
