### ISSUE TITLE
[string "Database.lua"]:2290

### ISSUE THREAD

**Issue by dusipuffi** [rsjaffe/MIDI2LR#169]
Hi,
plugin cannot connect to LR
I have LR 6.4 win7/64
0.9.4 working , 0.9.5 (all versions) not working

![image](https://cloud.githubusercontent.com/assets/13853856/12793481/2530b654-cab1-11e5-9d95-b096c52f1a4b.png)

**Comment by rsjaffe** [comment]
That sounds like a write permission issue. What directory did you put the plugin in? See item number 6 in the FAQ about choosing a directory: https://github.com/rsjaffe/MIDI2LR/wiki#faqknown-issues .

**Comment by rsjaffe** [comment]
My apologies, there's a missing line that will cause this error. Please download the latest version at https://github.com/rsjaffe/MIDI2LR/releases

**Comment by dusipuffi** [comment]
hi,
0.9.5.3 genereted this error
![image](https://cloud.githubusercontent.com/assets/13853856/12822507/aa5942da-cb68-11e5-99ef-ff01e50e5341.png)

**Comment by rsjaffe** [comment]
What directory did you put the plugin in?

**Comment by dusipuffi** [comment]
c:\program files\adobe\lightroom\

**Comment by rsjaffe** [comment]
That's the problem. The plugin cannot be in a program directory in windows, as we need to write to that directory. See [FAQ number 6](https://github.com/rsjaffe/MIDI2LR/wiki#faqknown-issues) in the wiki.

**Comment by dusipuffi** [comment]
Thank you! You are right.
