### ISSUE TITLE
Plugin Options Error 

### ISSUE THREAD

**Issue by StevenKersting** [rsjaffe/MIDI2LR#171]
OSX El Captian, LRCC 2015.4, 9.5

I started getting this error today. So I downloaded/installed latest version of 9.5. I removed previous version from LR, installed this version and rebooted computer.

Plug-in error log for plug-in at: /Applications/Adobe/Plug-ins/MIDI2LR-9.5/MIDI2LR.lrplugin

**** Error 1

An error occurred while attempting to run one of the plug-in’s scripts.
AgObjCBridge tried to call missing selector 'cellClass' on NSView

Revert to 9.4 and the error is gone. Revert back to 9.5 and error returns.

**Comment by StevenKersting** [comment]
Interestingly 9.5 was running fine previously and nothing changed that I am aware of.

**Comment by rsjaffe** [comment]
That is very odd. You're seeing an internal Lightroom error. I don't know what to do with it, as AgObjCBridge, cellClass and NSView are all internal LR identifiers--I don't see any information that would help me identify what is causing this.

One suggestion: check the attributes of /Applications/Adobe/Plug-ins/MIDI2LR-9.5/MIDI2LR.lrplugin to see that you have write access.

**Comment by mischnic** [comment]
When do you get that error? When the plugin loads or somewhere in the options?

**Comment by StevenKersting** [comment]
I have read/write access to the plugin.
The error occurs when accessing the options.

**Comment by StevenKersting** [comment]
I've gone thru the hassle of uninstalling/reinstalling LR with no change... it would be nice if it said which script it was trying to run.

**Comment by StevenKersting** [comment]
Ok, I've gone thru all of the releases. The problem does not occur with any of the 9.4 versions to include the 9.5 beta (9.4.2). But it occurs with all of the 9.5 versions...

I *thought* I was using a 9.5 version, but it may have been the pre-release and the error started to occur when I updated.

**Comment by StevenKersting** [comment]
Renamed the LR preferences.plist... added 9.5.3 and got the message "loading defaults"... error still present.

The script that is being called and is causing the error must be in a recently changed file.

**Comment by rsjaffe** [comment]
Did the application load successfully, or was the error before application load? Can you open the options dialog?

NSView is an OSX-specific class, so something odd is happening there that won't show up on Windows computers. However, we have other OSX users and I haven't heard anything from them yet...

**Comment by StevenKersting** [comment]
I've isolated the issue down to the limits.lua file. If I take the file from 9.4.2 and replace the one in 9.5.3 with it, then 9.5.3 loads and I can access the options. 

I tried commenting out the new import paramlist but that generated a different error and the plugin didn't load...
I haven't found an easy way to do a file compare so I'm at a bit of a standstill. 
I also noted that several of the lua files in 9.5.x show up as being exe files but they do not in 9.4.x. In trying to diagnose the issue I extracted the files from the plugin that were changed this week and the same files from 9.4.2. Here's a screenshot of those files side by side.

<img width="456" alt="screen shot 2016-02-05 at 4 53 45 pm" src="https://cloud.githubusercontent.com/assets/16807274/12860544/4b70ad6c-cc2b-11e5-8bef-852d09d39adf.png">

**Comment by rsjaffe** [comment]
Could you try copying the permissions from another lua file (e.g., Client.lua) and change Limits.lua and ClientUtilities.lua to match that set of permissions?

Here is the diff https://www.diffnow.com/?report=13brp . Not much has changed. My suggestion is to change 

```lua
return f:static_text{title = 'Limits only displayed when in Develop Module.'}
```

to 
```lua
return f:separator()
```

as NSView is associated with drawing things, and that's the only change in the file that relates to screen display.

**Comment by StevenKersting** [comment]
When I change it to separator I get an error relating to attempting to index a nil value. But if I change it to `return nil` as in the earlier version it works w/o error.

**Comment by StevenKersting** [comment]
Another relevant consideration... the failure to load the options dialogue does not occur if the develop module is active. It occurred to me to try from the develop module due to the static_text that was supposed to be displayed.

This may be the main difference I was failing to note before...

**Comment by rsjaffe** [comment]
Unfortunately

**Comment by StevenKersting** [comment]
So, `return nil` allows the options dialogue to open with any panel active (limits not displayed). Any version of `return:f` causes an error in any panel other than develop...

I have tried rewriting the code so that the `'Limits only displayed when in Develop Module.'` was defined in a separate line as a string and calling that string for the return with no success.

**Comment by rsjaffe** [comment]
Did you try
return {visible=false}

that avoids needing to use f:

**Comment by StevenKersting** [comment]
`return {visible = false}` works w/o error from any module.

**Comment by rsjaffe** [comment]
Great! Release https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.5.4 is out.
