### ISSUE TITLE
Color Temperature: probably stupid idea...

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#174]
..but why not?
The full range of Color Temperature correction may be importanf in many cases (for example, for concert/live performance shooting with crazy lighting). Other side, in most cases, only the lower range will need, but with the full-range setting, sensibility of the slider is not good enough.

Maybe it is possible to make 2-diapason limits? for the "full" and "limited" diapasons. I see two way of usage:
1. Two regulators are assigned together to the color temperature, one for the full range editing and other for limited.
2. One regulator  is assigned, but the button may switching the mode from the full range to the limited range and back (cyclic switching).

Is it possible?

**Comment by rsjaffe** [comment]
Both are possible, number one is easier to implement than number 2. I'm holding off doing something like that, though. If I can get NRPN working, it's a much better alternative.

**Comment by krakozavr** [comment]
:)
BTW, 2. looks better from my side because less of controls will be used.
And what's NRPN? I looked to Wikiopedia, looks like dual-control for parameters when 2 controls are used, one for some fine-tuning, is it right?

**Comment by rsjaffe** [comment]
NRPN for MIDI allows the control to have a wider range--instead of 0 to 127, it can be 0 to 16383. Some controllers, such as BCF2000, allow the knobs under NRPN to have variable speed, so that slow movement causes very minor changes, and fast movement fast changes--which allows you to use the knob for fine adjustments and coarse adjustments without having to change assignments.

**Comment by krakozavr** [comment]
oh. yes, you are right, probably it should be better. At least, it will be much more universal.
But, other side... For the Color Temperature my stupid idea may be, probably, good even with combination with NRPN, because the full range of the color temp is veeeeery wide, and the most important range is really narrow. So, especially for sliders, the movement of the controls could be very tiny to adjust the color temperature precisely.

And one more thing about the NPRM. Also, probably, not very correct, but: as I see now, with visualization of parameter's changes, it takes time to send data from the controller to LR, every single value one by one. It's very visible especially with knobs: when I do a turn, I do it fast, then I wait for relatively long time when the desired value will be reached, looking to the changing digits :) So, I'm afraid, is NPRN will not work even slower?

**Comment by rsjaffe** [comment]
No slower, but no faster. My system is pretty darn fast when I turn the knobs, and I have a very old computer (5 years old) and a BCF2000. What are you using?

**Comment by krakozavr** [comment]
With the latest version of MIDI2LR this issue was gone. Nothing changed beside of this. So, probably, long transmission was a local problem of the build.
