### ISSUE TITLE
Toggle Tone Curve adjustments

### ISSUE THREAD

**Issue by losinternet** [rsjaffe/MIDI2LR#175]
I am wondering if there is a command to toggle the tone curve adjustments off and on.

This works for details, color adjustments, split toning and others, but perhaps the tone curve toggle was overlooked.  i can do it manually with the mouse, clicking the on/off button

**Comment by rsjaffe** [comment]
It wasn't documented anywhere, and I didn't see it in any of the data dumps I reviewed, but I'll give it a try. I have to guess what LR calls that function, but I have some ideas.

**Comment by rsjaffe** [comment]
Well, that was easy. I've done it. It'll be in the next release. If you have windows and want to try it out now, you could unzip the following and use it to replace the files in your MIDI2LR.lrplugin directory.
[MIDI2LR.lrplugin.zip](https://github.com/rsjaffe/MIDI2LR/files/120488/MIDI2LR.lrplugin.zip)

**Comment by losinternet** [comment]
Thx
