### ISSUE TITLE
Basic Panel Contrast slider

### ISSUE THREAD

**Issue by losinternet** [rsjaffe/MIDI2LR#176]
For example if I am working in SOLO mode and have any single panel open and then I adjust a slider, the panel that has the slider I am adjusting will open.  This is not true for the Contrast slider in the basic panel.

To replicate:
- be in solo mode
- go to the effects panel
 - adjust the basic-contrast on the midi controller:  the contrast changes but the basic panel doesnt open
- adjust the basic-exposure on the midi controller - the exposure changes and the basic panel opens and shows the edits being made.

**Comment by rsjaffe** [comment]
That must be a LR bug. The plugin doesn't control the panel opening when adjusting sliders. It's enabled by calling LrDevelopController.revealAdjustedControls once at the beginning of the program.

Which version LR, what version and type operating system?

**Comment by losinternet** [comment]
Lightroom 6.4 
Win 7

**Comment by StevenKersting** [comment]
replicable on OSX 10.11.3, LR 2015.4, 9.5.4

**Comment by rsjaffe** [comment]
If you want to try a quick fix, you can edit Client.lua as follows. Add one line in updateParam. Change the start of function updateParam from:
```lua
    local function updateParam() --closure
      local lastclock, lastparam --tracking for pickup when scrubbing control rapidly
      return function(param, midi_value)
        local value
        -- this function does a 'pickup' type of check
        -- that is, it will ensure the develop parameter is close 
        -- to what the inputted command value is before updating it
        if LrApplicationView.getCurrentModuleName() ~= 'develop' then
          LrApplicationView.switchToModule('develop')
        end
```
to
```lua
    local function updateParam() --closure
      local lastclock, lastparam --tracking for pickup when scrubbing control rapidly
      return function(param, midi_value)
        local value
        -- this function does a 'pickup' type of check
        -- that is, it will ensure the develop parameter is close 
        -- to what the inputted command value is before updating it
        if LrApplicationView.getCurrentModuleName() ~= 'develop' then
          LrApplicationView.switchToModule('develop')
        end
       if param=='Contrast' then LrDevelopController.revealPanel(adjustPanel) end
```
