### ISSUE TITLE
Missing Local Adjustments

### ISSUE THREAD

**Issue by losinternet** [rsjaffe/MIDI2LR#177]
Local adjustments are missing the following:
-local whites
-local blacks
-local dehaze

**Comment by rsjaffe** [comment]
[The LR SDK documentation does not include those parameters](http://lightroomsolutions.com/sdk/modules/LrDevelopController.html). Implementing those will take some guesswork--I'll put it in the queue.

**Comment by rsjaffe** [comment]
Added to #31
