### ISSUE TITLE
Midi received with LR history update

### ISSUE THREAD

**Issue by StevenKersting** [rsjaffe/MIDI2LR#178]
I've been noticing uncommanded led color changes on my controller (MIDI Fighter Twister). It seems the controller is receiving a return signal of the adjustment value on the same CC as sent it when the history updates. Apparently it returns on the same channel?

It is odd in that it only occurs with a couple of specific controller configurations (switch channel and function assignments). I was able to alleviate the behavior by changing the switch's CC channel when programmed to that function.

If the return CC/channel/value is selectable/controllable in the code that could be useful to me... but I suspect it's not.

**Comment by rsjaffe** [comment]
Correct. It is sending back the adjustment value on the same channel because that is needed for fader and knob tracking. Removing that would break things for most users.

**Comment by StevenKersting** [comment]
I just needed to put the CC on a channel that is not also associated with the LED control (Ch1 which I cannot change). 
Interestingly, if the combined switch/rotary encoders are assigned to channels 1 and 2 w/ the same CC#, and they both got a suitable midi return, it would not only change the color but it would also change the animation state of the ring.

Since I cannot control the returns usefully, the answer was to set the switch channel to something other than 1 or 2.

This is probably only relevant to the MidiFighter Twister, and it only happens with certain switch function settings (i.e. encoder toggle)... But it might be relevant to someone else eventually.

**Comment by rsjaffe** [comment]
Added to [Wiki FAQ](https://github.com/rsjaffe/MIDI2LR/wiki#faqknown-issues)

**Comment by lastinglight** [comment]
@StevenKersting - thanks for this information.  Would you be willing to upload/share your XML configuration file for the MidiFighter Twister?  I'm having similar issues, but haven't entirely figured out how to resolve it by re-assigning the channels as you indicated.  Seeing your configuration would definitely help me sort this out.  Thanks!

**Comment by StevenKersting** [comment]
Lastinglight, it's not in the Midi2LR xml files... it's in the midi fighter configuration set with the OEM Midi Fighter Utility.
