### ISSUE TITLE
Next Profile switching for ON and OFF

### ISSUE THREAD

**Issue by losinternet** [rsjaffe/MIDI2LR#179]
I have a midi command to switch to Next profile.

This command is being executed on both the on and off change of the button, causing the profile to skip ahead by 2.

**Comment by losinternet** [comment]
I have 4 profiles in the folder and each profile there is a CC for NEXT PROFILE.  All profiles use the same CC number and channel.

**Comment by losinternet** [comment]
Looks like this was a previous bug in #141

solution appears to be the same change line 111 to following:
		if ((value != 127) || !m_commandMap->messageExistsInMap(cc))
//		if ((value != 0 && value != 127) || !m_commandMap->messageExistsInMap(cc))

**Comment by rsjaffe** [comment]
Thanks. Don't know how that reverted to the old way. Fixed in next release.
