### ISSUE TITLE
Local Blacks, Whites and Dehaze

### ISSUE THREAD

**Issue by losinternet** [rsjaffe/MIDI2LR#180]
YEsterday I wrote about these missing and they were to the consolidate list.

I was trying to resolve these today but it looks like the values are not documented, but through some trial and error I discovered there names so now they work.

Dehaze = local_Dehaze
Blacks = local_Blacks2012
Whites = local_Whites2012

Ive added these to my local build and now I have full control of these 3 local sliders

**Comment by StevenKersting** [comment]
Those are all functional in my installation (OSX)...

**Comment by rsjaffe** [comment]
thanks. good sleuthing. I've added these to the next release.
