### ISSUE TITLE
ShoVwdevelop_before

### ISSUE THREAD

**Issue by sherwood69** [rsjaffe/MIDI2LR#182]
Hello!
I've got an issue with this function. When I use my usual pc keyboard and press "\" - LR will show me image before, when I press "\" again - it will bring back edited image. When i using my midi controller "Behringer X-Touch mini" with this function mapped i only get "before" state when i press it. Pressing it again will not change anything. How can I map this function correctly to one button just like on my pc keyboard, so i can push it once and see Before, push it again and return to edited image to continue working?

**Comment by StevenKersting** [comment]
I don't think you can. You need to program a second button to "View Modes > Primary Display Loupe" in order to return to the previous view.

**Comment by rsjaffe** [comment]
If you're on a Windows computer, you can try the \ key as implemented in #189. It sends keystrokes to the LR app. If you're on OS X, I need help getting the OS X version to send keystrokes.

**Comment by sherwood69** [comment]
Hello!
I downloaded version 0.9.6. Then I downloaded  MIDI2LR.zip    from  #189 . Please help me a little, i can't find new function. Do I need to map something by myself?


>Понедельник, 15 февраля 2016, 16:44 -08:00 от rsjaffe <notifications@github.com>:
>
>If you're on a Windows computer, you can try the \ key as implemented in  #189 . It sends keystrokes to the LR app. If you're on OS X, I need help getting the OS X version to send keystrokes.
>—
>Reply to this email directly or  view it on GitHub .


-- 
Artem Gusev

**Comment by rsjaffe** [comment]
Sorry--I need to add that particular keystroke to the set of commands. Will do later today/tomorrow.

**Comment by sherwood69** [comment]
thank you! I will wait for it:) 


>Вторник, 16 февраля 2016, 7:43 -08:00 от rsjaffe <notifications@github.com>:
>
>Sorry--I need to add that particular keystroke to the set of commands. Will do later today/tomorrow.
>—
>Reply to this email directly or  view it on GitHub .


-- 
Artem Gusev

**Comment by sherwood69** [comment]
hey there!

Can you please do that version with keystrokes for me with before\after (key |\")? i have updated to 0.9.7 and there is no keystroke functions anymore.


>Вторник, 16 февраля 2016, 7:43 -08:00 от rsjaffe <notifications@github.com>:
>
>Sorry--I need to add that particular keystroke to the set of commands. Will do later today/tomorrow.
>—
>Reply to this email directly or  view it on GitHub .


-- 
Artem Gusev
