### ISSUE TITLE
Crop Angle Improvement Solution

### ISSUE THREAD

**Issue by losinternet** [rsjaffe/MIDI2LR#184]
I wanted to use a rotary dial to straighten my photos and have the dial fix the horizon and automatically keep the aspect ration of the photo.

The CropAngle command didnt do the trick as the aspect ratio would get messed up.
The Angle adjustment in the Lens correction panel can do small adjustments but it is kinda clunky to use since the adjustment is already available in the crop panel.

It turns out that we should be using the command **straightenAngle** instead of CropAngle.

**straightenAngle** adjusts the angle of the photo keeping whatever aspect ration you have and it moves the slider in the crop tool panel from -45 to 45.  (you can also set limits)

Please add straightenAngle to the LRcommands.cpp file for the next release

available here
  straightenAngle = {LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/StraightenAngle=Straighten Angle"), 1035, 'crop'}, -- enabled in app

**Comment by rsjaffe** [comment]
Thank you for finding that. Will include in next release (and thanks for the translation string).
