### ISSUE TITLE
Tone curve enable/disable issue

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#185]
This is a relatively minor release, mainly adding some missing adjustments, improving translations and cleaning up some code. Hope to work on sending keystrokes to LR next. For that, we will need some Mac users for debugging, as the code will be completely different for Macs and PCs.

https://github.com/rsjaffe/MIDI2LR/releases

## In this update
* *Straighten Angle* added as replacement for hard-to-use *Crop Angle*.
* More translations for plugin.
* Enable/disable tone curve toggle added.
* Blacks, Whites and Dehaze added to local adjustments.
* Even more code cleanup.
* Fix for LR bug, where basic adjustments panel not revealed when Contrast is adjusted.

**Comment by StevenKersting** [comment]
I'm using Mac.
OSX 10.11.3 El Capitain and LR CC 2015.4 (the latest/most current versions)

**Comment by StevenKersting** [comment]
Disable tone curve isn't working correctly. It toggles, but the view/image doesn't change and the toggle reverts after a couple of seconds. It appears the midi signal to update the history is toggling the setting back.

**Comment by rsjaffe** [comment]
Just verified it's working correctly on mine. Anyone else seeing this?

**Comment by StevenKersting** [comment]
9.6.1 fixed it.
