### ISSUE TITLE
Lens Correction Checkboxes are not working

### ISSUE THREAD

**Issue by losinternet** [rsjaffe/MIDI2LR#187]
In the Lens Corrections Panel, the 3 checkboxes that do the following do not seem to be working:

1 enable profile corrections
2 remove chromatic aberration
3 constrain crop

-I can control all of the slider with my midi controller and can toggle the panel as well as contronl the upright buttons.

**Comment by rsjaffe** [comment]
I see number 1 and 2--don't know why they're not working, but those are experimental undocumented settings that I pulled off of an array of settings obtained by CopySettings that I viewed in the ZeroBrane Lua IDE debugger. There may be no way to get those working in the current version of LR--I may go poking around some more and see if I can find something. I don't think I have a "constrain crop" for lens corrections. Under which menu did you see that?

Thanks

**Comment by rsjaffe** [comment]
Removing those from next version. WIll have to do some experimenting before adding them back.
