### ISSUE TITLE
Color adjustment revert to the tone panel

### ISSUE THREAD

**Issue by StevenKersting** [rsjaffe/MIDI2LR#188]
MIDI2LR 9.5.4 and 9.6. If I make an adjustment in the HSL panel it reverts to the tone panel (and changes profile if associated).

**Comment by StevenKersting** [comment]
A couple of diagnostic notes.
Restarted/reloaded everything multiple times, no effect. Reset controller to defaults, no effect. Tried different channels/CC's to no effect.

If the color mixer profile (any of them, or new one) is loaded by the controller or by the options (panel opening) then an adjustment causes a switch to the tone curve panel/profile... it often registers as a "multiple settings" adjustment. I'm wondering if it is related to the behavior I noted where toggling the tone curve visibility off reverts on it's own instead of updating the history.

But, if I load a color mixer profile manually this does not happen. It doesn't matter which profile.

**Comment by rsjaffe** [comment]
I found an error in the Database that is causing that problem.  https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.6.1 fixes it.

**Comment by StevenKersting** [comment]
Thank you!
