### ISSUE TITLE
BCF2000 no longer moves sliders between photos with 0.4.1

### ISSUE THREAD

**Issue by DaveSchneider42** [rsjaffe/MIDI2LR#19]
In 0.4.0, my BCF2000 would move all the sliders to current settings between photos. In 0.4.1, that no longer happens.

**Comment by rsjaffe** [comment]
Please restart LR and see if it functions. Otherwise, reboot. 

The plugin should then function normally.

This is a known issue when updating the plugin and appears to be a LR problem, though we're not sure yet.

**Comment by rsjaffe** [comment]
This information now in FAQ
