### ISSUE TITLE
Feature Request: Disable checking and/or notification of new versions

### ISSUE THREAD

**Issue by laklare** [rsjaffe/MIDI2LR#190]
While checking for new versions and being notified has its uses, I would like to eliminate the dialogue box that notifies me of every minor update. It won't go away until I install a new release, which takes up my time. I'd rather not upgrade every time for features that don't apply to me. Would blocking the executable using a firewall prevent these update checks? A better solution, of course, would be to disable it in the MIDI2LR in some future release. Thank you.

**Comment by rsjaffe** [comment]
Blocking with the firewall should prevent update checks. I'll add your request to be able to disable the dialog to #31

**Comment by laklare** [comment]
Wonderful, thanks!

**Comment by rsjaffe** [comment]
Wrote and tested code. It'll be in the next version. What it will do is, for each new version, show the dialog once only.
