### ISSUE TITLE
Contrast does not work on Version 0.9.6.1

### ISSUE THREAD

**Issue by EugeneMichel** [rsjaffe/MIDI2LR#192]
Not sure if its only me, but Contrast adjustment doesn't work for me on Version 0.9.6.1. It works on Version 0.9.6 though and all versions before it. All other adjustments work for me. Just leaving here as feedback, I am using 0.9.6 now. Using BCF2000.

Keep up the great work!

**Comment by rsjaffe** [comment]
Pushed out a fix with a new release number, as contrast is used a lot. Turns out to be a timing issue in Lightroom, where changing a panel followed immediately by a control change causes the control change to be ignored. Changed the order, everything is ok.
