### ISSUE TITLE
MAC OS X El Capitan and Korg nanoKONTROL 2 not working after MIDI2LR update

### ISSUE THREAD

**Issue by mikkiweb** [rsjaffe/MIDI2LR#193]
I have a problems after update of MIDI2LR plugin and update on Mac OS X El Capitan, my Korg nano Kontrol 2 is less responsive and few buttons and sliders are not working

**Comment by rsjaffe** [comment]
We did almost nothing to the application, other than changing the way it responded to a "shutdown" request, so it shouldn't affect the running behavior. Have you tried rebooting? I wonder if something's messed up with the driver. We have a lot of different things going on with MIDI2LR--hardware, MIDI driver, MIDI2LR app, MIDI2LR plugin, LR; so problems may arise from all sorts of different sources.

**Comment by mikkiweb** [comment]
I've removed plugin and activated it again from another folder location. Now i have issue with contrast, i've dedicated one slider for contrast and its very unresponsive and when I move another slider it changes contrast value in very unlogic way. Is there a way to fix it ?

**Comment by rsjaffe** [comment]
1. Look at your profile file. Do you have more than one slider assigned to contrast? If so, remove the second control from contrast, and see if that fixes things.
1. If that's not the problem, I'm afraid the most likely source is your device driver or your device. Did you buy your device used? If so, check to see that it is programmed to its default settings, then check that the buttons are set to "toggle-off" mode.
1. If your device is new, I'd suspect your MIDI driver. Make sure you have the proper version for your machine.

**Comment by mikkiweb** [comment]
I am going to try with a new driver, i bought it new, only used few times, its working on windows pc that i am not using often.

**Comment by StevenKersting** [comment]
Mikki, the contrast slider issue was fixed w/ 9.8

**Comment by mikkiweb** [comment]
Thanks my friend, I will try it tomorrow

**Comment by rsjaffe** [comment]
Is it working now?

**Comment by mikkiweb** [comment]
Now it works perfect with new version of plugin.

Is there an option to copy only selected settings, not all. For example i want with to copy only settings without crop if i cropped previous photo

**Comment by rsjaffe** [comment]
Yes, see: https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#paste-selections
