### ISSUE TITLE
Temperature adjustment not working

### ISSUE THREAD

**Issue by ojobojo** [rsjaffe/MIDI2LR#194]
Great plugin, thank you very much! One issue i am having on windows 7 and LR 6.1 is that the Temp adjustment is not picking up any input from the MIDI controller. All other functions are working (I haven't tried all). I am using an Arturia beatstep controller.

Bogo

**Comment by rsjaffe** [comment]
Are you using the latest version of MIDI2LR? I rechecked it, and the temperature control works. Also, try assigning temperature to a different knob or fader -- just in case it is a hardware problem with the controller. If you're still having trouble, please zip up your parameters XML file and reply to this message, and drag a copy of the zip file into your reply (Github will upload zip files and automatically link them to the message).

**Comment by losinternet** [comment]
Temperature with 0.9.7 is working for me too

**Comment by ojobojo** [comment]
Thanks for the quick response. I got 0.9.7 today and checked it again with all the knobs on the controller and it's still not picking up the temp :/ Everything else seems to be working including ResetTemp and custom white balance sets Here is the zip file.

**Comment by ojobojo** [comment]
hmm here is the XML code from the settings file. Everything looks in order

<?xml version="1.0" encoding="UTF-8"?>

<settings>
  <setting channel="1" NRPN="False" Relative="False" controller="103" command_string="Temperature"/>
  <setting channel="1" NRPN="False" Relative="False" controller="102" command_string="Tint"/>
  <setting channel="1" NRPN="False" Relative="False" controller="104" command_string="Temperature"/>
</settings>

**Comment by ojobojo** [comment]
[temperature test.txt](https://github.com/rsjaffe/MIDI2LR/files/136655/temperature.test.txt)

**Comment by ojobojo** [comment]
Text file as the zip is not being recognized as such :/ It all looks well in order to me

`<?xml version="1.0" encoding="UTF-8"?>

<settings>
  <setting channel="1" NRPN="False" Relative="False" controller="103" command_string="Temperature"/>
  <setting channel="1" NRPN="False" Relative="False" controller="102" command_string="Tint"/>
  <setting channel="1" NRPN="False" Relative="False" controller="104" command_string="Temperature"/>
</settings>
`

**Comment by ojobojo** [comment]
Text file as the zip is not being recognized as such :/ It all looks well in order to me

**Comment by losinternet** [comment]
Looks like you have two midi knobs/controls assigned to Temperature.  
Try deleting one of them.

`<?xml version="1.0" encoding="UTF-8"?>

<settings>
  <setting channel="1" NRPN="False" Relative="False" controller="103" command_string="Temperature"/>
  <setting channel="1" NRPN="False" Relative="False" controller="102" command_string="Tint"/>
</settings>
`

**Comment by ojobojo** [comment]
Thanks, that was for the sake of the test. Even with only one assigned to Temp it's not picking it up. Completely baffled. 
[temperature test 2.txt](https://github.com/rsjaffe/MIDI2LR/files/136662/temperature.test.2.txt)

**Comment by ojobojo** [comment]
I deleted and re-added the plugin. Restarted lightroom a few times but still  nothing.

**Comment by rsjaffe** [comment]
Delete temperature from the control you currently have it attached to, and assign it to a different control. Does it work now? Also, do you have pickup mode set? Have you set temperature limits?

**Comment by ojobojo** [comment]
Hello, I tried assigning to each of my rotary controls - didn't work with any of them :/ 

Pickup mode is enabled.

I don't think there are temperature limits. Where do you set them?

**Comment by rsjaffe** [comment]
In the application options dialog. https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog#limits

**Comment by ojobojo** [comment]
Thank you kind sir, that  was the culprit. All good now.
