### ISSUE TITLE
Beatstep Arturia absolute value

### ISSUE THREAD

**Issue by joris818** [rsjaffe/MIDI2LR#195]
So I was really wanting to try MIDI2LR so I went to the store and got me an Arturia Beatstep.
I like the quality of the device, feels sturdy, looks nice and doesn't cost to much.

I do seem to have one big problem that I can't seem to solve.
If I turn a knob, it goes to a certain value (between 0 and 127). So say I map knob 1 to exposure.
For photo 1 it put my knob value to 127 (over expose really hard).
I then go to photo 2. This one needs just a couple of clicks of under exposing. 
I twist knob 1 a couple of clicks to the left. All of a sudden my exposure spikes up and goes to the value of photo 1 (127).

Is there a way of making my knobs give a signal of +1 of -1 instead of an absolute value?

I'm really hoping there is a solution, I love the potential of this. Thanks in advance guys !

**Comment by joris818** [comment]
So basically I want MIDI2LR to level out all my knobs when I select a new photo. So that -if I turn a knob- it will start changing from that point, instead of the point that was made in the previous photo.

(I apologize for my terrible English)

**Comment by rsjaffe** [comment]
There is a way of fixing the problem. It doesn't give the knobs relative value. What it does is not change the exposure until you have moved the knob to the current value for that picture. That way you don't get those jumps. See the two pictures below. 

First, you click on **Settings** in the MIDI2LR app (circled in red).
![2016-02-18 1](https://cloud.githubusercontent.com/assets/1431301/13164104/9d0d1570-d667-11e5-8c06-9684e1ad4c74.png)
Then, on the settings dialog, click **Enable Pickup Mode** then close the dialog. Now the controller won't have an effect until you move it to the current value for the current picture. If you want to see how far away you are from the current setting, enable **Show status and activity** in the plugin (see https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog#show-status-and-activity). When you move the knob, you will see both the knob value and the picture value, so you can see when you're getting close to the picture value.
![settings](https://cloud.githubusercontent.com/assets/1431301/13164107/a5ebe28e-d667-11e5-88ab-b5404829e3be.png)

**Comment by rsjaffe** [comment]
I've added these instructions to the Wiki. https://github.com/rsjaffe/MIDI2LR/wiki/Application-Settings

**Comment by JesseSavage** [comment]
joris818, I just got the Beatstep, myself. I am having issues with the knobs registering with LR and it's very inconsistent. Did you have any issues with getting yours working?

**Comment by joris818** [comment]
I actually have bad new for you. I returned the Beatstep and switched over
to a Behringer X-touch mini.
I couldn't get the beatstep configured correctly to adjust al the knobs the
correct way.

2016-11-07 9:07 GMT+01:00 JesseSavage <notifications@github.com>:

**Comment by rogasgr** [comment]
hmmm...i thought also that Arturia Beatstep would work good but there is that issue that you mentioned joris818. Also when seting the Knobs as relative then Midi2LR does recognize the the knob as let's say a button with two values.

**Comment by cookiebaker** [comment]
Hi there,

I'm not sure if this is also relevant for (Midi2)Lightroom but here's how I have fixed this for Capture One.

In the Artura Midi Control Center I set all the dials
to relative. With Bome Midi Translator Pro I converted the up and downward 'motion' to separate keyboard shortcuts. With my controller the Midi gives a value of 65 for everything going up and 63 for everything going down. In capture one there's a shortcut for exposure up and exposure down. Dial the knob and it goes up (or down)...go to the next photo it just goes up and down from whatever value the exposure slider (or a different slider) is on at that moment.

**Comment by joris818** [comment]
Thank you cookiebaker,

I have in the meanwhile bought a Behringer x-touch mini. This works
perfectly.
I'm a very very happy user now !!!

Greets !

2017-02-26 11:46 GMT+01:00 cookiebaker <notifications@github.com>:

**Comment by cookiebaker** [comment]
Hi Joris,

Cool! Maybe it will help someone else down the line. 

Out of curiosity does the X touch mini have relative or absolute dials? And how do you effectively reset them when you edit another picture?

**Comment by joris818** [comment]
The X-touch mini has relative dials.
I don't have to reset anything. I set certain settings at one photo, when I
switch to the next photo, the controls reset to 0. When I than switch back
to the previous (edited) photo, it jumps to the last used settings.
So the dials are always in the correct spot.

Except for when I use a different layer, switching between layers resets
everything.

2017-02-26 11:53 GMT+01:00 cookiebaker <notifications@github.com>:
