### ISSUE TITLE
Certain keystrokes don't work with non-English keyboard layout (Windows)

### ISSUE THREAD

**Issue by phaul2001** [rsjaffe/MIDI2LR#201]
Hello,
I set up Midi2LR with TouchOSC, TouchOSC bridge on a Windows 8 Computer.
MIDI2LR detect correctly the Midi channel.
I allocate the LR function.
A lot of functions doesn't work, e.g. rotate left, rotate right, increase grid size etc. Delete rejected function works as rotate right.
Other functions work correctly. it seems the error is manly with the miscelleanous functions.

Regards

**Comment by rsjaffe** [comment]
Could you try the following functions (miscellaneous in your version):
* Cycle Lights Out
* Show/Hide Side Panels
Do either of those two work?

See http://windows.microsoft.com/en-us/windows/change-keyboard-layout#1TC=windows-7 for help in answering the next questions:

What is your input language?
What language is your keyboard layout?

Another suggestion--after testing the above, if you are still having problems, download the second beta of 0.9.8 https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.8. Note that the menus on the app have been rearranged. See https://github.com/rsjaffe/MIDI2LR/wiki/Commands for a map of the commands.

**Comment by phaul2001** [comment]
Cycle Lights Out -> work perfectly
Show/Hide Side Panels  -> work perfectly

What is your input language? -> German (LR is also German)
What language is your keyboard layout? -> German (QWERTZ)
Do you use more than one keyboard layout? -> no, not as far as I can check it in Windows

In my initally post I just list roughly some problem functions. Would it be helpful for you to have a more detailed list?

**Comment by phaul2001** [comment]
Breaking News, after switching both LR and my keyboard  to English (US) layout it seems to work now (except "Delete rejected flaged photo".

**Comment by rsjaffe** [comment]
> In my initally post I just list roughly some problem functions. Would it be helpful for you to have a more detailed list?

If you remember what didn't work and what did, a list would help. This sounds like an issue in the keyboard scan code translation, which I thought had been handled successfully.

**Comment by phaul2001** [comment]
The following situation could be reproduce:
The correct function is solely if LR is in English and the keyboard layout is in English.
Any mix configuration doesn't work.
-> function "delete rejected" doesn't work in neither configuration

-> in the following the situiation with keyboard layout and LR in German:
rotate left: doesn't work
rotate right: doesn't work
show/hide all panels: work
grid size increase: works as "next photo" and display tool tip " rating:0"
grid size decrease: work
virtual copy: work
grid view: work
full view: work
previous photo: work
next photo: work
flag rejected: work
no flag: work
modul library: work
modul develop work

**Comment by rsjaffe** [comment]
Thanks. Traveling right now, will look into this when I have a chance.

Are you using a physical keyboard or a virtual one (keyboard on screen)? When you change layouts, are you swapping out physical keyboards or using the same in each layout?

**Comment by phaul2001** [comment]
I use a physical keyboard (QWRTZ) with all the layouts. The MIDI device is an ipad with TouchOSC running.
I discover that some function via MIDI doesn't work but with the keybord (e.g. I for information toggle/ F for full screen/ Delete/ command,alt,A for select flagged).
I also found a function where it work in combination with shift instead of discribed combination with command. Unfortunately can I remeber by heart the function.

Have a safe trip. Cheers.

**Comment by rsjaffe** [comment]
Could you replace MIDI2LR.exe with the file of the same name that is in the zip file below? It has been altered to handle AltGr correctly (I hope). There may still be some work to fix grid size increase, but test that one, too. Thanks.

[MIDI2LR.zip](https://github.com/rsjaffe/MIDI2LR/files/159993/MIDI2LR.zip)

**Comment by phaul2001** [comment]
Check with new MIDI2LE.exe and both LR and Keyboardlayout in GER. Seems not to be improved.

rotate left: doesn't work
rotate right: doesn't work
grid size increase: works as "next photo"

**Comment by rsjaffe** [comment]
What keystrokes does lightroom expect in German for rotate left, rotate right, grid size increase?

**Comment by rsjaffe** [comment]
Try latest release--it should have fixed the issue: https://github.com/rsjaffe/MIDI2LR/releases
