### ISSUE TITLE
MIDI2LR doesn't open with latest profile (release 0.9.8)

### ISSUE THREAD

**Issue by phaul2001** [rsjaffe/MIDI2LR#202]
Hello,
I set up MIDI2LR_ with TouchOSC, TouchOSC bridge on a Windows 8 Computer.
MIDI2LR detect correctly the Midi channel. I allocate functions and save the profile in allocated folder.

With the restart of LR an old profile comes with MIDI2LR. I have to load manually the last used profile.

Regards

**Comment by rsjaffe** [comment]
Did you save the profile? MIDI2LR doesn't automatically save profiles. Also, make sure not to save the profile as "defaults.xml" in the plugin directory, as that file has a special use.

**Comment by phaul2001** [comment]
Yes, I save the profile and with a specific name. but there is also an older file of mine also in the folder. This is the one, that MIDI2LR load with the start. I will delete this old file and try it with just one file in the folder.

**Comment by phaul2001** [comment]
TaTaa, after having just the new profile in the folder it loads this one.

**Comment by StevenKersting** [comment]
When you open the profile folder (i.e. such as to manually load) the file at the top of the list is the one that is loaded w/ MIDI2LR. I use numbers to start the profile name to ensure the one I want by default loads initially.
