### ISSUE TITLE
Request for commands to implement

### ISSUE THREAD

**Issue by phaul2001** [rsjaffe/MIDI2LR#203]
Hello rsjaffe,
I really appreciate MIDI2LR. thank you for your work.

I would like to kindly request  some commands I miss to allocate.
- snapshot (in the development modul you can make a snapshot of the protocoll so far)
- direct access to the import and export dialog
- Zoom direct to 1:1
- Zoom direct to "fit"
- toggle information
- possibility to allocate more presets 
- to allocate the arrow keys for navigation in grid view

I don't know if technical possible but it would be great to allocate tags to keys and tag the photos then directly.

regards
phaul

**Comment by rsjaffe** [comment]
> I don't know if technical possible but it would be great to allocate tags to keys and tag the photos then directly.

Are you referring to keywords? If so, LR makes it harder than it should be for a plugin to add keywords. I might attack that in a later version.

> possibility to allocate more presets

Currently you can allocate 20 develop presets. Do you need more? How many?

**Comment by phaul2001** [comment]
-> yes, I referring to keywords. It would be nice to tag the selected photo(s) just by pushing a key. 

-> devolp presets: as much as possible ;-). in addition to a lot of film simulation presets,  I have a lot develop presets defined to use as "short cuts". It would be nice to use them with "hotkeys".

**Comment by rsjaffe** [comment]
In next release, presets increased to 40. That's as far as I can go without making the dialog box too big.

Added toggle information.

Don't know if there is a zoom direct to 1:1 shortcut or a zoom direct to 'fill' shortcut.

**Comment by e-savarese** [comment]
Hi rsjaffe

Thanks for your awesome work!!!! I was wondering if there was a keystoke to Switch crop between portrait and landscape orientation or vice versa whilst in the crop mode (x) 

I have a feeling that (x) may already be allocated to flag/reject a photo... 

Ps Thanks for all your hard work... 
(I have donated recently!!! :) )

Cheers

**Comment by phaul2001** [comment]
> Don't know if there is a zoom direct to 1:1 shortcut or a zoom direct to 'fill'  shortcut.

-> Z toggle zoom view  between 1:1 zoom and Fit into window

> What type of "snapshot" are you talking about? What is the keyboard shortcut?

In the Develop module "Create Snapshot WIN:Ctrl N , MAC:Cmd N"

**Comment by rsjaffe** [comment]
With the keyboard shortcuts, the label doesn't really matter, only the keyboard shortcut. I had attached labels to make it easier for people to find what they need--if there already is an x command, even though it's labeled flag/reject a photo, it can be used to switch orientation. I will probably add it into the develop section, too, so that it's easier to find.

**Comment by rsjaffe** [comment]
See #31
