### ISSUE TITLE
Keyboard emulation of alt key

### ISSUE THREAD

**Issue by StevenKersting** [rsjaffe/MIDI2LR#204]
I haven't been able to test keyboard emulation (mac) yet. And I don't think it's a command/option in MIDI2LR. But have you checked to see if a MIDI command for ALT works with the sliders? If it does it would be worth assigning it it's own function.

**Comment by rsjaffe** [comment]
I've tried ALT on the keyboard with MIDI2LR, and it doesn't work. Others have noticed the same bug. So I haven't tried emulating holding the Alt key down. I figured if it doesn't work with the real keyboard it can't work with the virtual one. See  #112  #40  #5

**Comment by StevenKersting** [comment]
I knew it didn't work with the keyboard... but you never know it could work for some unknown reason.

**Comment by rsjaffe** [comment]
OK. OK. I'll give it a shot. Though the way the keystrokes get sent to LR, I doubt there'll be a difference.

Question: should the alt key just be down while the control is being dragged, or should it be down for a period after (e.g., 1/2 second) or should there be a button that toggles the alt key down/up?

**Comment by StevenKersting** [comment]
Personally, I would use a button. But if it works, then a separate option for down while moved might suit some better.

**Comment by rsjaffe** [comment]
Thanks. Button is the easiest to implement.

**Comment by rsjaffe** [comment]
OK, tested. Definitely was able to emulate alt down, and that worked with directly moving the slider in LR. Did not work with moving the slider in MIDI2LR. Will not implement.
