### ISSUE TITLE
A way to edit in external editors ?

### ISSUE THREAD

**Issue by funkfu** [rsjaffe/MIDI2LR#205]
Hello, thanks for MIDI2LR, it's treallly really really a great and cheap solution for my workflow.
I don't know if it's the good interface to ask you something : is there a way to map a digit on my korg nanokontrol to "edit in photoshop", or maybe in "nik software", "radlab"...(others plugins).
Thanks a lot !!!
marco, france.

**Comment by funkfu** [comment]
oh sorry, i haven't read the whole page... i read you need help for this... sorry dude, i'll wait !

**Comment by rsjaffe** [comment]
Actually there is now a way to put in those commands. Look in the wiki under Commands--look at the bottom of the first table. There are two commands: one for edit in photoshop, one for edit in other. You set the "other" application in Lightroom.

**Comment by funkfu** [comment]
Thanks for your answer ! ...i found it on v0.9.9, but it doesn't work... my
externals editors are set up in lightroom (preferences/external editor), it
works perfectly with right clic, but not with midi2lr/nanokontrol2... my
mac ( yosemite 10.10.5) make the sound "booo" (bad command)...


2016-02-27 18:09 GMT+01:00 rsjaffe <notifications@github.com>:
