### ISSUE TITLE
Plugin doesn't update led position on Novation Nocturn

### ISSUE THREAD

**Issue by boomerek** [rsjaffe/MIDI2LR#206]
Hello

Great plugin but there is one problem with the way it works. Every slider has to "picked up" as plugin doesn't update/sync knob led positions with LR sliders (at least on Novation Nocturn). 
Paddy plugin used to do that without any problems so I hope it can be done here.
this video explains it better:
https://youtu.be/M68543e80D4?t=4m1s

**Comment by rsjaffe** [comment]
Odd. MIDI2LR does send data back to the MIDI controller on the current position in LR, so motorized faders and LEDs on encoders track it. I use a Behringer BCF2000 with no issues, and I haven't heard of issues with other controllers. Is there something special about how the LEDs are addressed on the Nocturn? Which values are you trying to control?

**Comment by boomerek** [comment]
Thanks for that reply rsjaffe as once I knew it should actually work I started to dig deeper in different settings and I found the solution!
In automap 4 Software I had to change in Software Setup/MIDI Ports/In to "All" and now it works!

Thanks!

**Comment by boomerek** [comment]
Ok, I jumped into conclusion a bit prematurely. It seems that the issue is a bit more complicated.
Plugin works and send data back to MIDI controller but ONLY with RAW files and doesn't when editing  PSD or TIFF files. 
It seems like it's a plugin issue after all.
