### ISSUE TITLE
Dedicated website for MIDI with Lightroom

### ISSUE THREAD

**Issue by emkorec** [rsjaffe/MIDI2LR#208]
Hi All,
I have created an informational website with every information needed for starting MIDI controlling Lightroom, called midi2lightroom.com. Of course MIDI2LR plugin got an emphasized role on the site. (and rsjaffe: I did not forget to mention your Donate button several times on the site ;) ).
This is the first website in the topic so it fills in the blanks.

I guess most of you guys here already own the knowledge I provide on midi2lightroom.com but if you have a friend who is starting MIDI controlling LR just recently, you'll be able to send them the link to get every information he/she needs.
That means:
- Introduction explaining the use of a MIDI controller in Lightroom
- Software requirements (LR plugins like MIDI2LR, download links)
- Hardware requirements (controller types, difference between rotary knobs, encoders, sliders and motorized sliders, using Layers/Presets/Banks or Profiles with MIDI2LR, Editor softwares for controllers,...)
- Suggested MIDI controllers for LR-use
- Installation guides for certain controllers and LR plugins (text and video tutorial)
- Download section for importable (sample) mapping files
- Sticker layout for labelling controllers
- Discussion forum

Although only basic (but most important) information is free to access on the website, the registration for advanced sections cost just a couple of bucks.

I hope this site will help to spread the new wave. I believe that every photographer should use controller for Lightroom. I use it for more than half a year now and I'm addicted. :)

**Comment by rsjaffe** [comment]
Thanks! :smiley:

**Comment by StevenKersting** [comment]
IDK... a pay/subscription site based on open source software (donation ware) and widely available information.
I sure hope there is something of significant value to justify it.

**Comment by emkorec** [comment]
I offer everything in one place for a small amount of money. I do not offer donationware for money or such. And yes the information is maybe widely available but on a thousand place all around the web. Now it is gathered into one place. Let me tell you an example: you can do workout for free. Despite the fact that doing pushups is free for everyone, and there is a buch of fitness plans and apps on the web, some people still go to a professional trainer in a fitness club. Or buy a book, read fitness magazines and so on. Also learning skiing is for free, you only need to practice enough to learn it at some level. But if you go to a ski-instructor you will develop faster.
My point is that I remember how hard was for me to start with my Nocturn and MIDI2LR. I had no idea about CC-codes, no idea about Automap, no idea about the difference of rotary knobs and encoders, or about pick-up technology. I did not know that only Nocturn and Behringer BCF are the only controllers suitable for Lightroom, or other controllers can be used too? In fact half a year ago I even did not know that MIDI controllers exist. I had to study this story for weeks and month to get the knowledge. I am the editor of a popular photography blog in Hungary, at the beginning I posted every knowledge there and people were interested. In fact I can say that I started the new wave (MIDI controlling Lightroom) in Hungary with my blog and the posts about the topic in there. After it I made a website in Hungarian that gathered all the information from my relevant blogposts, so I made some kind of framework for the knowledge. After these came the idea to make it international and add plus information, spicing it with video tutorials, controller overlay samples, user guides and everything that people require to start MIDI controlling Lightroom as quick as possible. If you are a DIY guy, you just read the free version of the site and go on by yourself. You will have much more information like this than I had at the beginning. If you a tutorial-fan guy, and you need to be teached by someone else, then you pay 9 bucks and will get everything you need. I guess 9 bucks is a small change for so many information.

**Comment by emkorec** [comment]
Here is the TOC of the paid version. I hope it justifies :)
![mid2ltrm-pro](https://cloud.githubusercontent.com/assets/17280850/13501702/00f034a4-e168-11e5-9dad-2cffcccdc1e5.jpg)

**Comment by rsjaffe** [comment]
Now I will say that, ultimately, I hope to have better setup information on this site--both developed by me and contributed by others, and have that freely available. So I would hope that support specific to MIDI2LR would be available for free. However, MIDI2LR's license does allow commercial use by others--the intent of the license is only to guarantee that MIDI2LR is free and that users can get it for free, not to prevent others from making money off of it.MIDI2LR uses GNU GPLv3. [Wikipedia gives a general overview of its effects, though if there is any conflict between what is written in the article and what is in the actual license, the license applies.](https://en.wikipedia.org/wiki/GNU_General_Public_License)

**Comment by emkorec** [comment]
That's clear. MIDI2LR is mentioned on my website on a page that is free to view for every visitor. The download link for MIDI2LR sends the visitor directly to its Project Page (http://rsjaffe.github.io/MIDI2LR/). I do not store the software on my servers I just talk about it and send the visitors to here if they are interested. (You can check it by yourselves: http://midi2lightroom.com/index.php/en/softwares). As for the paid website there are only installation guides and mapping profiles made by me. 
If you will create a user guide, obviously I will mention it on my website that it is available and it is free for everyone.
So keep calm guys I do not make money from freeware, I do not use MIDI2LR commercially, I am just trying to help people start with MIDI controllers because I love it and I want more people to discover it. (and would like to earn some money because I worked much with this site and with this topic in the recent months). Actually if I had enough money, moreover if I had enough knowledge I would create and sell something like Palette Gear especially for Lightroom, moreover I'd buy Capture One licence too, but much better than PG (and maybe on much lower price because PG is extremely expensive).

**Comment by rsjaffe** [comment]
Actually, my comment was meant to be taken in the other direction. People are free to make money from MIDI2LR. That's definitely permitted in the license.

I was just expressing hope that I can improve support for MIDI2LR here, on github. I see where I misworded it **So I would hope that support specific to MIDI2LR would be available for free.**  was too broadly worded--it was just referring to the prior sentence, where I was talking about putting better setup information on the site, and probably should have left the second sentence out.

I'm giving you a long reply, as I find it very difficult to judge tone of voice when communicating via text, as we are here. I am fine with what you are doing.

**Comment by StevenKersting** [comment]
If I were upset about it I would have used harsher wording.

**Comment by rubin110** [comment]
Slightly related. This thread kinda bummed me out, especially after searching for MIDI2LR with the term midi2lightroom and having that other site pop up. It's actually a little hard to tell that midi2lightroom is unrelated to this open source project, and I was about to give that site money.

Sooo.@rsjaffe, any way I can donate money to your project through a channel other than Paypal? :)

**Comment by joris818** [comment]
Is it inappropriate to ask where you found that BCR2000 sticker?
I'd like to print one ;-)

**Comment by rsjaffe** [comment]
I haven't set up a donation channel other than PayPal. You don't need a PayPal account to use it, though.

**Comment by SergeDubovsky** [comment]
Hi, @rsjaffe. I just created a login and paid for the subscription. However, nothing happens when I try to log in. It bounces me back to the login page. Same thing happens when I try to reset the password.
Can you take a look? 

Thank you.

**Comment by emkorec** [comment]
I'll check it

**Comment by emkorec** [comment]
Done. Now it should work

**Comment by SergeDubovsky** [comment]
It does work now. Thank you.
