### ISSUE TITLE
sending keys not working at all on OS X 10.10.5 - german

### ISSUE THREAD

**Issue by WaellerKlaus** [rsjaffe/MIDI2LR#209]
it appears I can’t get any keys sent, neither to any Text-Editor nor to LR. I was following the test instructions given here: [https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.9](https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.9)

I’m using the following system:
- MIDI2LR Version 0.9.9
- OS X Yosemite Version 10.10.5 (14F1021) Kernel-Version: Darwin 14.5.0
- Apple Internal Keyboard german (Product-ID: 0x025a, Vendor-ID: 0x05ac (Apple Inc.), Version: 2.24) MacBook Pro (Retina, 13-inch, Late 2013) 
- tested Apps:
-  - Lightroom: 6.4 [ 1060496 ]
-  - TextEdit Version 1.10 (319)
-  - TextWrangler version 5.0.2 (3786)

Anyway, thank your for adding the keystroke commands. They’re really helpful (if working ;) )!
How can I help tracing the issue?

Cheers,
Klaus

**Comment by rsjaffe** [comment]
Thanks for the feedback. I'm going to put together something in the next couple of days to start digging into the issue.

**Comment by WaellerKlaus** [comment]
Take your time. I won't be able to look at it before tomorrow evening.
Cheers,
Klaus

**Comment by rsjaffe** [comment]
Try the latest release. It should have fixed the issue: https://github.com/rsjaffe/MIDI2LR/releases

**Comment by rsjaffe** [comment]
See #232
