### ISSUE TITLE
"NOT CONNECTED TO LR" ON MAC

### ISSUE THREAD

**Issue by hunterpp** [rsjaffe/MIDI2LR#21]
WHY?? 

![image](https://cloud.githubusercontent.com/assets/772917/10151391/18e798d2-6615-11e5-860d-bafa727f7b8b.png)

**Comment by rsjaffe** [comment]
Please describe the circumstances behind this. For example, was this immediately after updating the app? In what sequence did you open the programs?

See the FAQ in the [wiki](https://github.com/rsjaffe/MIDI2LR/wiki)
