### ISSUE TITLE
Changes to parameters with no input made on midi device

### ISSUE THREAD

**Issue by censrd** [rsjaffe/MIDI2LR#210]
Hi, So i'm using the latest 9.9 version on windows 10, with a Akai APC40mk2 midi controller. The software seems to be picking up changes in values from the controller without any input to the controller. 

I have tried using Midiox to monitor if the apc device is actually sending data to the PC, but it shows nothing being sent unless I actually hit a button or move a slider. Eg even if the last input was on slider that sent Midi note 1: CC55 (100), after the value has been set it then jumps back to whatever note it decides to get stuck on say 1: CC48 (50) and just keeps flashing green as if input has been made on that channel. Yet there is no change in the actual value. 

Interestingly even if i turn off the midi device the software still thinks it is receiving new input data. Also noted that if i turn the affected channel down to 0 it then jumps to the next highest numbered channel. ie 1: CC47. I have attached a screen capture of what is happening in case my explanation doesn't make sense.
[midi2lrissue.zip](https://github.com/rsjaffe/MIDI2LR/files/160874/midi2lrissue.zip)

Also seperatly i have noticed that when midi2lr is loaded I am unable to use the mouse to select develop presets or reset any development changes.

**Comment by rsjaffe** [comment]
I'll look at the screen cap later, but the mouse problems caught my eye. MIDI2LR does nothing special with the mouse, so the mouse problems indicate something more is going on with your configuration. Do you have other software running that interacts with your MIDI controller at the same time you're using MIDI2LR? Does your MIDI controller have the capability to control the mouse?

**Comment by censrd** [comment]
That's me moving the mouse in the video, for example if I want to adjust
something further down the develop panel I'll use the mouse to scroll down
but due to the issue I'm having the panel quickly goes back up making it
near impossible to make any develop adjustments that aren't already mapped
to my midi. No other software is using midi, it was only in trying to find
what might be causing the issue did I use midi of.

**Comment by censrd** [comment]
Last word was meant to say midiox

**Comment by rsjaffe** [comment]
Honestly, the video didn't help--I'm still a bit confused. But---
What mode are your controllers in: they should be in absolute mode, not relative, and should be standard range, not extended range.
Have you used MIDI-Ox to watch what your controller sends when you move the slider to zero?

**Comment by StevenKersting** [comment]
I think the controller setup is the issue. is it in note, or cc mode? Hold or toggle? Have you tried resetting it?

**Comment by censrd** [comment]
Sorry for the delay in replying, So after looking through the manual from what i can work out I believe that the controller is in absolute mode, But not sure if standard or extended range as there is no mention of this anywhere in the manual. When i move the slider or knob to 0 it shows as 0 in midi-ox. There are buttons and knobs as well as sliders on this controller, and from what I can work out the buttons are note mode but pretty much everything else such as the knobs are in cc mode. Not sure of hold or toggle, and yes have tried resetting many times. I will make another quick video and attempt to make it clearer as to the issue.

**Comment by rsjaffe** [comment]
You may need to look at some of the documentation for your controller (e.g., the Communications Protocol Document at http://www.akaipro.com/index.php/product/apc40-mkii#downloads). Also, this site may help: http://createdigitalmusic.com/2009/06/apc40-hacking-superguide-monome-emulator-midi-tricks-and-the-handshake/ , though they say:

> The APC itself is strikingly limited for a MIDI device, without even basic abilities like preset switching or the ability to change default MIDI assignments
