### ISSUE TITLE
Actions don't match midi descriptor

### ISSUE THREAD

**Issue by Photog222** [rsjaffe/MIDI2LR#211]
This is so awesome - thank you so much!  I am having trouble getting just a few tasks to work after they are assigned.  "Increase Size" and "Decrease Size" on Local Adjustments menu are changing the **Rating** instead of changing brush size. And "Edit in Photoshop" in General menu is opening my export menu instead of opening photo in photoshop.    I'm sure it must be my fault, but any help is greatly appreciated I'm a newbie.  :-)  (Windows 10 with Lightroom CC - Korg2)

**Comment by rsjaffe** [comment]
Those are just keyboard shortcuts-- increase/decrease brush size only works while working with a brush. In the Library view, the same key shortcuts increase/decrease ratings. The Edit in photoshop is just Control E, so it has different effects in different locations.

**Comment by Photog222** [comment]
Thank you - I still can't get it to 'Edit in Photoshop' in Library or Develop module....it just goes to "Export file."   The keystroke "Control E" works, but is it possible to program a key to be Control E?   Sorry to be such a dork.
