### ISSUE TITLE
Keyboard not working commands list (Italian)

### ISSUE THREAD

**Issue by AlePhoto** [rsjaffe/MIDI2LR#212]
Hi rsjaffe, here below is my updated list of some commands that doesn't work properly:

paste from previuos;
rotate left, rotate right;
stack photos (unstack works!);
toggle stack;
delete rejected;
delete;
"full screen preview" works as toggle view mode;
edit in photoshop works as export dialog box;
show clipping works as rotate left;
auto-tone works as auto WB;
increase grid size works as zero stars (decrease works fine);
cyle grid view style works as rotate left;
primary display info works as go to develop module;
show cycle info style works as go to develop module;
swap images works but also assign a green label while swapping;
show/hide toolbar doesn't work;
select all doesn't work;
select none works as select active photo;
select flagged photos doesn't work (deselect unflagged works);

NOTE: I use windows7 LR CC and Keyboard in italian. If I can help you with more test let my know.

Regards

**Comment by rsjaffe** [comment]
Could you tell me what the keyboard shortcuts are for those commands in the Italian version of Lightroom? And are you using MIDI2LR 0.9.9?

**Comment by AlePhoto** [comment]
I'am using last relase 0.9.9;
here they are:

paste from previuos = ctrl+alt+v
rotate left, rotate right =  shift+j, shift+m
stack photos (unstack works!) = ctrl+g; ctrl+shift+g=unstack
delete rejected = ctrl+backpace
delete =canc
"full screen preview"= f
edit in photoshop = ctrl+e
show clipping=j
auto-tone = ctrl+u
increase grid size= + 
cyle grid view style=j
primary display info and cycle =i
swap images = up arrow (in compare view)
show/hide toolbar = t
select all ctrl+a
select none =ctrl+d
select flagged photos ctrl+alt+a

I don't think these shortcut are differnet from yours, right?
thanks!

**Comment by rsjaffe** [comment]
Oh boy, this is what I was worried about. Lightroom uses different key combinations for certain shortcuts in different languages, probably because the keyboard layouts make it hard for the user.

So I have two problems to solve--why the keys that are the same aren't working, and, what to do about shortcuts that vary according to language. For example, rotate left/right is ctrl [ and ctrl ] on USA keyboards.

**Comment by AlePhoto** [comment]
this sounds complicated... if you want I may try changing lenguage in LR or keyboard... at your disposal ;)

**Comment by rsjaffe** [comment]
Still working on major changes to key handling. Hopefully this will be fixed soon.

**Comment by rsjaffe** [comment]
Try the latest release. It should have fixed the issue: https://github.com/rsjaffe/MIDI2LR/releases

**Comment by rsjaffe** [comment]
See #232
