### ISSUE TITLE
Sending keystrokes: problems and proposed solution

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#213]
Well, sending keystrokes has a number of problems.

1. Different language keyboards use different shortcuts. This is how Adobe set it up.
1. Shortcuts have different effects depending upon what you're currently doing. Again, an Adobe feature. This creates some confusion with the labels I've attached to the shortcuts, as some people expect those labels to be the actions all the time.
1. OS X still not well-tested.

I'm thinking about ripping out the current system and going to a system where you would assign keystrokes to an action, sort of how we assign develop presets. This would take care of the multi-language issue.

It does mean I'm going to have to set up some more user interface elements to capture the keystrokes desired. I'm not happy with the Juce method of setting up interfaces, so I'll probably do it in the plugin, putting it in the Options menu where all the other choices are.

Comments? Help?

**Comment by AlePhoto** [comment]
I'm sorry but I have not any good suggestion about that... I'm wondering if set the language and the keyboard layout should fix this, I'have tried to doing so, but it seems not working even changing the LR language to English and the layout keybord to English...

**Comment by StevenKersting** [comment]
I think avoiding the multi language issue makes sense from a coding standpoint. And I don't really see it being an issue because we aren't "actually" using keyboard shortcuts (there's no "habit/knowledge" conflict).

I'd be glad to help if I can, but coding is definitely not my strong suit.

**Comment by rsjaffe** [comment]
Working on user-selectable keystrokes. #31
