### ISSUE TITLE
Not loading settings on opening

### ISSUE THREAD

**Issue by wockawocka** [rsjaffe/MIDI2LR#214]
Expected behavior

To load settings on start

Actual behavior

Doesn't. I have to load the xml file each time.

Steps to reproduce the behavior

Always happened from all versions

System information

Win7

* Operating system (Windows or OS X) and version:
* MIDI2LR version: 9.9
* Lightroom version: 2015.4
* Lightroom language: English
* Keyboard language: UK
* MIDI controller: BCF2000

Additional comments

It's been a problem since V4, I start lightroom, MIDI2LR starts but the settings aren't there until I load the xml file manually. It's a minor irritation.

**Comment by rsjaffe** [comment]
What directory is your plugin in. What directory are your profiles in.

**Comment by StevenKersting** [comment]
Have you told it where the profile is stored? (defined it in the settings)
