### ISSUE TITLE
Button needs to be pressed twice before it takes effect

### ISSUE THREAD

**Issue by loybuckz** [rsjaffe/MIDI2LR#215]
### System information

* Operating system (Windows or OS X) and version: Windows 7 x64
* MIDI2LR version: 0.9.9
* Lightroom version: 6.4
* Lightroom language:English
* Keyboard language: English
* MIDI controller: Behringer X-touch Mini

I noticed that when I press the buttons it sends either 0 or 127 as value and the action takes effect only when the button sends 127. Is there a way to make the buttons send only 127?

**Comment by AlePhoto** [comment]
it is a midi device configuration problem, you should use the behringer editor and set all buttons on "toggle off"

**Comment by loybuckz** [comment]
Thank you very much! I have installed the program and made the changes. Now everything works as I want them to.
