### ISSUE TITLE
software doesn't run

### ISSUE THREAD

**Issue by photoloco** [rsjaffe/MIDI2LR#216]
### Expected behavior
to work
### Actual behavior
doesn't seem to work
### Steps to reproduce the behavior
?
### System information

* Operating system (Windows or OS X) and version: OS X El Capitan
* MIDI2LR version:  latest?
* Lightroom version: CC latest update
* Lightroom language: english
* Keyboard language: qwerty international
* MIDI controller: novation launch control

### Additional comments

i'm probably making some kind of rookie mistake, but i can't get midi2lr to run in lightroom at all. 
I've downloaded the files. copied them into a folder om my mac. Found the MIDI2LR.lrplugin in source>LRPlugin>Controller_settings 
and then added the plugin in lightroom in the plugin manager.
But now i can't find the window where i can assign tasks to the knobs on my Midi controller. I thought it would pop up when i turn a knob. But it doesn't. And i've also tried to select 'Start Server' in the Plugin extra's. but nothing happens. 
If i quit lightroom it does say that the plugin is performing shut down tasks. So i guess it runs?

I've checked the Midi controller by the way. And it works fine. Am i missing some impotent step by any chance?

Thanks in advance

**Comment by StevenKersting** [comment]
Check the task bar to see if it's running minimized...

**Comment by photoloco** [comment]
I just checked, but it isn't

**Comment by StevenKersting** [comment]
I think maybe you have downloaded the source code and not the compiled app. You need to download/install the MIDI2LR.zip file here: https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.9

**Comment by photoloco** [comment]
You're right. That was it. it's running now. thanks a lot!
