### ISSUE TITLE
White Balance Selector Tool

### ISSUE THREAD

**Issue by stevejmu** [rsjaffe/MIDI2LR#217]
Can the White Balance Selector Tool be mapped to a button on a MIDI controller? I didn't see it anywhere in the documentation or as an option in the list of Lightroom Commands when setting up buttons/knobs/sliders. The keyboard shortcut is 'W' to open the tool, but it would be great if I could assign that to a button rather than reaching for the keyboard or moving the mouse over to open the tool.

**Comment by rsjaffe** [comment]
If you start moving the control, it will reveal automatically. 

I am working on providing custom keyboard shortcuts, which should take care of this issue as well as many others.

**Comment by stevejmu** [comment]
I know that the sliders appear when the tool starts being adjusted, but I want the eyedropper tool to become active when I press a button, then I can use my mouse to click a neutral area to select the white balance.

![wb-tool](https://cloud.githubusercontent.com/assets/14840553/14066921/9e7a2804-f425-11e5-8024-6f7d0081e186.JPG)

**Comment by DavidWeaverPhoto** [comment]
While in the develop module the 'w' key is a bottom to press to make the eyedropper tool active.
I feel sorry for Parth here as I see a fair number of requests to buttonize some command that already exists in LR  :-|

**Comment by stevejmu** [comment]
The purpose of MIDI2LR is to increase productivity in a Lightroom workflow. Time can be saved by moving more commands away from the keyboard and onto a MIDI controller. How much time is saved in a normal workflow? If it takes only 1 second to change to the WB tool by using the keyboard 'W' shortcut, then in a workflow with 400 - 600 images (or more), then that's anywhere from 6 to 10 minutes saved just by moving it down to a button on the controller... and that's just for one tool (assuming that tool is used on every photo).

Similar keystrokes have already been programmed for things like activating the Spot Remover tool (keyboard shortcut 'Q') and the Brush Tool (keyboard shortcut 'K'), so this isn't asking too much. The same goes for other keyboard shortcuts, especially ones that require multiple keystrokes.

**Comment by rsjaffe** [comment]
Once we have custom shortcuts, you will be able to customize to your heart's content. I'm having trouble with the custom shortcuts right now, need to debug--once they're working, I'll release it. See #31

**Comment by DavidWeaverPhoto** [comment]
Whiny MoFo and not realistic.  It takes 1/5th to 1/10th of a second for me to move from controller to keyboard.  You are not doing a custom WB on every image .  Even out of 600 images you must be selecting maybe 50% (I do about 10%).  So of those 300 image you are not white balancing every freaking image unless you know nothing abouit workflow...whichj in your case is possible..  You do one imageand then copy the setting and past that into a new image (yes programmable in MIDI2LR).
Go take a LR course.   Sheesh....Whiny fucker.

**Comment by stevejmu** [comment]
That's a helpful tone.

**Comment by bozwellox** [comment]
Wow.
