### ISSUE TITLE
Problem with detecting of MIDI Controller TRAKTOR  Kontrol Z1

### ISSUE THREAD

**Issue by webmanov** [rsjaffe/MIDI2LR#219]
**Expected behavior:** work fine

**Actual behavior:** Plugin installation was OK. But when try to close the Lightroom, OS popup a error message: 
### midi2lr has stopped working:
----------------------------------------------------------------------------------------

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	MIDI2LR.exe
  Application Version:	0.9.9.0
  Application Timestamp:	56d0d147
  Fault Module Name:	MIDI2LR.exe
  Fault Module Version:	0.9.9.0
  Fault Module Timestamp:	56d0d147
  Exception Code:	40000015
  Exception Offset:	0009fbb0
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1026
  Additional Information 1:	7c9f
  Additional Information 2:	7c9fa5b4fd099aeadbd7c2980d130cda
  Additional Information 3:	a15e
  Additional Information 4:	a15e8eb75a70b51d50ea98837709ca27
-----------------------------------------------
and it become OK, when restart the Lightroom, or restart the plugin, from Lr plugin menu. 
2. Couldnt found the MIDI devices,click so many times, at the button , but no reaction !

1. Install the MIDI2LR /add in Lr plugin menu, path to the folder/
2. The Plugin menu, popup
3. Try to close it, win popup an error
4. Restart the plugin
5. Connect the midi controller and install its drivers for the OS.
6. Try to scan for the midi device, with plugin : no result.

### System information

* Operating system (Windows or OS X) and version: Windows 7
* MIDI2LR version: Version 0.9.9
* Lightroom version: 2015/CC
* Lightroom language:ENG
* Keyboard language:ENG
* MIDI controller:Traktor Kontrol Z1

Additional comments: May be must try with other midi controller ?

**Comment by rsjaffe** [comment]
Which directory did you use for the plugin?

**Comment by webmanov** [comment]
D:\midi2lr
I browse it in plugin interface of Lr, as Readme install file

**Comment by webmanov** [comment]
Also, try to move it in root folder of Lr/ the plugin menu automatically detect it and start it/
NO, results of that action . Again > No, MIDI , click at rescan for new midi devices, nothing.

**Comment by rsjaffe** [comment]
Have you checked to see whether any other midi software can detect your controller? I wonder if the drivers are correct or the cable isn't plugged in. Don't laugh--while debugging one apparent issue I found out that I forgot to plug back in my controller--plugging it in fixed the problem!

**Comment by webmanov** [comment]
After a midnight research, guess what? This device isnt a midi !!! Traktor kontrol z1 is a mixer with sound card, no midi ... 
My general mistake 'cause i hadnt patient to test midi2lr. Must to find real midi device. Excuse me mr officer:)
