### ISSUE TITLE
Lightroom Presets

### ISSUE THREAD

**Issue by stevejmu** [rsjaffe/MIDI2LR#22]
Would be nice to assign presets to buttons and provide a drop down menu of available presets to assign with that button. Have a look at the LrDevelopPresetFolder & LrDevelopPreset classes available in the Lightroom 6.0 SDK (descriptions below).

# LrDevelopPresetFolder (Class)
This class provides access to a develop-preset folder, and to the LrDevelopPreset objects for the contained presets. 

Access the functions and properties from the object. Retrieve the objects for all the folders by calling LrApplication.getDevelopPresetFolders().

##### - folder:getDevelopPresets()
Retrieves the develop-preset children of this folder.

##### - folder:getName()
Retrieves the name of this folder.

##### - folder:getPath()
Retrieves the path of this folder.

##### - folder:type()
Reports the type of this object.

# LrDevelopPreset (Class)
This class provides access to a develop preset, which stores persistent develop settings.

Access the functions and properties from the object. Retrieve the objects for all the presets at the root of the hierarchy by calling LrApplication.developPresetFolders().

Retrieve objects from the parent folder using LrDevelopPresetFolder.getDevelopPresets().

##### - preset:getFile() 
Retrieves the file path of this preset.

##### - preset:getName()
Retrieves the name of this preset.

##### - preset:getParent()
Retrieves the parent folder of this preset.

##### - preset:getSetting()
Retrieves the settings for this preset.

##### - preset:getUuid()
Retrieves the unique identifier of this preset.

##### - preset:type()
Reports the type of this object.

**Comment by rsjaffe** [comment]
Good idea. I'll put it in the queue.

**Comment by rsjaffe** [comment]
See #31
