### ISSUE TITLE
Request: Local Adjustment preset

### ISSUE THREAD

**Issue by AlePhoto** [rsjaffe/MIDI2LR#220]
Hi rsjaffe, 
Wuold you consider the possibility of adding Local Adjusting preset? I think those are usefull staff. thanks

**Comment by rsjaffe** [comment]
Could you explain what you mean by a local adjustment preset? Are you talking about a preset for the adjustment values or a preset for the adjustment positioning?

**Comment by AlePhoto** [comment]
Once you active a brush or a gradient or a radial, below "new", "effect: "PresetName". in this drop down menu you can recall settings for brushes, gradiant and radial. I am talking about the possibility to set a button via midi to recall this presets, in the same way as DeveopPreset work at the moment. 
I find myself to always go for my 3 or 4 best preset and I need to open and search for them through this drop down menu. I think this would be handy.

**Comment by bozwellox** [comment]
I agree this would be a useful feature - being able to hit a button and have a dodge brush, burn brush etc would remove the need to click onto the local adjustment brush and choose a preset or adjust the sliders.

**Comment by C0d3Rush** [comment]
if achievable this would be very very useful!

**Comment by rsjaffe** [comment]
There are controls for the sliders (see the local adjustments section of the commands list), but I don't see how to control the local adjustments presets.

**Comment by wetfirer** [comment]
They omitted probably the most important detail about this RQ: **"Custom"** presets. You can create and save your own presets e.g.: 
**Eye wrinkle** remover: _Lessen the **Shadow**, removing **Clarity** and **Saturation**_

Making your own custom Local Adjustment preset is the key to fast image processing ;-)

Additionally any chance of adding a possibility for _sliders_ for Brush 
**Size**, 
**Feather**, 
**Flow**, 
**Density** 

and that _button_ "**Auto Mask**"?

How would it be more convenient for you? Should I make a new separated RQ for that one?
