### ISSUE TITLE
Feature request: targeted adjustments via button push

### ISSUE THREAD

**Issue by bozwellox** [rsjaffe/MIDI2LR#222]
Would it be possible to add this feature? In Paddy I had the targeted adjustment function mapped to a push/click of whichever rotary controller was mapped to the relevant Lightroom slider, e.g:

Curves (one for each rotary controller, i.e. shadows, darks, lights, highlights)
Saturation
Vibrance

Also, as someone else has already requested, I had the white balance dropper assigned to a click of the rotary controller that was assigned to the temperature slider.

### System information

* Mac OSX 10.11.3
* MIDI2LR version: 0.9.9
* Lightroom version: CC 2015.5
* Lightroom language: English
* Keyboard language: English
* MIDI controller: Behringer BCF2000 & X-Touch Mini
* Plugin installation directory: Within Lightroom folder
* Profiles save directory: Within Documents folder

**Comment by bozwellox** [comment]
Just to clarify - I've perhaps made this sound more complicated than it is. I had four rotary controllers assigned to each curve adjustment point, and I assigned the "click/push" midi CC of the first of the four rotary controllers to the targeted adjustment tool for the curve. So, I'd click the relevant button, then click onto an area of the image and drag up or down to adjust the curve, relative to the tonal value of the pixels I'd clicked on.

**Comment by rsjaffe** [comment]
I'm going to open up the keystrokes shortcuts. That will allow you to activate the targeted adjustment tool with a button.

**Comment by rsjaffe** [comment]
See #31
