### ISSUE TITLE
Feature request: finer control over straighten angle

### ISSUE THREAD

**Issue by bozwellox** [rsjaffe/MIDI2LR#224]
I have the straighten angle (within the crop tool) assigned to a controller but it is very sensitive - too sensitive for fine adjustments. Would it be possible to adjust the sensitivity somehow, or the range of the adjustment?

Mac OSX 10.11.3
MIDI2LR version: 0.9.9
Lightroom version: CC 2015.5
Lightroom language: English
Keyboard language: English
MIDI controller: Behringer BCF2000 & X-Touch Mini
Plugin installation directory: Within Lightroom folder
Profiles save directory: Within Documents folder

**Comment by rsjaffe** [comment]
You can already do that. See https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#customizing-the-limits-dialog on how to add straighten angle to the Limits Dialog.

**Comment by bozwellox** [comment]
Thanks, that sounds great. However, the wiki mentions:

"open up Limits.lua from the plugin directory".

Where would I find this on a Mac? I can't find a Limits.lua file anywhere, even when searching the entire hard drive.

**Comment by bozwellox** [comment]
Weird, I couldn't see anything other than what looks like a Midi2LR.lrplugin file on my Mac. It's not displaying as a folder. If I click on it in Finder it shows no subfolders/files)  if I double click on it, it just opens the Lightroom import screen?

However I've just downloaded the same Midi2LR.zip file on my PC and I clearly see the Midi2LR.lrplugin folder, contatining all the .lua files.

So it seems to be an issue with how the folder is displaying on my Mac. I'll try again later when I'm back in front of my Mac, but if anyone has any ideas that would be appreciated! I searched the entire Mac hard drive for anything containing "limits" or "lua" and it didn't display anything. It's as if they are hidden files.

**Comment by Polekso** [comment]
Hello no there is no issues, on a mac to open it you have to do a ctrl+clic and open it as Package Contents this way you'll see all the files.
Have a nice day

**Comment by bozwellox** [comment]
@Polekso Thanks - I'm new to this weird Mac way of thinking!

**Comment by Polekso** [comment]
I agree that's weird

**Comment by rsjaffe** [comment]
I'll update the instructions. I'm not a Mac user so I have no weirdness experience. :smile:

**Comment by bozwellox** [comment]
A quick update: I followed the instructions from @Polekso and all good - the straighten tool is now super accurate. Thanks!
