### ISSUE TITLE
Midi2LR.exe not in MIDI2LR.zip 0.99

### ISSUE THREAD

**Issue by MarkWestbroek** [rsjaffe/MIDI2LR#225]
### Issue
Midi2LR.exe not in MIDI2LR.zip 0.99
It gives an internal error API error 2, as in https://github.com/rsjaffe/MIDI2LR/issues/92

### Versions
* Operating system (Windows or OS X) and version: Windows 8.1
* MIDI2LR version: 0.99
* Lightroom version: CC

### Additional comments
0.98 seems to work. Do I need to extract 0.99 over 0.98 as a kind of upgrade?

**Comment by rsjaffe** [comment]
Please download the zip file again. I just looked, and it does have the exe file.
