### ISSUE TITLE
New release issues

### ISSUE THREAD

**Issue by AlePhoto** [rsjaffe/MIDI2LR#228]
* Operating system WIN 7
* MIDI2LR version: 0.9.10
* Lightroom version: CC
* Lightroom language: italian
* Keyboard language: italian
* MIDI controller: BCF 2000
* Plugin installation directory: desktop
* Profiles save directory: document

Hi, with a lot of sadness I have to say the new KeyboardShortcut feature didn't worked in my case. I think I done everything right but anyway let's wait for other users experience. the new autosync has worked instead. I point out the main window of Midi2Lr keeps saying I am on versione 0.9.9 but I think it is just a little bug.

**Comment by rsjaffe** [comment]
I think you have an installation issue. I just checked the installation package. The application reads `0.9.10` as does the plugin.

You should see the following for the Options dialog in the plugin:

![Options Dialog](https://raw.githubusercontent.com/rsjaffe/MIDI2LR/gh-pages/images/DialogOther.png)

And you should see this when assigning a shortcut to a MIDI button--note that `Keyboard Shortcuts for User` is near the top:

![List of Shortcut types](https://cloud.githubusercontent.com/assets/1431301/14227354/46f1427c-f8b0-11e5-821e-e0fa6a3932a5.png)

**Comment by AlePhoto** [comment]
Hi, let me clarify: I see the new fields in option menù, and I also see the new "keyboard shortcuts for user" ... As I said, I think I done everythink properly, for example, I set the letter "w" for target WB in the 1key... and mapped the button on my BFC2000 ... and it didn't worked. same with combination ctrl+alt+v for pastfromprevious. any suggestion? I also tryed removing the plugin from LR and installing again. thanks

**Comment by EugeneMichel** [comment]
Im having the same issue. Plugin manager says version 9.10, but MIDI2LR still shows 9.9. I also see all the dialogs above for shortcut keys, but its not working for me when I put in the shortcuts. I set my shortcuts but it does not do the effect of those keys; for me it opens up the secondary monitor (F11) with a few shortcuts I tried (copy, paste, reset) Auto tone shortcut starts the slideshow for me.

**Comment by EugeneMichel** [comment]
Also want to mention that when first Copy and Paste settings were introduced, I had similar issue as Keyboard shortcuts now, where the boxes that I marked in CopySettings would not paste but would apply another effect (another keyboard random shortcut would apply). This has been fixed a few releases down and Copy and Paste works perfectly for me now. Maybe the Keyboard Shortcuts have a similar issue that Copy and Paste had at first.

**Comment by rsjaffe** [comment]
This sounds like part of the old app is still running.

Make sure you exit Lightroom and restart it. This is a known issue with LR--it hangs on to part of the old app when you install a new one, even if you press 'reload' -- see https://github.com/rsjaffe/MIDI2LR/wiki#updating-from-a-previous-version.

**Comment by EugeneMichel** [comment]
Yes, Ive deleted the old folder, restarted Win 10, and then installed the new plugin with the Plugin Manager. I dont think its the old app because I see all the new features of 9.10.

**Comment by rsjaffe** [comment]
Ouch! Somehow the wrong build of the app got put into the zip file. I'm fixing that right now. New version should be up in a minute!

**Comment by rsjaffe** [comment]
Sorry it took so long to fix this simple issue--I had changed my build directories and the app ended up in the wrong place, so I picked up the old one when packaging for release.

**Comment by rsjaffe** [comment]
Fixed key issue in hotfix, I hope. See https://github.com/rsjaffe/MIDI2LR/releases/tag/%60v0.9.10.1
