### ISSUE TITLE
The problem with temperature control BCF2000

### ISSUE THREAD

**Issue by tryba2000** [rsjaffe/MIDI2LR#229]
Hello. I have a problem with temperature control. When I move the slider to temperature changes from 3000 to 9000. How to increase the range of 2000 to 50000.
System information

* Operating system Windows 10
* MIDI2LR version: 0.9.9
* Lightroom version: 6.0
* Lightroom language: PL
* Keyboard language: PL
* MIDI controller: Behringer BCF2000
* Plugin installation directory: E:\Programy\programy foto\MIDI2LR
* Profiles save directory: E:\Programy\programy foto\MIDI2LR\AlexArtPhoto_BehringerBCF2000_MIDI2LR

**Comment by AlePhoto** [comment]
READ THE GUIDE: ... 
https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#limits
