### ISSUE TITLE
Modify X with + - (plus and minus) keys

### ISSUE THREAD

**Issue by alexsheppard11** [rsjaffe/MIDI2LR#23]
Lightroom supports using the plus and minus keys for incrementing / decrementing an adjustment.
It would be useful to map these to buttons.

It looks like LrDevelopController.increment() and LrDevelopController.decrement() allow this.

**Comment by rsjaffe** [comment]
Simple enough. It's done and will be out with the next release.

**Comment by shaunchu** [comment]
hey guys,
do you mind pointing me to where the settings is located in the plugin?
thanks

**Comment by rsjaffe** [comment]
see Increase Last Modified and Decrease Last Modified https://github.com/rsjaffe/MIDI2LR/wiki/Commands#9

**Comment by shaunchu** [comment]
thanks @rsjaffe 
so am I correct to say there's no way to simply click on an attribute name and turn a rotary encoder to change the values? instead we have to actually change a value and then turn the rotary encoder.

**Comment by rsjaffe** [comment]
No, that's wrong. Look carefully at the list in the **Develop** section of commands. What you're looking for if you've selected a particular adjustment and want to use a rotary encoder is _More – Less_. That works on the currently selected adjustment. _More – Less Last Modified_ works on the last modified adjustment. Lightroom has a complex interface and MIDI2LR captures most of that, but that means you have to go through the list of commands to find the one that best fits your needs.

**Comment by shaunchu** [comment]
ya that's what I thought and tested first, but More - Less actually changes to the next - previous photo on the photo strip on my mac, as noted on your wiki commands it's a cursor left / right, which changes photos. that's why I thought I got it wrong.

**Comment by rsjaffe** [comment]
Please post further discussion at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . The Github issues page is for development planning only.
