### ISSUE TITLE
If your app said 0.9.9 even though you downloaded version 0.9.10

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#231]
The wrong app was packaged with the zip file. Please redownload.

This should only affect Windows users who downloaded the app prior to 19:00 UTC on April 2, 2016.

https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.10

**Comment by AlePhoto** [comment]
this release has fixed the but about the app version as you said... but doesn't fix the issue about keyboard shortcuts :(

**Comment by rsjaffe** [comment]
I'm encountering a bug in the application framework I use. I'll work on that later this weekend.

**Comment by rsjaffe** [comment]
Fixed in hotifx.
