### ISSUE TITLE
Hotfix for latest release

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#233]
Turns out that the Juce framework is adding a 'shift' to letter keys. I've put in a fix for that, so custom keys should work better. See https://github.com/rsjaffe/MIDI2LR/releases/tag/%60v0.9.10.1 for the hotfix for all who downloaded version 0.9.10.

**Comment by tryba2000** [comment]
This program is amazing. A good job. Now it works perfectly.

**Comment by stevejmu** [comment]
I agree, it's working great now!  Can't wait to see what else is in store!

**Comment by rsjaffe** [comment]
Next--get rid of the pre-defined keypresses--those are confusing, and now we have programmable keys, unnecessary.

After that:

1. Use as little of the Juce library as necessary--the struggles with the keys and the Juce bug just made me more determined to do so.
2. Try getting NRPN messages working. This will make control much more sensitive for those controllers that support it.
3. Maybe some mouse control, for moving crop, white balance dropper, etc.

**Comment by stevejmu** [comment]
> Next--get rid of the pre-defined keypresses--those are confusing, and now we have programmable keys, unnecessary.

What do you mean by pre-defined keypresses?

**Comment by rsjaffe** [comment]
For example, look at https://github.com/rsjaffe/MIDI2LR/wiki/Commands under "General"--*Import Photos and Videos* is control-shift-i, but people can now set that up with the custom keys. All the commands with predefined keystrokes--there's serious cross-language issues.

**Comment by stevejmu** [comment]
That's what I thought, just wanted to make sure. I think it's nice having the pre-defined keypresses spelled out are nice so that the user knows what's mapped to which button, but if there are too many issues on the backend then it's probably best to un-code them.  I think the Next / Previous Photo and Add to Left / Right Selection options should stay in there. I didn't see a way to map the arrow keys in the Keyboard Shortcut editor.

**Comment by rsjaffe** [comment]
I forgot to put instructions for the arrow keys.

they are:
cursor left
cursor right
cursor up
cursor down

**Comment by stevejmu** [comment]
I tried those when I saw the popup suggestion, but they didn't work so I figured they weren't the arrow keys.

**Comment by AlePhoto** [comment]
Nice done rsjaffe... It seems ok now.. even the old pastFromPreviuos command works now :) I'm testing it and I'll let you know... thanks, great job!
