### ISSUE TITLE
Buttons need 2 clicks in my controller, to do the action

### ISSUE THREAD

**Issue by senepro** [rsjaffe/MIDI2LR#236]
Hi Guys!

I'm very new to the MIDI2LR, but I love it from the first time :-) Everything works fine, but if I set an action to a button in my BCR2000 unit, I must click 2 times the button, to do the action.

I figured, that in the mapping window there's a different code for the ON state (CC107 [127]) and the OFF state (CC107 [0]). Could you help me please, how can I set the plugin, to do the action in the OFF and the ON state, so I don't need to click two times for the function.

Is it available from the plugin settings, or I can edit the settings container XML file in a specific way?

Thank you very much,
John

**Comment by rsjaffe** [comment]
You need to set the buttons in the BCR2000 to toggle off. That way, it sends a 127 when pressed and a 0 when released. The application is set up that way, as the lights on the buttons won't make sense otherwise. You can either program the buttons directly (see your BCR2000 documentation) or use [bcmanager](http://mountainutilities.eu/bcmanager) to do it.

**Comment by senepro** [comment]
Thank you very much rsjaffe, it worked for me.

**Comment by senepro** [comment]
Hi Guys!

I would like to share with the community the way of toggling OFF any button especially in the Behringer BCR-2000, if somebody has the same problem:

1, Press and HOLD the Edit button, while
2, Press the button, you want to set to toggle OFF
3, Release the Edit button
4, Turn left the Mode potmeter in the unit (Top row, 3rd pot from the right), while the LCD show ToFF
5, Hit the Edit button
6, Thats it :-)
7, Repeat this with every button, you want to toggle OFF

Regards,
John

**Comment by rsjaffe** [comment]
Thanks for the instructions. I'll put them in the wiki.
