### ISSUE TITLE
Temperature value 

### ISSUE THREAD

**Issue by thorodt** [rsjaffe/MIDI2LR#239]
### Expected behavior
Temperature value is working only for raw files, not for JPG
the TINT value is working for both formats

### Actual behavior
the Temperature value for jpg is not working

### Steps to reproduce the behavior
try to change Temperature in Lightroom 6 for a JPG

### System information

* Operating system (Windows or OS X) and version:  OS 10,9,2
* MIDI2LR version: 0.9.9
* Lightroom version: 6,0
* Lightroom language: italian
* Keyboard language: italian
* MIDI controller: xtouch mini behringer
* Plugin installation directory: /user/desktop/MIDI2LR/
* Profiles save directory: /LIGHTROOM/

**Comment by rsjaffe** [comment]
Could you open a jpg in Develop module, then look at the plugin options menu: other options, and check the temperature limits?

**Comment by thorodt** [comment]
for JPG the temperature range is from -100 to + 100
for raw  2000 - 50000

**Comment by rsjaffe** [comment]
Odd. I can't reproduce the error. I've flagged this to see if anyone else is having the same issue.

**Comment by alexsheppard11** [comment]
I can reproduce with 0.9.10.1 and LR 6.5.

**Comment by Slelmo** [comment]
I can confirm this with TIFs. One of those that PS (CS6) sends back to LR. 
Haven't touched a JPG in a while so can't tell.

Lightroom version: 6.5 [ 1067055 ]
MIDI2LR version 1.0.0.1

**Comment by rsjaffe** [comment]
See #255. Will be fixed (I hope) in next release.

**Comment by thorodt** [comment]
thanks a lot :)
