### ISSUE TITLE
BCF2000 question - reprogram STORE, LEARN, EDIT and EXIT buttons?

### ISSUE THREAD

**Issue by bozwellox** [rsjaffe/MIDI2LR#241]
I'm sure this is possible as a previous setup I had for Paddy on the PC made these buttons available for assigning to LR functions via midi CCs. Now I've reset back to the default BCF2000 setup via a sysex dump to use it with Midi2LR, those buttons are no longer assignable.

Does anyone have any idea how to do this please?

**Comment by rsjaffe** [comment]
There's an example in the MIDI2LR.zip under controller settings. You can find it here on github at https://github.com/rsjaffe/MIDI2LR/tree/master/Source/LRPlugin/Controller_Settings/BCF2000%20RSJ%20OneProfile. The text file has directions. I'm sure you can also do that directly on the controller, but I don't have access to the instructions right now--Boeringer should have it.

**Comment by bozwellox** [comment]
Ace! I'll give it a go. And probably break it massively.

Cheers.

**Comment by rsjaffe** [comment]
Well, did it burst into flames or no? :fire:

**Comment by bozwellox** [comment]
Just tried it. No actual fire but it didn't go so well. I get an error when trying to load the Preset2.bcf file into BCManager. Can't copy and paste the text, but here's a screenshot showing the kind of things it's complaining about:

<img width="1376" alt="screen shot 2016-04-17 at 16 54 41" src="https://cloud.githubusercontent.com/assets/16922715/14588284/4416236a-04bd-11e6-891a-9df74f43b9b1.png">

**Comment by rsjaffe** [comment]
Ewww. Better to just program it in BCManager yourself. It gives you the option of changing dedicated keys into pushbuttons.

**Comment by bozwellox** [comment]
Sorted it - I'd tried to copy the text from the page you linked to but obviously ballsed it up. Checked the latest download and found the file in there. Now working like a charm!

Another one bites the dust. Cheers!
