### ISSUE TITLE
cancel doesn't work properly in dialog box

### ISSUE THREAD

**Issue by AlePhoto** [rsjaffe/MIDI2LR#242]
Hi, I'd like to report this issue: when I push copy-settings, than move to another picture in order to paste same settings, than and push paste via the dialog box, the settings marked will apply even if I push "cancel" insted of "ok"
sorry about my English!

* Operating system win7* MIDI2LR version:
* Lightroom version: 6
* Lightroom language: ita
* Keyboard language: ita
* MIDI controller: bcf2000
* Plugin installation directory: desktop
* Profiles save directory: documents

**Comment by rsjaffe** [comment]
there are several paste settings commands. which are you using?

**Comment by AlePhoto** [comment]
develop -> copysetting

("Copies all develop settings. Application will remember last copy operation and use that for all paste operations until a new Copy Settings is done or the application is restarted. button ")

**Comment by AlePhoto** [comment]
--> Paste Selected Settings :  ("Pastes only those settings checked in the Options—Paste Selections dialog. button") ... if you push cancel in the dialog box the plug-in applys the settings anyway

**Comment by rsjaffe** [comment]
Right--cancel only cancel's the changes you make in the dialog box. It doesn't cancel the paste.
