### ISSUE TITLE
"Version 0.0.0 available." Version update notification doesn't handle full version numbers well.

### ISSUE THREAD

**Issue by DavidWeaverPhoto** [rsjaffe/MIDI2LR#244]
Hahahahahahaha!    Completely made my day.  Just opened LR and got a message that version 0.0.0 is available.
:-)

**Comment by rsjaffe** [comment]
Yes, that bug will be fixed—but not until 1.0.1, so you'll be seeingit
again. It was in some legacy code.

On Saturday, April 16, 2016, DavidWeaverPhoto <notifications@github.com>
wrote:

> Hahahahahahaha! Completely made my day. Just opened LR and got a message
> that version 0.0.0 is available.
> :-)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rsjaffe/MIDI2LR/issues/244>
>


-- 
Sent from Gmail Mobile, all typos are Siri’s fault.
