### ISSUE TITLE
Feature Request: Less meticulous upgrade process

### ISSUE THREAD

**Issue by rubin110** [rsjaffe/MIDI2LR#245]
Wishing out loud, it would be great if upgrading to a new version (on Windows at least), didn't involve so many steps. I've avoided a number of updates simply because I didn't want to waste time...

1. Downloading an update
2. Going to the Lightroom plugin manager
3. Removing midi2lr
4. Opening up the file explorer
5. Remember where I install my plugins
6. Open the downloaded zip
7. Overwrite the plugins folder
8. Add a new plugin to Lightroom
9. Refind the plugin directory
10. Go back to editing photos

If there was a script I could run to automate this that would be awesome. Or even something similar to how Jeffrey Friedl's Lightroom plugins self update.

Thanks!

**Comment by alexsheppard11** [comment]
I simply close lightroom and overwrite the MIDI2LR plugin folder with the new version.
I don't bother removing it from the LR plugin manager and re-adding.

**Comment by PhantomLordM** [comment]
I agree with rubin110. What's more I need to change Limits.lua every time I update as well as setting limits within Options dialogue in LR.

**Comment by rsjaffe** [comment]
@PhantomLordM  what do you need to change in Limits.lua?

**Comment by rsjaffe** [comment]
Further discussion should be on https://groups.google.com/forum/#!forum/midi2lr . Github issues is being closed down in favor of the google forum.
