### ISSUE TITLE
Version 1.0.0.1 released (mainly for OS X users)

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#246]
This release attempts to fix a Lightroom bug in OS X, where the command key is ignored. I've added short pauses (30 ms) between keystrokes to see if that fixes it. Please provide feedback.

Also fixes version display bug in version checker dialog box.

**Comment by bozwellox** [comment]
Great news. I'll give this a test later on and report back.

**Comment by bozwellox** [comment]
@rsjaffe Still not working for me I'm afraid, although the version number shown on the plugin when it's running is still 1.0.0.0, whereas plugin manager in Lightroom shows it as being 1.0.0.1.

I disabled and removed Midi2LR from plugin manager within Lightroom, then deleted the MIDI2LR.lrplugin file Controller_Settings folder and ReadMe.txt file, so as far as I'm aware I'd removed all trace of any previous versions.

Any ideas?

**Comment by rsjaffe** [comment]
Let me check the distribution. The app should say 1.0.0.1 if it were
updated--I may have placed the wrong copy in with the zip file.

**Comment by bozwellox** [comment]
I hope so - I'm working through a wedding edit and I've developed an acute case of what I've dubbed "Option + CMD + V claw"! Please put me out of my misery.

**Comment by emkorec** [comment]
Yes, same here:
![screen shot 2016-04-20 at 15 58 58](https://cloud.githubusercontent.com/assets/17280850/14677195/dc0c8f2e-0710-11e6-8d56-b51b0c9ec64e.png)

**Comment by laklare** [comment]
There's a minor bug in version number for the update notification. The notification I received from the plugin in Lightroom for Windows was "New version 0.0.0 available"

**Comment by rsjaffe** [comment]
(@laklare see #244 .)

The new OS X app should read 1.0.0.1. I've recompiled and uploaded it. I'm also attaching the plugin here. While I don't have Lightroom for OS X I did run the app and it read 1.0.0.1. So if you install the plugin below it should read 1.0.0.1 and have the changes as described. I'll respond to feedback on this after I get back in about 18 days.

[MIDI2LR.zip](https://github.com/rsjaffe/MIDI2LR/files/229194/MIDI2LR.zip)

**Comment by emkorec** [comment]
Unfortunately still does not work.
1. MIDI2LR window still shows 1.0.0.0 no matter which plugin I install (downloaded from here or downloaded from the Releases site)
2. Something might be completely wrong because now not only Cmd does not work but Shift does not eighter.

Actually I've found another plugin that overrides Lightroom shortcuts. Possibilities are limitless ;) ...at least until MIDI2LR handles osx keyboard shortcuts well.

**Comment by emkorec** [comment]
Weird.... no keystroke or keyboard shortcut works for me that I set in Options windows. I installed 1.0 version from 10th April where everything worked except Cmd key and still nothing. If I do not set a modifier key just a keystroke (eg. "r" fro crop tool) - it does not work.

**Comment by EssendonPhoto** [comment]
@rsjaffe - thanks for developing such a useful tool!
However, I too am an OSX user with the same issues - key strokes do not work. (Clean install of 1.0.0.1 on latest versions of OSX and LR.)
I am also having the issue of inelegant program failure on close.

**Comment by EssendonPhoto** [comment]
Actually - I have a hint why keys do not work. If I restart and tick the "Show status and activity" box on the "Other" tab of MIDI2LR options in LR then the first time I hit a key bound to Key1 (mapped to "r" in my case) then I get the error dialog:
An internal error has occurred.
Failed to get CharCodes from EventRef (-9870)

**Comment by EssendonPhoto** [comment]
Oh - how odd.

Following more investigations I have found I have the following behaviour:
If I am in the Library module then hitting the "r" key on my keyboard takes me to Develop and puts me in crop mode (ie expected LR behaviour)
If I am in the Library module then hitting the midi button bound to Key1 which is mapped to "r" produces an error sound
If I am in the Develop module then hitting the midi button bound to Key1 which is mapped to "r" moves me to crop mode - as expected
