### ISSUE TITLE
A few slightly odd behaviours

### ISSUE THREAD

**Issue by sandyfsx** [rsjaffe/MIDI2LR#247]
### Expected behavior
The keyboard shortcut 'X' can be used for both 'reject photo' and within the crop module, switching between landscape and portrait. 

### Actual behavior
When a button is assigned to X it only functions as reject photo. Furthermore, it actually changes the function of the actual keyboard button to lose this function too. When the button on the midi controller is assigned back to reject photo, normal function returns.
### Steps to reproduce the behavior
Assign a button on the midi controller to X, open the crop dialogue, press button.

### Expected behavior
Enable Lens Corrections would tick the box labeled 'Enable profile corrections' under the lens corrections tab in Develop

### Actual behavior
It actually toggles the tab on or off. This isn't much use if you want to use it to turn lens corrections on or off as you have to manually turn it on first. I may be mistaken but I couldn't find an option that actually does turn lens profile corrections on and off.

### System information

* Operating system (Windows or OS X) and version: Windows 10
* MIDI2LR version: MIDI2LR 1.0.0
* Lightroom version: LR 2015.5
* Lightroom language: English
* Keyboard language: UK English
* MIDI controller: Behringer bcf 2000
* Plugin installation directory: E:\Documents\MIDI2LR\MIDI2LRV1.0.0
* Profiles save directory: E:\Documents\MIDI2LR

### Additional comments
The only key the send key option doesn't seem to support is return. This would be useful as it is used to accept pretty much all local adjustments, crops etc. I know you can press the button that activated your local adjustment again to deactivate it but hitting return is a catch all button rather than needing individual ones. I don't actually assign all the local adjustments to buttons as this would take up too many buttons.

**Comment by DMVpix** [comment]
Interesting as I just ran into this problem myself as a new user. 

I use X to switch the crop orientation and wanted to assign the shortcut to a key on the controller. As you stated, it rejects the photo when in the crop tool vice changing the orientation. Would be really nice if this worked.

**Comment by rsjaffe** [comment]
The return key is included in version 1.0.0.1, --try that and see if that helps.

I don't understand how the keyboard function would change--the shortcut keys are being sent by the MIDI2LR app, which doesn't do anything directly to lightroom--it just emulates a keypress. If you could get more information on the X key issue, it would help me. For example, close the app and see if the keyboard works. Open the app and check again, use the 'X' shortcut in the app then check the keyboard again. It's hard for me to debug this without being able to replicate it.

**Comment by DMVpix** [comment]
Hopefully this answers what you're asking.

With MIDI2LR running, while in crop mode 
1) pressing X on the keyboard changes the crop rotation (expected behavior),
2) send key X from the controller sets the reject flag (incorrect behavior) and advances to the next photo

Without MIDI2LR running, while in crop mode pressing X on the keyboard changes the crop rotation (correct behavior).

In Library, from either the keyboard or controller, X rejects the photo, which is the behavior expected.

The keyboard input works regardless of whether MIDI2LR is running.or not.

**Comment by rsjaffe** [comment]
Very weird.

@DMVpix Which version MIDI2LR are you using?

**Comment by DMVpix** [comment]
version 1.0.0.1
