### ISSUE TITLE
LR cc will not load the plug in

### ISSUE THREAD

**Issue by kzuments** [rsjaffe/MIDI2LR#249]
### System information

* Operating system (Windows or OS X) and version: windows 8.1
* MIDI2LR version: latest
* Lightroom version: cc
* Lightroom language:english
* Keyboard language:english
* MIDI controller:knog nanokontrol2 
* Plugin installation directory:documents/Midi2lr
* Profiles save directory: same

### Additional comments this only happened after I tried to update to the latest version of the MIDI2lr software. Everything was great until then.

![image](https://cloud.githubusercontent.com/assets/18664208/14791362/98205da0-0ae3-11e6-8c9c-26fa37f096b5.png)

**Comment by rsjaffe** [comment]
The image shows "Lightroom 5 Catalog" and the error is that the plugin is for the wrong version of Lightroom. Could you check the version again on this?

**Comment by kzuments** [comment]
Thank you 

 

Somehow my quick launch icons did not match. Working great now

 

Kris Zuments

 

-----Original Message-----
