### ISSUE TITLE
Setup problem? Can't get motorized faders to move to settings for each photo.

### ISSUE THREAD

**Issue by DMVpix** [rsjaffe/MIDI2LR#254]
### Expected behavior

Behringer BCF2000 motorized faders move to current photo settings

### Actual behavior

The motorized faders do not move

### System information

* Operating system (Windows or OS X) and version: Win 10 Home v1511
* MIDI2LR version: 1.0.0.1
* Lightroom version: CC 2015.5
* Lightroom language: English
* Keyboard language: English
* MIDI controller: Behringer BCF2000
* Plugin installation directory: D:\MIDI2LR.lrplugin
* Profiles save directory: D:\

### Additional comments

I'm sure I've done something wrong, but I am trying to set up a used controller for the first time with Lightroom and the motorized faders do not reset to the settings of the next photo. They work in "pickup" mode only. There is no movement whatsoever outside when I calibrate them to confirm they worked.

I downloaded the MIDI2LR.zip, followed the readme.txt in the "BCF2000 RSJ OneProfile" profile folder, sent the preset2.bcf file to the controller (yes, the four buttons did remap and work), and loaded Develop1.xml.

I can use the MIDI controller in Lightroom and it works minus the faders moving by motor. I spent the extra money on a motorized controller specifically to avoid "pickup" mode.

I've also done the resets and reloaded the firmware to ensure those weren't an issue. Still no luck.

Anyone have an idea? Thanks.

**Comment by DMVpix** [comment]
I need to add I'm trying to process JPG images, not RAW. It appears I'm experiencing an issue already reported (https://github.com/rsjaffe/MIDI2LR/issues/106), but apparently not resolved.

I switched over to a RAW gallery and the faders do move when I switch images.

Any update on when the plugin will work with JPG images?

Why JPG and not RAW? I photograph high school sports and have a LOT of photos to process. I just checked and I had 118K actuations in 2015 and already have 63K so far this year. Of this, I keep about half, all of which are cropped and have minor adjustments (mostly to exposure, highlights, shadows, blacks and noise). The sheer volume is why I'm exploring the MIDI controller as even minor ways to speed up the workflow can pay big dividends.

**Comment by DMVpix** [comment]
rsjaffe's suggestion in https://github.com/rsjaffe/MIDI2LR/issues/255 solved this issue. I'm repeating here for ease of reference: 

"One suggestion: while viewing a jpeg image, go to the Plugin options dialog and view the limits section, then press OK. I wonder if this is a limits issue--setting up the JPEG limits (which will happen when you follow the above steps) might be a fix."

**Comment by rsjaffe** [comment]
Thanks. See #255 for details. Bug will be fixed on next release.
