### ISSUE TITLE
Sliders unresponsive / not working / not resetting to middle on iMAC

### ISSUE THREAD

**Issue by ajaxandy** [rsjaffe/MIDI2LR#255]
### Expected behaviour

I have been using MIDI2LR successfully on PC but recently bought an iMac 5k.  I've installed the latest version of MIDI2LR on the iMac but my BCF2000 isn't working properly.  The sliders either are unresponsive most of the time or just don't work.  Sometimes they sort of work for a short while and then just stop.  MIDI2LR is recognising I'm moving the slider on the BCF but it's not communicating it to LR it seems.

### Actual behaviour

So yeah basically that and the fact when I switch to the next photo the sliders don't reset to the middle and 'tint' doesn't work although the rest of the knobs seem to be working fine.
### System information

* Operating system (Windows or OS X) and version:  Mac OS X - not sure but it's a new machine so the latest version
* MIDI2LR version: 10.0.0.1
* Lightroom version: CC
* Lightroom language: English
* Keyboard language: English
* MIDI controller: BCF2000
* Plugin installation directory: 'Documents'
* Profiles save directory: ?

### Additional comments
I copied the .XML over from the PC but I'm not sure that would cause any issues as the sliders do work sometimes albeit are unresponsive whilst doing so a lot of the time.

**Comment by ajaxandy** [comment]
Update - disabled 'pick up' mode and that seems to have resolved most of the issues.  However it's still not resetting to the middle when I change image and the Tint slider isn't working

**Comment by DMVpix** [comment]
ajaxandy, RAW or JPEG images? See https://github.com/rsjaffe/MIDI2LR/issues/106 as I am experiencing the behavior shown and had not realized this was a limitation.

**Comment by rsjaffe** [comment]
I've been unable to replicate this problem, so I'm still at a loss as to how to address it.

One suggestion: while viewing a jpeg image, go to the [Plugin options dialog](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog) and view the limits section, then press OK. I wonder if this is a limits issue--setting up the JPEG limits (which will happen when you follow the above steps) might be a fix.

**Comment by DMVpix** [comment]
THANK YOU. I don't know if this solves ajaxandy's issue, but it did mine.

I also shoot RAW, so will I have to revisit this dialog each time for the sliders to reset to the type of image I'm editing?

**Comment by rsjaffe** [comment]
No, you shouldn't have to. The reason I suspected this issue is that the limits are preset for certain DNG ranges, but not for JPG ranges. I thought the software would automatically compensate for that, but that seems not to be the case. I will fix this issue in the next release.

**Comment by ajaxandy** [comment]
Sorry I had a job to get to a client so haven't had time to look in to this since I posted, thank you for the replies.  I shoot RAW so I'll check out the steps above and feedback asap :)

**Comment by ajaxandy** [comment]
Thanks the Tint option is now resolved :)  Just need to work out the not resetting to the middle when I switch photos now

**Comment by ajaxandy** [comment]
I didn't have BC Manager installed and I think that might have been the issue... looks like it's fixed the wider issue now I've installed it.  Please close this thread :)
