### ISSUE TITLE
Differences between version 0.9.10.1 and 1.0.0.1 version

### ISSUE THREAD

**Issue by tryba2000** [rsjaffe/MIDI2LR#256]
Instructions: 
![midi2lr 1 0](https://cloud.githubusercontent.com/assets/18228236/15097448/cc73d572-151b-11e6-82a6-cd500d9d545c.jpg)
![midi2lr 9 0](https://cloud.githubusercontent.com/assets/18228236/15097449/d53dbb14-151b-11e6-9ff7-283b982237f5.jpg)
### * Operating system (Windows 10) and version:
* MIDI2LR version: 1.0.0.1
* Lightroom version: 6.0
* Lightroom language: pl
* Keyboard language: pl
* MIDI controller: BCF2000
* Plugin installation directory:
* Profiles save directory:

**Comment by DMVpix** [comment]
v1 was my first install and I couldn't find Paste from Previous, so I assigned it to a keyboard shortcut (Ctrl + Alt + V) and that seems to work fine.

**Comment by rsjaffe** [comment]
Right--it's described in the release notes. I removed the predefined keystrokes as those were causing problems for non-English keyboards. They were also causing some confusion, as shortcut keys are reused by Lightroom in different modules for different purposes.

You can now assign them as custom keystrokes, so the features can be replicated in the new version without the issues associated with the old version.
