### ISSUE TITLE
Plugin Options Dialog dont work - LR crashes

### ISSUE THREAD

**Issue by Skydupont** [rsjaffe/MIDI2LR#258]
I got the following problem:

Beim Ausführen des Menübefehls “Options” ist im Zusatzmodul ein Fehler aufgetreten.
Limits.lua:53: attempt to index global 'ProgramPreferences' (a nil value)

Please help me.

* Operating system (Windows or OS X) and version: WIN10
* MIDI2LR version: 1.0.0.1
* Lightroom version: 2015.5
* Lightroom language: German
* Keyboard language: German
* MIDI controller: BCR2000

## OK I tested and waited a long time and after a minute the site comes up. While waiting of the window Lightroom becomes in black screen and nothing happens and the mouse coursor is turning and turning around.

**Comment by Skydupont** [comment]
Is there a chance to get help???

**Comment by rsjaffe** [comment]
What directory did you install the plugin in?

**Comment by Skydupont** [comment]
Before I had it in .../Modules (same issue) now its on second drive D:\MIDI2LR.lrplugin

**Comment by rsjaffe** [comment]
See if version 1.0.1.0 fixes that. Any further questions issues should go in https://groups.google.com/forum/#!forum/midi2lr . We're terminating the github issues page.
