### ISSUE TITLE
Shortcut Keys how to send only the Control key

### ISSUE THREAD

**Issue by kkurasch** [rsjaffe/MIDI2LR#259]
I would like to send only the control key without any additional keys, it seems it is not possinle.

if I only check "control" at the Shortcut Key's and press okay the checkbox will be unchecked automatically and there is no special command for the control / alt / shift key.

I would like to use the crop Straighten Tool with this key.
Thanks for your help or advice.

![shortcut key](https://cloud.githubusercontent.com/assets/19296078/15167273/ebb08ff8-1727-11e6-836d-6e33bad0835b.PNG)

**Comment by rsjaffe** [comment]
Are you intending to "hold down" the control key while you manipulate the straighten tool or just send a keystroke (down-up)?

**Comment by kkurasch** [comment]
Actually hold-down is what I need, I would like to choose the Straighten Tool, but there is no shortcut for it. Therefore the control key is the only way I guess. Or maybe you can implement it to asign a midi command to a button to choose the Crop Straighten Tool.

THX 
![unbenannt](https://cloud.githubusercontent.com/assets/19296078/15195160/e088ffee-17c6-11e6-84ea-702a960c7b89.PNG)

**Comment by DMVpix** [comment]
Flagging this as there are other uses of this feature, e.g., holding down Alt to crop from center of photo. It would be nice to retire the keyboard while editing, but I realize there are likely constraints from doing so. Thanks.

**Comment by wetfirer** [comment]
Ctrl,  Alt, Space, Shift are modifiers used as hold buttons for various operations e.g:

Space + mouse/tablet pointer to move within the picture
Alt + mouse... to remove part of brush stroke from a current local adjustment.
