### ISSUE TITLE
NOT CONNECTED TO LR :(

### ISSUE THREAD

**Issue by H2HSTUDIOS** [rsjaffe/MIDI2LR#260]
### Expected behavior
Working normally

### Actual behavior
Not connected to LR

### Steps to reproduce the behavior
I have installed your AWESOME plugin in one of my laptops + Korg nanoKONTROL2 and it's AMAZING!!! THANK YOU :)

But I've installed in my second laptop (both Mac) with the same versions of LR, MIDI driver, etc, and it's not working. Appear the red message with NOT CONNECTED TO LR. But the MIDI is recognized, because I move the knobs and the plugin recognize it and show the values (0-127).

I've tried uninstalling and reinstalling the plugin, on LR, rebooting the Mac, etc, but is not working. Can you help me?

### System information
Apple Mac Book Pro 15" 2011
LR CC last version (2015.5.1)
Korg nanoKONTROL 2 (last version firmware 1.0.3) and last version of the Korg Mac driver.
MIDI2LR 1.0.0.1
![screen shot 2016-05-11 at 1 12 58 pm](https://cloud.githubusercontent.com/assets/19298169/15169677/543020bc-1781-11e6-8e04-6f707176f8a3.png)
![screen-shot-2016-05-11-at-1 12 58-pm](https://cloud.githubusercontent.com/assets/19298169/15169757/0a66546e-1782-11e6-951e-10d790568d46.jpg)

* Operating system (Windows or OS X) and version: OSX El Capitan 10.11.4
* MIDI2LR version: 1.0.0.1
* Lightroom version: 2015.5.1
* Lightroom language: Spanish
* Keyboard language: English
* MIDI controller: Korg nanoKONTROL last version
* Plugin installation directory: Photoshop CC Plugin directory
* Profiles save directory: Documents/midiprofiles

**Comment by rsjaffe** [comment]
In Lightroom, open up the plugin manager: File->Plugin Manager. Is MIDI2LR installed and active?

**Comment by H2HSTUDIOS** [comment]
Yes, is installed and active.

**Comment by rsjaffe** [comment]
Do you have any other unusual programs on this computer that you don't have on the other? I'm wondering if something is interfering with the communication.

**Comment by H2HSTUDIOS** [comment]
Yeah, I was thinking the same, but no, nothing unusual ;(



Enviado con MailTrack
<https://mailtrack.io/install?source=signature&lang=es&referral=yesh2hstudios@gmail.com&idSignature=23>

2016-05-12 11:10 GMT+10:00 rsjaffe <notifications@github.com>:

> Do you have any other unusual programs on this computer that you don't
> have on the other? I'm wondering if something is interfering with the
> communication.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rsjaffe/MIDI2LR/issues/260#issuecomment-218634027>
>



-- 
[image: photo]
Carlos & Pat
Destination Wedding & Family Photography

Carlos: +61 455 272 583  <+61+455+272+583>
Pat: +61 476 861 868  <+61+476+861+868>
Whatsapp: +34 675 60 89 61
Email: yes@h2hstudios.com
Website: http://www.h2hstudios.com
Skype: h2hstudios1
Address: 159, Logan Road, Brisbane, QLD 4102
