### ISSUE TITLE
Paste selected settings Highlights bug

### ISSUE THREAD

**Issue by noalorama** [rsjaffe/MIDI2LR#261]
Hello, 
first big Thank you for midi2lr and frequent updates and maintenance. After Paddy, this is finally a solution for Windows users. I hope midi2lr will survive for a long time :) Right now I'm plannig to upgrade to LR6 and buying better controller so I'm definitely gonna donate to the project. I also hope it would support keyboard and custom shortcuts for presets and such at some point. With this, there would be no need for me for multiple midi controllers. 

Anyway, there is a minor bug in Paste selected settings.
Highlights are ignored. I fixed it by editing ParamList.lua. On line 63, 611 and 762, I changed "Highlights" to "Highlights2012" and it seems to work. Again, this is not critical, just to let you know..
 
### Expected behavior
Paste selected should paste all checked settings.
### Actual behavior
Highlights are not pasted. I played with the basic panel only so far.
### Steps to reproduce the behavior
Adjust highlights > copy settings > Paste selected.
### System information
* Operating system (Windows or OS X) and version: Windows 7 x64
* MIDI2LR version: 1.0.0.1
* Lightroom version: CC 2015.5.1
* Lightroom language: en
* Keyboard language: en
* MIDI controller: Nanokontrol2
* Plugin installation directory: C:\midi
* Profiles save directory: C:\midi

**Comment by TheRealCookie** [comment]
Great! Thx for the fix! Hope the 1.0.1.0 can be released soon.

**Comment by rsjaffe** [comment]
It's in the latest release.https://github.com/rsjaffe/MIDI2LR/releases
