### ISSUE TITLE
Missing Settings / Keyboard Keys / Issues

### ISSUE THREAD

**Issue by Skydupont** [rsjaffe/MIDI2LR#262]
I miss the following Shortcut Settings / Keyboard keys:

-1. Match exposures (button)
-2. ESC(ape) (button)
-3. Backspace / Delete picture (button)
-4. Shift (button)
-5. Alt (button)
-6. Strg/Ctrl (button)
-7. Return or Enter (button)
-8. If blacks or sharpening masking is in progress over midi no Alt Button on keyboard is working to see the mask.
-9. Blinkies for Highlights and Shadows for outburning

Please help to programm or how to get upper settings.

**Comment by rsjaffe** [comment]
For number 8 and 9, [see the wiki FAQ](https://github.com/rsjaffe/MIDI2LR/wiki#faqknown-issues). That is a Lightroom bug. There is nothing we can do to get around it.

For 2-7, [see the wiki section on keystroke shortcuts](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#keyboard-shortcuts).

For 1, set up the keyboard shortcut as described in the wiki. A good list of keyboard shortcuts is at http://www.lightroomqueen.com/keyboard-shortcuts/lrcc6/.

**Comment by Deadbeef64** [comment]
I'm been searching through all the Wiki, but still can't find a solution to the question asked above.
HOW can I assign the SHIFT or CONTROL keys to a button so I can use them when I drag with my mouse.
Looks to me it is impossible/not implemented?

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.
