### ISSUE TITLE
Request - temporary alternative for Command not working on Macs

### ISSUE THREAD

**Issue by EssendonPhoto** [rsjaffe/MIDI2LR#263]
Hi

Love the app @rsjaffe - thanks so much for the work on it. I started trying it out with a Korg NanoKontrol and loved it so much after a week I have now bought a BCF2000. 

I am using MIDI2LR on a Mac and, as you know, key assignments involving the Command key do not work - I believe that you think this is due to a LR bug, correct?

Assuming so and as a perhaps temporary alternative, is it possible to include a couple more functions in the MIDI2LR command set available to be assigned to controls? I am especially interested to have "Edit in Photoshop" (Command-e) and "Auto tone" (Command-u) included in the set.

Ian

PS Just to confirm reports you already know about - the app does not close gracefully, instead giving an error popup on exit.

**Comment by rsjaffe** [comment]
Unfortunately, the only way to add those in the command set would be to try to send keystrokes, so we're back to the same LR bug.

And I've started looking at the shutdown process. It's ugly! It's all in code I inherited from the original author, and I'm going to have to do a major rewrite. If anyone is interested in helping, please contact me.

**Comment by EssendonPhoto** [comment]
Ah, what a pity! Thanks for letting me (us) know.

I wish I was sufficiently competent in Mac programming to assist with the shutdown re-write; but I'm not. :( Good luck! Please feel free to close this issue. 

And thanks once again.
