### ISSUE TITLE
What commands in lieu of keyboard shortcuts? Sharing a BCF2000 template

### ISSUE THREAD

**Issue by DMVpix** [rsjaffe/MIDI2LR#265]
This isn't a bug or unexpected behavior. I've programmed my BCF2000 using two presets to match my workflow; however, before I share the template I want to make sure I've not missed any of the embedded commands.

I have eight keyboard shortcuts. Should any of these be replaced with commands from the MIDI2LR feature set?

---Develop module--- (based on other posts, I know this one stays on the shortcut list)
Paste Settings from Previous = Ctrl + Alt + V (Cmd Opt V)

---Library module---
Compare View, Switch Select and Candidate (down arrow) = cursor down
Compare View, Make next photos Select and Candidate (up arrow) = cursor up
Compare View, Swap active photo (backslash) =  \
Grid and Compare View, Previous photo (left arrow) = cursor left
Grid and Compare View, Next photo (right arrow) = cursor right
Rotate Left = Ctrl [
Rotate Right = Ctrl ]

Please note the embedded next/previous photo command in MIDI2LR doesn't have the desired behavior when in Compare view, so I've used the left/right arrow.

FYI, I adopted presets over dedicated buttons (e.g., Pfixer) as I don't lose a button for each mode. Right now I have programmed two presets: Culling and Basic Editing. Here's the current layout:
![bcf2000-template](https://cloud.githubusercontent.com/assets/19232092/15448966/4640a476-1f3e-11e6-9a11-b36fd118cb10.gif)

**Comment by Skydupont** [comment]
Do you have an Phooshop PSD Overlay??? It would be great if you could share it for us with your settings.

**Comment by Skydupont** [comment]
How do you changed the Store, Learn, Edit, Exit and Presets buttons into Midicontrolers from factory default to your settings???

**Comment by DMVpix** [comment]
Skydupont, the overlay was created in Illustrator and I do plan to post it. To change the Store, Learn, Edit and Exit buttons, you need to load the preset2.bcf file provided with the MIDI2LR distribution using BC Manager. See https://github.com/rsjaffe/MIDI2LR/issues/84

I am not reprogramming the Preset buttons as I need those to switch between the different modes I'm programming.

**Comment by Skydupont** [comment]
DMVpix thank you very much for your support !!! Thumbs up !!!

**Comment by DMVpix** [comment]
I've uploaded the template and overlay in Post https://github.com/rsjaffe/MIDI2LR/issues/267

I'm still interested in whether I should change any of the keys. If so, I'll modify and update the template and XML as the info is discovered.

I'll also add the "X" to rotate crop if the issue in Post https://github.com/rsjaffe/MIDI2LR/issues/247 can be addressed.
