### ISSUE TITLE
Copy/paste develop settings - Highlight value not copied

### ISSUE THREAD

**Issue by senepro** [rsjaffe/MIDI2LR#266]
Dear rsjaffe!

I figured, that during the copy/paste/paste selected settings (in the develop module) command, the highlight value not copied/pasted. Could you help me, what could be the problem, or this is a bug in the Midi2LR?

Thanks,
John

**Comment by rsjaffe** [comment]
This is a bug -- an undocumented feature/bug in Lightroom. It will be fixed in the next release.Which should be very soon.

**Comment by senepro** [comment]
Thank you, waiting for the next release...
