### ISSUE TITLE
BCF2000 template and overlay by DMVpix.com

### ISSUE THREAD

**Issue by DMVpix** [rsjaffe/MIDI2LR#267]
I'm sharing my setup for MIDI2LR (v 1.0.0.1) using a BCF2000 in case others may find it of benefit. It is a mix of some Pfixer, the default settings and my own preferences. I am running Lightroom CC on a Windows computer.

I realize templates are highly personal, so if nothing else you can get an editable overlay out of this post.

A couple of key points to make is:

1) I'm using Presets instead of dedicated buttons for the different modes. As of now I have programmed two presets: Culling and Basic Editing.

2) The layout uses shortcut keys, which you'll need to create in your instance of MIDI2LR. The keys are shown on the overlay.

The needed files (BCF and XML) and editable overlay (Adobe Illustrator (original) and Photoshop (exported from AI)) are in the attached ZIP. Be sure to send the .bcf file to the controller (see Post https://github.com/rsjaffe/MIDI2LR/issues/84).

Here's a view of the overlay: 
![bcf2000-overlay-for-midi2lr-dmvpix](https://cloud.githubusercontent.com/assets/19232092/15526129/7b19ec0e-21fd-11e6-99ec-7ca6b9420343.gif)

[BCF2000 MIDI2LR DMVpix Preset.zip](https://github.com/rsjaffe/MIDI2LR/files/280873/BCF2000.MIDI2LR.DMVpix.Preset.zip)

**Comment by Skydupont** [comment]
@DMVpix Faboulous !!! I'll check it out. Thanks for your support and help!!!
