### ISSUE TITLE
Development Plans

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#268]
Those of you watching the git repository may have seen a number of commits. I was near to releasing a new version but ran into a lot of the old problems. So,... Here's what I'm planning to do.

1. Completely rework how MIDI2LR handles undefined limits. This has been a problem for various people, with "unresponsive controls", particularly temperature. This should be out with the next release (I hope).
2. Try to attack the shutdown issue in OS X. I've isolated some of the problems: in LR_IPC_IN the *run* member function (which is run as an independent thread). Lots of this code is JUCE-dependent, and I'm not sure where the problem lies. If someone here is good with multithreaded applications, please pitch in.
3. Try to figure out why the *command* key doesn't work in OS X. I'll need help from a Mac user for this.

Development has slowed down for several reasons:

1. The remaining issues are harder to fix.
2. The main planned functionality of the initial application is working (except for keys in OS X).
3. I'm busy with work, home, etc.

Helpers wanted! Especially for the OS X issues: shutdown, and keyboard shortcuts.

Thanks

**Comment by bozwellox** [comment]
More than happy to help in any way I can with the Mac troubles!

**Comment by DMVpix** [comment]
Sorry, I'm not a programmer. I will help where I can, e.g., the editable template I've already posted for a BCF2000. I do appreciate the plugin though and will be using it extensively once fall sports start.

**Comment by TheRealCookie** [comment]
I can't help programming, but I will help with small donation.
Don't let this great piece of software die.

**Comment by rsjaffe** [comment]
@bozwellox Could you attack the command key issue?

From what I can find out, the application properly sends the keystrokes in OSX, but the way LR listens for command keys causes it to miss the command key press when sent the way I'm sending it.

The following would help:
a listing of the key events sent by the operating system when ```command a``` is pressed;
emulating that sequence in the sendkeys module of the app.
seeing if that works with LR.
if not, playing around with different sequences and delays to try to convince LR that command was intended.

As part of the migration to google groups, I'm closing this thread, but please respond on groups:
https://groups.google.com/forum/#!forum/midi2lr
