### ISSUE TITLE
Paste settings from previous not working

### ISSUE THREAD

**Issue by michaelmowbray** [rsjaffe/MIDI2LR#269]
### System information

* Windows 7 Professional
* MIDI2LR version:  0.9.8
* Lightroom version:  CC
* Lightroom language:
* Keyboard language:
* MIDI controller: Novation Launch Control XL
* Plugin installation directory: standard
* Profiles save directory: 

###

**Comment by DMVpix** [comment]
You're using an older version of the plugin. If you upgrade to the latest version, you must create a keyboard shortcut and it will work as I use this command on my setup.

**Comment by michaelmowbray** [comment]
Updated to 1.0.0.1 and created a key shortcut for Ctrl+ALT+V.  Mapped that to several different keys that already work with other mapping.  Nope.  Still not working.

**Comment by noalorama** [comment]
michaelmowbray: Yes, I noticed too. Strangely, setting ctrl+alt+v instead of capital "V" helped.

**Comment by michaelmowbray** [comment]
Hahaha....I tried it lower case v first then tried upper case. No go on either.

**Comment by DMVpix** [comment]
I'd suggest creating a couple of other shortcuts and testing those to see whether it is just this one problem or something larger. It is working on my version of LR CC on Win10. Good luck.

**Comment by wetfirer** [comment]
Actually none of my keys worked at all :-( 

Win 10 x64, LR 6.5 Working path: H:\Lightroom\LR Plugins\MIDI2LR)

Wanted to add a screenshot, but I don't know how to add it here .

**Comment by DMVpix** [comment]
I'm shooting in the dark here, but I had a couple of instances where the buttons weren't responding when I was customizing my setup and everything worked again after I reloaded the preset2.bcf file for the BCF2000 controller using BC Manager. I'm not sure what controllers you're using, but hopefully there is a way to set it back to default behavior then to load back your MIDI2LR settings easily.

**Comment by rsjaffe** [comment]
We're closing the github discussions and moving to google groups. Please post any subsequent comments/questions there: https://groups.google.com/forum/#!forum/midi2lr
