### ISSUE TITLE
Bank 3: Push Knob Showing Wrong Knob Numbers

### ISSUE THREAD

**Issue by surjones1** [rsjaffe/MIDI2LR#270]
### Expected behavior
Bank 3: Press in knob 44, 44 should open up and be able to map 

### Actual behavior
Im setting up my knobs - everything has been smooth till of course Im almost down. While in Bank 3, I press in the 2/44 and it shows 2/47, I press in 2/45 and it shows 2/47, I press in 2/46 and it shows 2/46, and I press in 2/47 and it shows 2/47. Turning the dials does the exact same thing.  All other buttons seem to work just like normal on pressing and turning with the correct numbers.

### Steps to reproduce the behavior
I've rebooted, I've deleted the plugin, and re-installed, installing my SAVED file. Im not a coder, but I opened up the saved XML file, duplicated the line code, and change 2/47 to 2/44 and then loaded it, and nothing showed up, deleted the line code I added, loaded and it loaded just fine.

### System information

* Operating system OSX 10.11.5
* MIDI2LR version:1.0.0.1 (Always crash on quiting)
* Lightroom version: CS6 (current update)
* Lightroom language: English
* Keyboard language: English
* MIDI controller: Fight Twister
* Plugin installation directory: IDK
* Profiles save directory: IDK

thanks in advance

**Comment by surjones1** [comment]
Anyone still alive in this site? :)

**Comment by Skydupont** [comment]
I think u have to programm your midi controller right. Thats all.

**Comment by surjones1** [comment]
You think I have to control it correctly (I'm assuming that's what you meant) The answer is I am. So That being said it's clearly something wrong if I push a knob and it's not registering the correct nu,beer of knob.

**Comment by rsjaffe** [comment]
We're migrating to google groups, which is better for discussions. Please post subsequent messages there: https://groups.google.com/forum/#!forum/midi2lr

It does look like you have the wrong channel programmed for one of your controls. Please check the channel assignments on your Flight Twister.
