### ISSUE TITLE
Request: Would MIDI2LR project benefit from gaining a mailing list?

### ISSUE THREAD

**Issue by rubin110** [rsjaffe/MIDI2LR#271]
Hi there. I popped in here as my BFC2000 stopped working correctly on my Windows 10 machine. I'm pretty sure the issue is more OS related than MIDI2LR. Going into the project's Github issues page, I realized this really isn't the spot to discuss things not directly related to the code base that is MIDI2LR.

Would the maintainer of this project benefit from a separate mailing list that's more community discussion oriented? I imagine things that could get discussed in there are...

- Annoying MIDI device / OS issues
- Sharing neat Lightroom tricks with MIDI2LR
- Sharing button mappings
- Discussing new and interesting MIDI devices to use with MIDI2LR

Getting a mailing list setup through Google Groups is fairly straight forward.

P.S. While drafting this up I figured out my issue. I recently started using Remote Desktop (RPD) to access my Windows machine from my Linux laptop and attached screen. By default the RDP client I'm using disabled audio forwarding, which Windows achieves by disabling most audio devices including MIDI.

**Comment by rsjaffe** [comment]
I heartily agree. Github is really poor for discussions and help--it's best just to track application changes and bugs.

The group has been created:
https://groups.google.com/d/forum/midi2lr

**Comment by rubin110** [comment]
👍

I'd encourage you to throw up the link onto the github page and your project page. :)

**Comment by rsjaffe** [comment]
Thanks
