### ISSUE TITLE
Odd behavior in latest LR update

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#28]
It appears that the latest LR update has changed the amount of information sent when moving to a different photo in the Develop module. This may leave most controls unsynced. I'm holding off on the official MIDI2LR 0.4.2 release until I put in a temporary fix. If anyone wants to try the 0.4.2 release, I've put a beta version for PCs (without the fix) here: http://thejaffes.org/tmp/MIDI2LR.lrdevplugin.zip

**Comment by wockawocka** [comment]
4.1 is fine though. (BCF2000) :)
