### ISSUE TITLE
Problems with Mac/X-touch mini/Midi2Lr

### ISSUE THREAD

**Issue by douglascostanzo** [rsjaffe/MIDI2LR#280]
Hi, 

I am having two issues for setup my new device. Probably, I am not doing something right...

The first one is, even saving and uploading the profile I organize with my adjustments, after every time I close the Lightroom, even all the profile seems right uploaded on the screen, when I touch anything on the x-touch for the adjustments, it says that it is unmapped and I have to start again.

The second one is, I couldn't find a way to how save one preset on the lightroom and have it actived calling it on my x-touch mini/midi2lr presets panel. I don't know if it is a problem with the name I have to save on the presets panel on Lightroom, although I have tried a few.

I know that probably these are stupid questions but I couldn't find a way out so far. 

Any help would be really appreciated

Regards

Douglas

**Comment by rsjaffe** [comment]
Please post this on https://groups.google.com/forum/#!forum/midi2lr . The issues tracking section here is closed and not monitored regularly.
