### ISSUE TITLE
App language translations

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#286]
Currently, only plugin translates interface to local language. Plan to use LR translation features to translate app interface as well. see https://github.com/rsjaffe/MIDI2LR/tree/feature/app-languages

**Comment by mathieucarbou** [comment]
Hi @rsjaffe, I saw your commit 23eb53e0f0a8aaff138699a2aa0f30cc5f32

How do you find the right path to use for the translation (I.e. `LOC("$$$/CRaw/ToneCurvePreset/MediumContrast`) ? 
Is there a manual or file somewhere referencing all Lightroom translations ?

Thanks!
