### ISSUE TITLE
OSX shutdown hangs

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#287]
See https://github.com/rsjaffe/MIDI2LR/tree/feature/OSX-Shutdown . Currently addressed by issuing a force shutdown in OSX.

**Comment by mathieucarbou** [comment]
Hi @rsjaffe : the branch is not available anymore. This issue is still there ? I can start a branch from the develop branch ?

**Comment by rsjaffe** [comment]
yes, start a new branch. thanks

» Rory Jaffe <rsjaffe@gmail.com> • Our family web site
<http://thejaffes.org/>

 «
