### ISSUE TITLE
Extend Selection

### ISSUE THREAD

**Issue by stevejmu** [rsjaffe/MIDI2LR#29]
## Feature Request: Extend Selection

Please implement the Extend Selection class to map to a button and/or keyboard shortcut (if keyboard shortcuts are ever implemented, too). Currently the only selection-type classes are "Next Photo" and "Previous Photo".

As for keyboard shortcuts, I'd like to use the keyboard to map the D / F keys for previous / next and use the SHIFT + D / F to extend the selection in either direction. Doing so allows me to keep my hand on the mouse for selecting white balance with the eye dropper, rotate / crop an image, use the adjustment brush or spot tool.

### LrSelection.extendSelection( direction, amount )
Extends the existing selection, selecting more photos to its beginning or end. Behaves exactly like the Shift+Left/Right Arrow keys in Library grid. 

First supported in version 6.0 of the Lightroom SDK.

##### Parameters
1. direction(string) either "left" or "right"
2. amount(number) number of photos to add to the selection in that direction

**Comment by rsjaffe** [comment]
See #31
