### ISSUE TITLE
Add more debugging facilities

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#293]
Goals are to help users feed data for bug requests, and help developers see what's going on.

Some ideas:

- [ ] menu-item>console that shows live logs
- [ ] see what is sent to the MIDI controller 
- [ ] include a shell specific for midi2lr (there's already some projects to look for ideas such as Lua Shell and Lua Console) with the inspect.lua lib

**Comment by rsjaffe** [comment]
Have you used the debugger in the Zerobrane IDE? The app has hooks in it for that debugger.

Will this add new capabilities?

The hooks are commented out in Client.lua. See lines 21-24 and 486.

**Comment by mathieucarbou** [comment]
I didn't know that, thanks! Actually I'm new to Lua so I am still learning ide and tools. I'm a bit busy at the moment so didn't have time to look into other issues but will do soon :-)

But this ticket was a bit more to add some menu items or things that can help users or developers troubleshooting user issues. Such as the ability to activate debug logging for example that could be looked into or sent, the ability to see what is sent and received to/from midi controllers, etc.
