### ISSUE TITLE
Moving to a completely Lua-based GUI

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#299]
I find it hard having to deal with both C++ code and Lua code, both having a lot of redundancy in naming and also they are quite coupled (i.e. when creating new menu items).

I saw there are several solutions existing to make Lua-based GUI, such as __WxLua__ (http://wxlua.sourceforge.net/)

I see a lot of benefits to such (big) migration:

- will improve contributions
- will help providing some quick patches to users if some bugs are found
- development process would be smoothier

**Comment by rsjaffe** [comment]
The database-driven approach was my attempt to manage the tight coupling, as the database generates plugin code,, app code, and documentation.  It would be nice to simplify the structure. However, Lightroom sandboxes the Lua environment for plugins, so I'm not sure you'd be able to use an external framework. Many system calls are unavailable under LR. 

LR does provide a gui framework, which might be flexible enough for our purposes. The nice thing about staying within the LR framework is that it definitely works in Windows and OSX, and it has built in internationalization.

**Comment by mathieucarbou** [comment]
Yes I agree. I looked at WxLua because I didn't manage to find an example of a Lightroom plugin having a non-modal window. I always found samples that use modal dialogs. But I didn't extensively search.
Do you know some ?

**Comment by rsjaffe** [comment]
Looks like this won't work.
