### ISSUE TITLE
Move all MIDI2LR settings / options in the same file

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#303]
Currently, there are several configuration files:

- MIDI2LR.xml in user app folder
- the XML Mapping file
- Settings saved (option dialog)

It would be nice to reduce the set of places to facilitate config migration.

See: https://groups.google.com/forum/#!topic/midi2lr/ZiHKnpj5qDg

**Comment by JMhowell** [comment]
I have a question about Profiles. When I select the profile, the encoders don't work as described. They just work as originally established.

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.

**Comment by rsjaffe** [comment]
Folders organized better now.
