### ISSUE TITLE
Support local adjustment tools: size, feather, flow, density, overlay, etc

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#307]
Support for brush / radial / etc tools:

- ~[ ] size slider~
- [x] feather slider
- [ ] flow slider
- ~[ ] density slider (less important)~
- [X] Show Selected Mask Overlay (see PR #384)
- [X] Cycle Overlay Color (see PR #384)

See: https://groups.google.com/forum/#!topic/midi2lr/hmQB1IfDUyM

See also some articles about keyboard / mouse shortcuts:

- http://www.lightroomfanatic.com/tutorials/beginner/changing-the-adjustment-brush-properties-in-lightroom-5/
- https://forums.adobe.com/thread/1034029

I determined that:

- Overlay options are easy to do. 
- Size is useless, since can be achieved from the mouse wheel or trackpad.
- Density slider is less important than flow - density can be kept at 100% most of the time
- Flow and feather would be feasible by sending keys to decrease/increase after the action of a button or better whether we turn an encoder on the left or right side

**Comment by wstoettinger** [comment]
This feature would make Midi2LR superior to LrControl! Woul very much appreciate it!

**Comment by rsjaffe** [comment]
Supported now to the maximum extent permitted by API. Have put in feature request to Adobe for Flow, Density
