### ISSUE TITLE
Github repository settings (waffle.io and protected branches)

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#318]
https://waffle.io/rsjaffe/MIDI2LR (for task management)

- admin hook must be setup (red banner at the bottom)
- wafflebot should be installed (left panel, flash icon)

Github repository settings:

- activate protection on protected branches (such as `master` and `develop`): if we want to prevent push on this branch, forcing a PR first, and also force a review before any merge

![screen shot 2016-11-15 at 14 30 02](https://cloud.githubusercontent.com/assets/61346/20320536/29fcb8fc-ab40-11e6-98f3-95325fc4b92f.png)

**Comment by rsjaffe** [comment]
OK, I've enabled the admin hook and installed wafflebot. I don't understand the merits of protected branches. Who can currently alter my version of the project?

**Comment by mathieucarbou** [comment]
All depends on the preferred workflow of your project. I.e. in the other OSS projects I'm working on, we prefer to disallow direct push into the master (here develop and master) branches to force users and collaborators to send PR, and we even also force that PR gets at least one review otherwise they cannot be merged.
It's usually best practices when working in the same OSS project with other people guys are also committees.

**Comment by mathieucarbou** [comment]
@rsjaffe : can we close it ? I think you made the changes ?
