### ISSUE TITLE
Clear a preset mapping in option dialog

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#327]
I'd like to be able to clear or remove / unmap a preset mapping:

![2016-11-27 15_00_37-set midi2lr options](https://cloud.githubusercontent.com/assets/61346/20651392/a9ef40ea-b4b2-11e6-9157-d8424a14cc1f.png)

I don't know the best way to do that but I can see:

1. having a blank entry in the list that, when selected, would clear the mapping
2. having a "clear" button next to each entry

**Comment by rsjaffe** [comment]
**Clear all** would be very simple. Much harder to have a clear for each individual one. I'll have to think on that.

**Comment by mathieucarbou** [comment]
@rsjaffe : to implement, yes, but I disagree for the user experience though because in my case, I have a lot of preset: the drop-down is huge, and finding the right one in these small boxes is really a pain because a small move scrolls a lot... In my case, I know the preset name. So having a drop-down list or an auto-complete field would be better.
A list is logically used when you want to present a set of items to the user that he needs to see in a whole because he content is not known in advance and he has to choose.
In the case of preset mapping, I am pretty sure that users know what they want to map before even opening the option dialog ;-)

**Comment by rsjaffe** [comment]
I may be misunderstanding you. Are you looking to change the left side of the picture you posted to a set of drop-down lists or are you wanting to be able to individually clear each assignment?

**Comment by rsjaffe** [comment]
OK. Got it now. Will add blank line to top of preset list.

**Comment by rsjaffe** [comment]
done  7e4dd79
