### ISSUE TITLE
Ensure MIDI2LR commands are executed in order

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#333]
See: https://groups.google.com/forum/#!topic/midi2lr/jo00fYFRnVY

This would solve #331.

Some ideas:

1. put in a queue all MIDI2LR commands received, and dequeue them once they are executed. This would make MIDI2LR waits for an async command to be executed before running the next ones.

2. Other possibility would be to use the LR queue mechanism that is asynchronous and once a command arrive, we start an asynchronous task that will dequeue all commands, until finished. Since we are already in an async task in this case, I guess we won't need to start any other async task for point curve and profile corrections for example. We could just run all commands one by one in this async task.

**Comment by rsjaffe** [comment]
All of `Client.lua` is already in an async task--that was done to stop blocking Lightroom during initialization of the program.  So we don't have to start another one--could just queue within this task.

LR has another mechanism to use when receiving information faster than it can process: `LrRecursionGuard`. We already use that for simple parameter changes and for receiving parameter information from Lightroom. We could add that to the other actions in the message handling loop--see line 531, or could put the entire body of the `onMessage` function into a guard.

See `LrRecursionGuard` documentation. We've been using it in a way that ignores messages if they come too quickly. For simple parameter setting the user doesn't really see anything odd, but it could be an issue if it were a number of button pushes instead, as the button pushes would come from different controls and some could be ignored. We can also use `LrRecursionGuard` as a mutex and queue things that way.

Certainly, if we pull stuff off a queue, we'll have to use a mutex. I worry about performance issues, as the LR API version of a mutex pretty much requires you to spin around it while waiting.

I had a number of odd message handling issues that were improved by adding the guards and optimizing the `LrSocket` code for both receive and send, that I blame on timing issues within LR.

**Comment by mathieucarbou** [comment]
Thanks for the explanations :smiley:

**Comment by rsjaffe** [comment]
We could try asynchronous tasks for a message queue and yield when empty, but I'm worried about implementing a queueing mechanism that would be concurrency-safe. It might be best to leave this alone and tolerate occasional quirks, as the cure may be worse than the disease.

**Comment by rsjaffe** [comment]
Or https://www.lua.org/pil/9.2.html . LR hides some of the coroutine functions in lua, so I'm not sure how far we can go with this.

**Comment by mathieucarbou** [comment]
the producer / consumer (https://www.lua.org/pil/9.2.html) seems to lack a queue to buffer and order things (I am a newbie to Lua: I know Java really well).

In our case, I do not see any concurrency issues if we implement by using the same pattern they used in javascript: http://api.jquery.com/jquery.queue/.

All is async in javascript. So the idea is not to enqueue objects, but functions that do something and will call the next dequeue.

so this is like we had:

queue = {}

// Point curve command arrives, we push the function to execute in the queue
queue.push(function(queue) {
   runPointCurve(function callback() {
      // point curve async command finished
      dequeue(); // like a call to next(): take the next function in the queue and execute it
   });
})

So this is ordered, and the dequeuing can be done within the same thread. We just need to either launch a thread that periodically check the queue to dequeue it, or, that will wait for a mutex saying that now the queue is not empty, it can run, etc.
Or, it could be the tread that created the functions and put them in the queue that triggers this dequeuing in another tread, if it detects that the queue is empty.

with this approach, we can avoid using a "central" data structure, but instead trying to "link" the next thing to execute to the previous thing so that all functions are like nodes that execute one after the other.

**Comment by rsjaffe** [comment]
commands now queued
