### ISSUE TITLE
Generate SHA or MD5 signatures for MIDI2LR zip file and file content ?

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#334]
See: https://groups.google.com/forum/#!topic/midi2lr/bDzTERXGHbo

- [x] Submit the sample to MS (https://www.microsoft.com/en-us/security/portal/submission/submit.aspx)
- [ ] Generate SHA signatures for executables or all project files so that users can validate if the executable (or any file) has been tempered after unzipping MIDI2LR

Note: why not creating a sort of `dist.lua` file, runnable just with `lua dist` that would create this md5 file (https://github.com/kikito/md5.lua), and also eventually create the zip file or do anything else required to generate a distribution zip ?

**Comment by rsjaffe** [comment]
Started putting md5/sha signatures in version history section of wiki.

Sample submitted to Microsoft.
