### ISSUE TITLE
LrDevelopController.revealPanel usage

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#339]
Hi @rsjaffe,

This morning I found something pretty cool. I don't know how we could use it but basically `LrDevelopController.revealPanel(name)` can be called by any command name, not just the name of the panel. I tried in an Lua Console with several commands.. For example: `LrDevelopController.revealPanel("Exposure")` will be equivalent to `LrDevelopController.revealPanel("adjustPanel")`

I don't know if it could lead to some code simplification or not, but at least, we know that

**Comment by rsjaffe** [comment]
We already have the control-panel assignments in the database, so this wouldn't save much but it's nice to know--did you try it with the Transform controls? I wonder if the mapping is wrong there as well.

**Comment by mathieucarbou** [comment]
No it doesn't work and it is quite random. For example, `LrDevelopController.revealPanel("PerspectiveVertical")` shows the lens correction panel, but `LrDevelopController.revealPanel("UprightFull")` does strictly nothing at all.
