### ISSUE TITLE
Mapping "Temperature" to first slider (CC:0) doesn't work

### ISSUE THREAD

**Issue by neilpho** [rsjaffe/MIDI2LR#34]
I've mapped the 8 sliders of my nanoKontrol2 to the 1st 8 basic controls of Lightroom CC 2015.1. They all work as expected except for colour temperature. It's not possible to "pick up" the thumb of this slider unless it is at the lower end of the scale. Then is is only possible to move the slider downwards so the image ends up stuck with a blue cast.

**Comment by rsjaffe** [comment]
Please try assigning temperature to one of the other sliders to see if the problem is related to that slider or not. Thanks.

**Comment by neilpho** [comment]
Good idea. I tried another slider and a knob and the problem is related to temperature rather than the control used.

**Comment by rsjaffe** [comment]
Hmm. Could you try the following?

In the plugin's directory, open up the file MIDI2LR_Client.lua in a plain text editor like notepad. Around 30 lines down, you'll find the following code: 
```lua
local function midi_lerp_to_develop(param, midi_value)
    -- map midi range to develop parameter range
    local min,max = LrDevelopController.getRange(param)
    if(param == 'Temperature' and max > 8000) then
        min = 2000
        max = 8000
    end
    
    local result = midi_value/127 * (max-min) + min
    return result
end
```

Edit the line
```lua
if(param == 'Temperature' and max > 8000) then
```
to read
```lua
if(param == 'Temperature') then
```

Save the modified file, then, in lightroom, open up the plug-in manager (file->plugin manager), select the MIDI2LR plugin and press the button to reload the plugin. Or you could just restart LR. Then see if that fixed the issue.

If that didn't fix the issue, edit the lua file to remove the range control for temperature by deleting the following lines, then test as above.
```lua
    if(param == 'Temperature' and max > 8000) then
        min = 2000
        max = 8000
    end
```

**Comment by Der-Canonier** [comment]
The error occurs with me also. Both solutions are not working. The temperature will be provided by 5250 to 4409 and then to 3559, then nothing happens. Increasing the temperature does not work

**Comment by rsjaffe** [comment]
I'm reverting the change that was made to the temperature range control. Will see this change in the next release.

Reverted commit 31c029c31ffcef3368ad8f4db9cfbb4a57b5a6d6 in commit d24f025835caee1bac2fae68d27311b39067d28b .
