### ISSUE TITLE
Midi2LR Crashes Lightroom CC on Picture Export

### ISSUE THREAD

**Issue by pdeboos** [rsjaffe/MIDI2LR#344]
I need to Disable the Plugin before any export attempt. With the Plugin enabled, Lightroom just hangs as soon as the Export menu is opened. It 'looks' like Lightroom is waiting for all connected disks to be spooled up. Forever.
As if LR sees (and fails to access) the Midi controller as a USB external disk ...
The MIDI controller is the KORG nanoKontrol2
System is a MacbookPro
OS 10.12.1 Sierra

**Comment by rsjaffe** [comment]
Please repost on the discussion group at https://groups.google.com/forum/#!forum/midi2lr , as that is the place for assistance. This issues log is only for developing and assigning coding tasks.
