### ISSUE TITLE
Add keywording support

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#345]

**Comment by mathieucarbou** [comment]
Hi @rsjaffe ! How do you intend to achieve that ? Do you have an idea ? Is it by adding a UI screen in MIDL2LR options where you could map some keywords, like keystrokes  ? Or is there a better way ?

**Comment by rsjaffe** [comment]
This is a tough one. Getting the current keyword hierarchy is complicated. 

But, yes, I thought the UI would look like the keystrokes UI. However, we'd have to link the options to the hierarchy currently in LR for keywords, as the same keyword could occur different places in the hierarchy.

Also, the list of available keywords may be huge.

**Comment by mathieucarbou** [comment]
yes! For the duplicates, I have some and a way to avoid that would be to always tag with the full hierarchy. 

Example:

If we have:

```
parent1
   |--- tag1
parent2
   |--- tag1
```

then we ould have to tag with:

`parent1 < tag1` or `parent2 < tag1`
