### ISSUE TITLE
Key shortcut problem with non-english keyboard layout and mac use

### ISSUE THREAD

**Issue by Keylhan** [rsjaffe/MIDI2LR#346]
Hi rsjaffe,

First of all, thank you for your awesome job on Midi2Lr!

I saw in the 1.6.1.0 release note that you were searching for some Mac testers. Maybe I can help.

My context:
- System : Mac OS X Yosemite, in French
- Lightroom version : 6.8 (not CC), in French
- Midi2Lr version : 1.6.1.0
- Keyboard : French azerty keyboard
- Midi device : x-Touch mini

Constated issues with key shortcuts:
- shortcuts that include a command key don't work
- the 'f' shortcut (shortcut for Fullscreen) doesn't work

Let me know what I can do to help. Is there any debug mode so I can get some logs?

Best Regards

**Comment by rsjaffe** [comment]
Do you know how to code for the Mac? We need someone to revise and test the key send code, and possible change it from C++ to Objective-C++ or Swift.
