### ISSUE TITLE
LR doesn't support reference view yet

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#349]
Response from Adobe:

> Thanks for the report. This will be fixed in the next Lightroom update. You will be able to call 
> 
> import "LrApplicationView".showView( "develop_reference_horiz" ) or 
> 
> import "LrApplicationView".showView( "develop_reference_vert" )
> 
> to go to Left/Right or Top/Bottom reference view. Of course this will only be available for CC version of Lightroom.

**Comment by wetfirer** [comment]
Await it before end of march. That is what I got from a dev.
