### ISSUE TITLE
Light up the MIDI controller to  to app statecorrespond

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#359]
E.g., selected profile.

**Comment by cbishop76** [comment]
It could be done by having a field on the Profiles tab next to each xml field where the user can specify a CC number for that profile.
When a ProfileSwitch event occurs, send a Note On message with Velocity 1 to the associated CC for the new profile and a Note Off message to all other CCs linked on the profiles tab.

**Comment by rsjaffe** [comment]
I like that idea. Thanks.

**Comment by rsjaffe** [comment]
Are you going to put in a pull request?

**Comment by cbishop76** [comment]
Would love to help and have been looking through your code, but I think the juce framework is confusing me a bit in visualizing the whole program flow.  In all honesty C++ is not my language.

**Comment by rsjaffe** [comment]
Duplicate of #477
