### ISSUE TITLE
See the wiki for full listing of MIDI2LR commands

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#36]
A full listing of commands available in MIDI2LR is now on [the wiki](https://github.com/rsjaffe/MIDI2LR/wiki).

**Comment by rojmagd** [comment]
Ok perfect. I'm waiting impatiently for the next version. Copy and paste operations, virtual copies, and modules selection are very important for me to increase my working efficiency.

Thank you very much for work. It helps me a lot.

**Comment by Clueless2015** [comment]
Yep can't wait for this latest build to be able to program a few buttons with functions.

Thanks :)

**Comment by rsjaffe** [comment]
Next release should be out soon. Need to fix the code for copy/paste (current code is incorrect--turns out copy/paste more complex than I thought) and test the other additions.

**Comment by rsjaffe** [comment]
Latest version has virtual copies and modules selection. I've just fixed
copy/paste, so that'll be in the next release.

» Rory Jaffe <rsjaffe@gmail.com> • Our family web site
<http://thejaffes.org/>

 «

**Comment by Clueless2015** [comment]
Excellent, thanks :)
