### ISSUE TITLE
Set Windows Installer default path to LR module folder

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#363]
The installer default path should be ideally set to the current's user Lightroom module folder at:

`%APPDATA%\Adobe\Lightroom\Modules\`

**Comment by rsjaffe** [comment]
I can see that for windows, will make change

**Comment by rsjaffe** [comment]
But can people find that? the appdata directory is normally hidden.

**Comment by mathieucarbou** [comment]
I don't know... For photographers, I guess because they are used to put their LR plugin at this location. At least by opening the module folder from LR, so even if they do not have to know how to go there since the root, they are used to put things in that folder.

**Comment by rsjaffe** [comment]
Ok
