### ISSUE TITLE
Vertical and Horizontal Perspective Transform Sliders are mixed up.

### ISSUE THREAD

**Issue by wstoettinger** [rsjaffe/MIDI2LR#366]
Assigning the Perspective Vertical value changes the horizontal value in Lightroom and vice versa.

Furthermore, only the vertical slider (which moves with the Perspective Horizontal setting), moves in the wrong direction.

Same thing with "Perspective X" and "Perspective Y". Their name is also misleading, imho they should be named "Offset X" and "Offset Y".

Version: 2.0.3.1 on Windows, LR 2015.7

**Comment by rsjaffe** [comment]
See FAQ 4: https://github.com/rsjaffe/MIDI2LR/wiki#faqknown-issues

**Comment by wstoettinger** [comment]
ah, I see! Thanks! I did search the issues though ;) 
And I'm assuming there is no way to find out, which mode the picture is currently in, to adjust for this bug?

What about the naming of perspective x and y?
