### ISSUE TITLE
Commands for 'Paste', Rotate, and Develop Presets?

### ISSUE THREAD

**Issue by b3nb123** [rsjaffe/MIDI2LR#38]
Firstly I have to say the simplicity of this plugin is great! I've just put it on my laptop, plugged in a NanoKontrol 2 and it just worked in mere seconds!

On my desktop PC I'm set up with Paddy and a Behringer BCF2000 and some of the controls I set up stopped working, some of the things I try and set up afresh just don't take. Quite infuriating. However, the way I have it now just works for me for 95% of the controls I use when editing huge batches of wedding photos so although I really want to change to MIDI2LR for my main PC I won't switch over until I know it does all I require.

Am I right in saying there's no option for 'Paste Previous'? Or have I missed it?
Any way I can twist a dial for rotating an image?

Will there be any plan to add develop presets?

I just love how to select a button to program you just prest it. Really smart. And I guess helpful too for the software - as long as your midi controller has a button the software can learn what a click looks like and map a command to it. Really cool.

Sorry if my questions are commonly asked, hope anyone can advise
Thanks

**Comment by rsjaffe** [comment]
paste previous photo's settings is in development right now--I'm working out a few bugs. It should be in the next release unless I am unable to fix the bugs in time.

There's a way to rotate the image in the lens corrections settings, but I suspect you're talking about 90 degree rotation. There's nothing in the plan yet for that.

Adding develop presets is definitely in the planning stage.

**Comment by b3nb123** [comment]
Thanks, good to hear presets may be an option one day, all those buttons,
it would be great to quickly apply a favourite. More important to quite a
few people I'm thinking would be the previous button, when going through a
big set of photos it's something I personally use loads.

Regarding the rotation, I wasn't talking about the transform, rotate
setting, I meant crop angle, it would be great to adjust a slightly wonky
photo with a twist of a knob!

Thanks for the great work, it's such a simple and effective piece of
software!

**Comment by DavidWeaverPhoto** [comment]
I'm assuming that anyone using MIDI2LR is also familiar with shortcut keys in LR. ;-)
https://helpx.adobe.com/lightroom/help/keyboard-shortcuts.html
A couple early ones that are very useful are In the develop module next and previous are just right arrow and left arrow. In Develop mode it's CTRL+ [L/R] Arrow.    
To copy settings (w/ dialog) it's CTRL+SHFT+C, and to past settings it is CTRL+SHFT+V.
To past the settings from the previous photo it's CTRL+ALT+V 
(these are Win keystrokes, but MAC equivalents are there.)
Just FYI.

**Comment by b3nb123** [comment]
Thanks David, I'm familiar with the keyboard shortcuts!
but the convenience of a midi controller setup is adjusting a batch of
photos with minimal reaches for the keyboard or mouse. Paste is a three
finger command, one button, for example programmed over next to previous,
next and undo, for me is a button I use a lot on my paddy setup.
Would an option of custom keyboard inputs from one button be easier instead
of trying to tap in to the exact lightroom command directly?

**Comment by rsjaffe** [comment]
copy-paste settings are in the latest version. presets coming very soon.

**Comment by rsjaffe** [comment]
Presets are in 0.6.0
