### ISSUE TITLE
2105.9 broke some experimental features

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#381]
https://groups.google.com/forum/#!topic/midi2lr/siYOF2WL8UY

Verify that those are broken, then use debugger to find new values (if there are any).

- [x] camera calibration function( switch between camera landscape, camera neutral and so on) 
- [x] lens correction toggle button
- [x] Basic Auto Tone

**Comment by mathieucarbou** [comment]
Hi @rsjaffe,

I have opened a PR: https://github.com/rsjaffe/MIDI2LR/pull/382

So camera calibration and basic auto tone are now subject to the same issue I had when applying PointCurve: they need to be applied asynchronously through `applyDevelopPreset`

**Comment by mathieucarbou** [comment]
lense correction is working.
