### ISSUE TITLE
Add missing notifications

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#388]
Hello!
Normally, MIDI2LR send the activity notification to the screen for all actions.

But for some actions, no notifications appeared, which is not useful.

The actions which don't send notifications:
- Copy settings
- Lens profile enable/disable
- Chromatic aberration removal enable/disable
- Upright (all commands)

Maybe more.

BTW, most of these actions are works like switches (set be the first button's press, remove by a second). Is it possible to send notification which will inform which action has been executed exactly (as it made for color labels, for example)?

See: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/midi2lr/YQWq8FvL-zU/r-Bjn3VmAgAJ

**Comment by rsjaffe** [comment]
Yes. I can look at that when I get back. I'm traveling for the next 3 weeks.
