### ISSUE TITLE
error appears when starting LR or also after restarting MIDI2LR

### ISSUE THREAD

**Issue by Der-Canonier** [rsjaffe/MIDI2LR#39]
![screenshot_2015 10 25_13h59m32s_003_](https://cloud.githubusercontent.com/assets/15310331/10793890/0cda5e2c-7d93-11e5-9169-46cb73ba0d73.jpg)

**Comment by rsjaffe** [comment]
Odd. "File not found"? Is the MIDI2LR.exe executable in your MIDI2LR.lrplugin directory? That is where it looks for the application.

**Comment by Der-Canonier** [comment]
many thanks. I was able to solve the problem

BTW: Where is the version for 0.4.3.? The last version is still 0.4.2.
