### ISSUE TITLE
MIDI2LR option dialogue box in LR

### ISSUE THREAD

**Issue by joeldgphoto** [rsjaffe/MIDI2LR#390]
got an error

An internal error has occurred
[string "Limits.lua"]:53: attempt to index global
'ProgramPreferences' {a nil value}

**Comment by joeldgphoto** [comment]
I can't open the option box in plug-in extras

**Comment by nop25751** [comment]
Same problem here MIDI2LR v.2.0.0 LR Ver.2015.10.1 it simply hangs without showing anything and need to make a hard reset every time I try to run it. Tried to stop server with no luck. Wouldn't it be better to make this kind of adjustments directly within the app itself under options creating a dedicated button for it? My 2cents
