### ISSUE TITLE
ALT key in develop mode

### ISSUE THREAD

**Issue by Der-Canonier** [rsjaffe/MIDI2LR#40]
Is it possible for "White", "Black" or Sharpening etc. in develop mode to use the ALT key together with the slider. So far, nothing happens when I press the ALT key on the keyboard with simultaneous actuation of the sliders

**Comment by rsjaffe** [comment]
MIDI2LR is moving the slider using the function Lightroom provides, so whether LR ignores or responds to a keypress is a result of LR's design.

I'd suggest posting that as a bug to the Lightroom team.

**Comment by Der-Canonier** [comment]
in LR (using the mouse or the Wacom tablet) works the key combination i.e. 
![screenshot_2015 10 29_09h39m09s_009_](https://cloud.githubusercontent.com/assets/15310331/10813670/fb81f926-7e20-11e5-95f2-d55946369d37.jpg)

ALT + white or black slider as normal black or white image with up to clipping indicator.

If I use the slider with MIDI2LR and simultaneously press the ALT key, nothing happens. It appears no black or white image. And accordingly, no clipping indicator

**Comment by rsjaffe** [comment]
It's a Lightroom bug.
