### ISSUE TITLE
Small adjustment increemnts in Lightroom history

### ISSUE THREAD

**Issue by mu5ia** [rsjaffe/MIDI2LR#400]
When I am making one exposure adjustment it's all showing up in Lightroom history as many 0.08 steps. Is it normal? I am pretty sure before while making those adjustments in the same 0.08 increment, it would show up s one step in history. 
I have a feeling that clogged image editing history it's not helping me with already slow Lightroom ):
Thanks!
![screen shot 2017-11-09 at 1 34 16 pm](https://user-images.githubusercontent.com/33527545/32625756-be4a7792-c552-11e7-9538-f01ec924f132.png)

**Comment by mu5ia** [comment]
@rsjaffe is there a thread about it?

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.
