### ISSUE TITLE
Error with Lr Classic CC in Spanish

### ISSUE THREAD

**Issue by pulse1981** [rsjaffe/MIDI2LR#402]
There is a problem with this plugin. Only a few commands work with this version. Im using Adoble Lightroom Classic CC in spanish. If i put it on English and all commands work fine but not in spanish. I can only see this with this version of LR. If use LR CC (2015) works fine in spanish to...

Any solution?

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.

The forum has a large announcement about this issue. Read more there.
