### ISSUE TITLE
Some commands not working on Lightroom Classic

### ISSUE THREAD

**Issue by Endo03** [rsjaffe/MIDI2LR#406]
Hi, i'm using MIDI2LR with a Korg nano Kontrol2, but since i've updated to lightroom classic i can no more control exposure and contrast controls. i've tried assigning different wheels/faders but nothing works. Any hint? Thank you!

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.
