### ISSUE TITLE
Meaning of previous and next profile

### ISSUE THREAD

**Issue by Der-Canonier** [rsjaffe/MIDI2LR#41]
![screenshot_2015 10 28_16h50m22s_007_](https://cloud.githubusercontent.com/assets/15310331/10794260/67c20938-7d94-11e5-8b17-6e34709049fc.jpg)

what does "Previous and Next Profile" means and how can I use it? Or do I have to enter the name of the profile somewhere?
It is so possible to select another preset in Midi Controller (as it were a 2nd level)

**Comment by Mei-Lewis** [comment]
A 'profile' is a set of control mappings. Each profile corresponds to a .xml file that stores it.

When you start using MIDI2LR it creates a file default.xml in its own directory and stores the control mappings you save in there.

If you click 'Save' and choose a new filename, say alternative.xml you now have two profiles, corresponding to the two .xml files (default.xml and alternative.xml). You can move between them with the commands in your screenshot.


I have two profiles currently, one with basic controls such as exposure and contrast, and another with more detailed stuff like split toning and lens correction. I use the TRACK<> buttons on my nanoKONTROL2 to switch between profiles.

**Comment by krakozavr** [comment]
If I understand you properly, this is a wat to have multiple layouts as cheap devices like Behringer X-Touch Mini or Korg Nano-Control? And it should work similar with "presets" at "big" devices like BCF2000?

**Comment by Mei-Lewis** [comment]
I think so yes.

**Comment by Mei-Lewis** [comment]
[mei midi2lr.zip](https://github.com/rsjaffe/MIDI2LR/files/73198/mei.midi2lr.zip)
![midi2lrsetting](https://cloud.githubusercontent.com/assets/15857139/12019131/3a8713aa-ad64-11e5-950d-164f4e457f3f.jpg)

My settings with the latest version fwif.
