### ISSUE TITLE
Send repeated "button" messages with continuous control

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#410]
For example, _next_ when rotating clockwise, _previous_ counterclockwise. Probably will enact in application so that application can keep control in centered position and avoid bottoming out--but this will cause problems with faders.

Some would be sending keystrokes (these should be constrained to develop module):

- Brush size up/down; spot size up/down: ] and [
- Brush feathering up/down shift ] and shift [
- Increase/decrease slider value: + and -

**Comment by joshuawagner** [comment]
Thanks for addressing my suggestion! I would find use in having the keystrokes in Library mode also. An example would be to use an encoder to adjust thumbnail size with - and =.  Maybe that's not what you meant when you said "constrained to develop module."
