### ISSUE TITLE
Move corner for crop

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#413]
Will require sending both side and bottom/top commands. Need to figure out how to do differential commands, as the side and bottom/top could be at different numeric values.

**Comment by TheNotoriousGit** [comment]
(Let me know if I should put this in a new issue, separated from this one)

One thing I would like to add is that it would also be nice to be able to move the crop rectangle / field of view. I know that I could use the offset in the "Transform" panel but then the changes don't show in the crop panel which might lead to forgetting that I changed it.
