### ISSUE TITLE
Support of non-MIDI controllers. #Enhancement

### ISSUE THREAD

**Issue by abrilevskiy** [rsjaffe/MIDI2LR#416]
Dear @rsjaffe ,

Do you mind to enhance MIDI2Lr with support of non MIDI controller for example Contour Design Shuttle Pro v2?
I received an Contour Design Shuttle Pro v2 SDK (C++) and can contribute, but I am not so much C++ experience and need some guidance in Architecture to start.

**Comment by rsjaffe** [comment]
The only way this would be done is if you did all the work. Without the hardware to test this (and the time to do so), I don't do any non-midi controller development. You are welcome to contribute a pull request once you have this working.
