### ISSUE TITLE
Support for modifiers (key combination) #Enhancement

### ISSUE THREAD

**Issue by abrilevskiy** [rsjaffe/MIDI2LR#417]
It will be nice to have support of modifiers (key combination):

1. Press two or more button in same time - separate "virtual" button
2. Press one or more button and rotate knob in same time - separate "virtual" knob

**Comment by rsjaffe** [comment]
That's what profiles are for.

**Comment by andreipopovici** [comment]
It would be great to have momentary-switch profile support (i.e. a knob responds differently if turned while a drum pad or note is pressed or "on"), instead of needing to toggle between profiles.

Is that something that could be configured using the existing options, or would it fall under "new feature request"?

**Comment by rsjaffe** [comment]
That would be a new feature request.

**Comment by andreipopovici** [comment]
Thank you! For context, here's how I'm using this feature in Capture One (via Bome MIDI Translator):

I have three relative-mode knobs set to Hue, Saturation and Lightness. Then, I use a momentary press on one of three drum pads to make each knob control the H, S or L for either shadows, midtones or highlights, only while the respective drum pad is pressed.

In MIDI2LR, it could work by temporarily activating a specific profile on "Note On" and reverting to the first or default profile on "Note Off", in addition to the current mode, which only enables a profile on "Note On".

**Comment by D-Noc** [comment]
I think this is an excellent idea.
It would make it possible to have the Basic profile selected, and then, while pressing a button, the profile would switch to e.g. the Details profile. Releasing the button would switch back to the Basic profile.
Only caveat I can think of is that the pressed button cannot be assigned to do something else in the Details profile.
Perhaps this Feature Request ties in with https://github.com/rsjaffe/MIDI2LR/issues/463 ??

**Comment by rsjaffe** [comment]
I like the temporary profile idea. That's relatively easy to implement within the current framework of the program.

**Comment by tss68nl** [comment]
I was about to leave a similar feature request so instead I support this motion :) Please include this feature in Midi2LR.

I think it's easily possible to assign another function to the same button in the 'details' profile, as Note-start will trigger the details profile, while Note-end will trigger the return to the previous profile. Note-start can be attached to something entirely different in the details profile, should you also be able to choose the details profile with a permanent switch.

This enables you to quickly jump into HSL mode for some luminance adjustments, while the same modifier will work differently when you permanently switch to HSL mode, for example by letting you adjust the Hue's under the same modifier.

This feature would make Midi2LR so much more powerful.... can't wait!

**Comment by tpj2018** [comment]
Perhaps you can use bome to send a note on and off when pressed down which selects a different profile.
Then on release bome sends a different note on/off which then selects the previous profile.
Not ideal as you need to add bome to midi2lr, but this could perhaps work.
