### ISSUE TITLE
Saving Profile

### ISSUE THREAD

**Issue by stabone76** [rsjaffe/MIDI2LR#419]
Why wont it let me save my profiles to my midi2lr account or Lightroom account, whichever it is.  The folder it would save to is:  C:\Program Files\Adobe\Adobe Lightroom Classic CC\MIDIprofiles...... I also tried doing it to the parent folder (without the MIDIprofiles folder).  Nothing will save.  I tried saving it as AAA, 1, aaa1, aaa1main, main, and even added the .xml file after the name it keeps saying UNABLE TO SAVE FILE AS SPECIFIED.  PLEASE TRY AGAIN AND CONSIDER SAVING TO A DIFFERENT LOCATION.  

None of that has worked, I even tried folders ALL OVER my computer... nothing worked.

#The Github issues section is closed.

Post any comments, questions, bug reports, etc., at our new google groups discussion page: https://groups.google.com/forum/#!forum/midi2lr . **Do not post here.**

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.
