### ISSUE TITLE
v4.2 temperature dial unusable

### ISSUE THREAD

**Issue by wockawocka** [rsjaffe/MIDI2LR#42]
Hi there!

I installed v4.2 and have noticed whenever I change the temp setting it defaults to a minimum level. I can't dial any different settings in. If I move the actual control in the lightroom gui it moves the slider accordingly, but I can't do it the other way.

**Comment by rsjaffe** [comment]
I've removed the special handling for the temp setting. It should now function as any other control. We'll work on improving the handling of wide-range controls such as temperature in future releases.

**Comment by rsjaffe** [comment]
See #44
