### ISSUE TITLE
All Settings Reset with Preset Buttons

### ISSUE THREAD

**Issue by stevejmu** [rsjaffe/MIDI2LR#425]
When I assign a preset to a button, every setting is reset except for the adjustment assigned in the preset. For example, let's say I have a preset that sets the Exposure to 1.00 and I have all kinds of other settings made to the photo such as Profile, Calibration (Version 3 for an older picture), Lens profile correction, white balance, shadows, etc. If I assign that preset to a button and use it in my workflow, then all the other settings are reset and the Exposure is set to 1.00 (and the Calibration is updated to Version 4).

However, if I click this same Preset in Lightroom, only the Exposure setting is changed to 1.00 and all the other settings stay the same, which is the expected behavior.

**Edited to Add:**
Lightroom presets are now .XMP files. I'm not sure when this changed, but I wonder if MIDI2LR is still reading them as .LRTEMPLATE files.

Lightroom CC Classic 7.3 Release, Camera Raw 10.3
PC / Windows 7 Pro
MIDI2LR 2.7.0.4

**Comment by thomasmadel** [comment]
I got the same problem on a Windows 10 PC. If I click the presets with the mouse, only the parameters which were chosen in the preset change. If I use the same preset with MIDI2LR all other parameter were set to zero.
The same presets work fine on my Macbook with the newest Version of Lightroom and MIDI2LR.

**Comment by rsjaffe** [comment]
It's a Lightroom bug: https://feedback.photoshop.com/photoshop_family/topics/lr-classic-7-3-resets-settings-when-develop-preset-is-applied-via-script
