### ISSUE TITLE
LR copy and paste settings in Develop module does not work

### ISSUE THREAD

**Issue by xrb17** [rsjaffe/MIDI2LR#426]
#The Github issues section is closed.

Post any comments, questions, bug reports, etc., at our new google groups discussion page: https://groups.google.com/forum/#!forum/midi2lr . **Do not post here.**

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.
