### ISSUE TITLE
MIDI2LR fails when reloading

### ISSUE THREAD

**Issue by BenLim88** [rsjaffe/MIDI2LR#433]
I have installed the MIDI2LR and runs perfectly with my BCF2000. However, everytime when I close and reopen lightroom, MIDI2LR stops responding and just give me a white screen in the app.

I have tried installing it in various folders, but the problem keeps repeating. The only way is to completely uninstall and reinstall everytime I want to use it. 

Any idea what is happening?

**Comment by rsjaffe** [comment]
For support, please use https://groups.google.com/forum/#!forum/midi2lr .
