### ISSUE TITLE
Internal error ClientUtilities.lua49: Table index is nill

### ISSUE THREAD

**Issue by boontje12** [rsjaffe/MIDI2LR#435]
**Describe the bug**
After installing the updated version of Midi2lr Today (after getting a pop up in LR, I know get the Internal error message: ClientUtilities.lua49: Table index is nill After selecting the folder where the plugin is installed in.

**To Reproduce**
1. Go to '...' Add Plugin
2. Click on '....' The selected folder where the plugin is installed in
3. Scroll down to '....' Enter

**Expected behavior**
Don't get the error message, but get the workable plugin in Lr. Now ahving to work with manual editing in LR till this is solved..
**Screenshots**
![image](https://user-images.githubusercontent.com/48644331/54488345-f2faca00-48a0-11e9-9b7f-bdd748b04aa5.png)

**System(please complete the following information):**
 - OS: [e.g. MacOS Mojave] Windows 10
 - Lightroom version 6CC
 - MIDI2LR version 3.0.1.0

**Additional context**

**Comment by NKame** [comment]
Same here,
Windows 10
Photoshop Lightroom version 6
MIDI2LR version 3.0.1.0

**Comment by rsjaffe** [comment]
One new command isn't support in LR versions before 6.6. If you could test a fix, unzip the files in the dropbox link below, and place them in your MIDI2LR.lrplugin directory to replace *ClientUtilities.lua*, *Client.lua*, and *Utilities.lua*. I believe it will fix the issue, and I will put it in for the next bug-fix release.

https://www.dropbox.com/s/865unhmcxvxhy67/Client.zip?dl=0

**Comment by rsjaffe** [comment]
Fixed in version 3.0.2.0
