### ISSUE TITLE
Application ended unexpectedly when closing LR 6.14

### ISSUE THREAD

**Issue by phalicki** [rsjaffe/MIDI2LR#437]
**Describe the bug**
When closing Lightroom with MIDI2LR still running I'm receiving the error message "Application quit unexpectedly". Happens every time and only when MIDI2LR is running - if I close it before closing Lightroom, everything is fine.

**To Reproduce**
1. Start Lightroom
2. Wait for MIDI2LR to open and connect with Midi device and Lightroom
3. Close Lightroom

**Expected behavior**
Closing Lightroom will gently close MIDI2LR - no crash/error message.

**Screenshot**
Attached. In Polish, but shouldn't matter too much as it's a pretty generic error. Attached crash report may tell more.
![Error](https://user-images.githubusercontent.com/18087829/55200970-171faa80-51c1-11e9-8419-b0233bd3f9e6.png)
[crash_report.txt](https://github.com/rsjaffe/MIDI2LR/files/3020608/crash_report.txt)

**System**
 - OS: OSX 10.12.6
 - Lightroom 6.14
 - MIDI2LR 3.0.2.0

**Comment by rsjaffe** [comment]
Yes, I think I've fixed this in the upcoming release. In some circumstances, MIDI2LR app gets two **close** signals instead of one, and tries to close twice.

Release 3.1 is planned for May.

**Comment by phalicki** [comment]
Cool, no worries then. Thanks
