### ISSUE TITLE
Copy and paste LR settings not working

### ISSUE THREAD

**Issue by goanheat** [rsjaffe/MIDI2LR#438]
When mapped to a button it should copy and paste the settings. (It did work one time only when I first set it up)
Nothing changes
Steps to reproduce the behavior: I have remapped several different buttons with the same results.
System information
Mac OS Mojave 10.14.4
MIDI2LR version: 3.0.2.0
Lightroom version: CC
Controller: Behringer Xtouch mini

**Comment by rsjaffe** [comment]
Try version 3.1.0.4
