### ISSUE TITLE
Release v0.4.3 out

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#44]
[See wiki for full list of commands](https://github.com/rsjaffe/MIDI2LR/wiki). Copy/Paste settings unfortunately not yet implemented. Have to debug the LUA code for that.

Temperature parameter handling now normal, as specialized handling was creating bugs for some people. Will work on improving wide-range parameters such as temperature in future releases.

**Comment by Clueless2015** [comment]
Sorry to sound silly but where is 0.4.3 to download?  I can only find compiled files for 0.4.2 and the 'latest' download link is also 0.4.2.

Thanks

**Comment by Der-Canonier** [comment]
where did you find the files? When I click on the lastest release, I only find version 0.4.2

![screenshot_2015 11 01_12h11m51s_012_](https://cloud.githubusercontent.com/assets/15310331/10868593/52b7d1e8-8092-11e5-8c0f-3824578a7845.jpg)

**Comment by Der-Canonier** [comment]
and I have no chance to start MIDI2LR - no connection to LR

![screenshot_2015 11 01_12h21m56s_013_](https://cloud.githubusercontent.com/assets/15310331/10868625/50866668-8093-11e5-88e0-37cdc1aa500a.jpg)

**Comment by Clueless2015** [comment]
Latest version is here : https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.4.3

**Comment by Der-Canonier** [comment]
Thanks

**Comment by rsjaffe** [comment]
Sorry, github somehow mislabelled the latest release. I've now edited it and version 0.4.3.1 is shown (I had to add the .1 to make it the latest release--it's the same as 0.4.3)

**Comment by DavidWeaverPhoto** [comment]
The compressed files for MAC and WIN:
https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.4.3.1

**Comment by rojmagd** [comment]
Everything runs perfect. I only miss the copy and paste options for having a perfect workflow.

Thank you very much for you work.

**Comment by Clueless2015** [comment]
Just going to echo the above, really is working very well with all the additional functions and improvements.  Thank you, definitely enjoy your drink tokens :) 

Looking forward to future development and see what that brings!
