### ISSUE TITLE
Consistent Crash When Exiting Lightroom

### ISSUE THREAD

**Issue by greycubesgav** [rsjaffe/MIDI2LR#440]
**Describe the bug**
Every time I close Lightroom I get a "MIDI2LR quit unexpectedly" error.

**To Reproduce**
1. Open Lightroom
2. MIDI2LR opens
3. Navigate Lightroom, with or without using Midi2LR
4. Exit Lightroom
5. "MIDI2LR quit unexpectedly" error.

**Expected behavior**
MIDI2LR exits with no errors.

**Screenshots**
![Screenshot 2019-04-24 at 19 40 19](https://user-images.githubusercontent.com/3426859/56677276-d84e1900-66c8-11e9-8ee3-6029e69774a2.png)

**System(please complete the following information):**
 - OS: MacOS Mojave 10.13.0
 - Lightroom version: 8.2.1 [1206193]
 - MIDI2LR version: 3.0.20

**Additional context**
Full MacOS error text.
[MIDI2LR.error.txt](https://github.com/rsjaffe/MIDI2LR/files/3113339/MIDI2LR.error.txt)

**Comment by rsjaffe** [comment]
Issue fixed with 3.1.0.1
