### ISSUE TITLE
Local adjustments: Density

### ISSUE THREAD

**Issue by LR234234** [rsjaffe/MIDI2LR#441]
Hi, 

I think, it is not possible to assign density (at least this is what it is called in the german edition) in the local adjustments on one of the keys. Would be very helpful in my opinion!

Thanks!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rsjaffe** [comment]
This control is not documented in the Lightroom API and is not assigned to a keyboard shortcut. I know of no way of controlling it. Sorry.
