### ISSUE TITLE
Error with any button on the Behringer X-Touch Mini

### ISSUE THREAD

**Issue by eranknafo2001** [rsjaffe/MIDI2LR#442]
**Describe the bug**
I have a Behringer X-Touch Mini and when I start to configure the commands, it crash and show this error
![image](https://user-images.githubusercontent.com/13423155/57367312-747c2380-7191-11e9-8813-677fe67f5d68.png)
 
**To Reproduce**
1. Go to 'MIDI2LR MIDI command To LR command Table'
2. Click on 'Any button on the Behringer X-Touch Mini'
![image](https://user-images.githubusercontent.com/13423155/57367312-747c2380-7191-11e9-8813-677fe67f5d68.png)

**Expected behavior**
it should show the Midi command and let me assign the LR command.

**Screenshots**
![image](https://user-images.githubusercontent.com/13423155/57367312-747c2380-7191-11e9-8813-677fe67f5d68.png) 

**System(please complete the following information):**
 - OS: Windows 10
 - Lightroom version: 8.2.1 release
 - MIDI2LR version: 3.1.0.1

**Comment by rsjaffe** [comment]
Try release 3.1.0.4.
