### ISSUE TITLE
Grating of the controllers

### ISSUE THREAD

**Issue by LR234234** [rsjaffe/MIDI2LR#443]
Is there any possibilit to define the grating of the controllers? For example, the steps for temperature are by far to large when using the X-touch mini with Lightroom to be actually usable.

Thanks for answers!

**Comment by D-Noc** [comment]
You can set the lower and upper limits for Temperature, Tint and Exposure in MIDI2LR options.
From Lightroom: File -> Plug-In Extras -> MIDI2LR Options.
Then select the Other.. tab.
When you set limits, the steps will be adjusted to fit the range between lower and upper limits.

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.

**Comment by LR234234** [comment]
Hey D-Noc! Thanks for your help. This is exactly what I would like to do. However, if I open File -> Plug-In Extras -> MIDI2LR Options -> Others I see the following:
![grafik](https://user-images.githubusercontent.com/50400559/58113448-cdb66f00-7bf5-11e9-8d34-31be0b003a74.png)
Actually, I don't see how to set the limits here.

Could you help me again? Thanks!

**Comment by D-Noc** [comment]
![image](https://user-images.githubusercontent.com/50765320/58120594-d9119680-7c05-11e9-83d2-83df3564f5bf.png)

Weird.. it looks like you are missing this entire region, above the horizontal separator..
Are you running the latest version?

**Comment by LR234234** [comment]
I am running 3.1.0.4 but the controllers of your screenshot are not shown in my version. What a pity...
Might there be any solution?! A friend of mine seems to have the same problem.

**Comment by rsjaffe** [comment]
The controllers only show when you are in Develop mode
 And a picture is selected. That’s the only way to detect what limits are possible.
