### ISSUE TITLE
Midi2LR crashes on any use of Keyboard Shortcuts for User

### ISSUE THREAD

**Issue by jimvetter** [rsjaffe/MIDI2LR#444]
**Describe the bug**
midi2lr crashes Lightroom 8.3 when my controller requests to execute any Keyboard Shortcuts assigned in the midi2lr mapping window. It is ONLY the keyboard shortcuts that cause the crash as far as I can tell. The buttons assigned to other lightroom commands work fine. I've tried various keyboard shortcuts - including shortcuts with no key assigned to them in the midi2lr Options window - they all cause a crash.

I have tested this problem with the previous version of LR 8.2.1 and the error does NOT occur. This seems to be an issue with LR8.3

**To Reproduce**
1. Assign any keyboard shortcut to any button on the controller.
2. Press the button
3. See the error: "MIDI2LR quit unexpectedly." "Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple."

**Expected behavior**
Normal behavior is that LR would execute the command as if I typed it on the keyboard.

**System(please complete the following information):**
 - OS: Mac OS High Sierra 10.13.6
 - Lightroom version 8.3
 - MIDI2LR version 3.0.2.0
 - Behringer BCR2000 controller

**Additional context**
This issue only began recently. Perhaps with the update to LR 8.3. I've never had this issue before.

**Comment by rsjaffe** [comment]
Fixed with release 3.1.0.4
