### ISSUE TITLE
Option to automaticaly switch knobs for basic exposure to filter exposure when filter panel open

### ISSUE THREAD

**Issue by leonlazic** [rsjaffe/MIDI2LR#448]
**Is your feature request related to a problem? Please describe.**
I would really love if there would be an option, so that MIDI2LR automatically switches the knob of the basic picture exposure to the filter exposure slider when the filter panel is open. Because otherwise you either have the knob set for the basic exposure or filter exposure and you have to adjust the other one with the mouse. You could have a separate knob just for the filter exposure but that would be a waste of a knob in my opinion since the filter panel only gets used so much. 
If you decide to implement this feature, of course implement it for all of the filter settings. 👍 

Best Regards Leon

**Comment by rsjaffe** [comment]
That's already in place. Look at the [Profiles](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#profiles) options. You can have MIDI2LR switch control mapping for any of the listed tools and panels offered in the dialog. If you have questions about using Profiles, please use the [MIDI2LR group(https://groups.google.com/forum/#!forum/midi2lr).
