### ISSUE TITLE
Assertion failed: err == noErr

### ISSUE THREAD

**Issue by mischnic** [rsjaffe/MIDI2LR#45]
This occurs on my mac every time the MIDI2LR application tries to start.
Version 0.4.3

![bildschirmfoto 2015-11-01 um 22 37 48](https://cloud.githubusercontent.com/assets/4586894/10871500/329e3332-80e9-11e5-99e3-c2f35f66b732.png)

**Comment by rsjaffe** [comment]
Is there anyone else with a Mac that can verify this is a problem? Also, have you tried starting MIDI2LR.app directly instead of letting it start from the Lightroom plugin?

**Comment by mischnic** [comment]
I know what the problem is: MIDI2LR.app is compiled for 10.11, I have 10.10. Maybe you could add that to the downloads page or compile it for an earlier OSX version?

**Comment by rsjaffe** [comment]
Aha! I'm not familiar with Macs and didn't realize that I'd have to make sure it compiled for a given OS version. Next time I get my hands on a Mac I’ll recompile for an earlier version. It'll be a few days.

**Comment by rsjaffe** [comment]
See current release for 10.10 version

**Comment by mischnic** [comment]
Thanks!
