### ISSUE TITLE
Switching profiles automatically when tool selected doesn't work

### ISSUE THREAD

**Issue by leonlazic** [rsjaffe/MIDI2LR#450]
About a week ago I said that I would like to have a setting, that automatically switches between the Basic Exposure and Local Exposure slider when the Filter Panel is opened. I am sorry that I didn't look in the forums first because there was already a solution. As you wrote back, the trick is to set a specific profile for local adjustments and assign it in the midi2lr options window.
BUT I have problems with this technique. I made the profiles, stored them into a folder and made that folder the profile folder in the Midi2lr settings. So I have a: 
- Develop Profile.xml
- Filter Profile.xml (This is for graduated filters and radial filters. Just changed the basic adjustments to local adjustments.)

The problem is that only the first switch of profiles works. I rotate the encoder and the basic exposure slider moves as expected. Then I open a Graduated Filter panel and the profile automatically switches, so when I rotate the same encoder again, the local exposure slider moves, also expected. The problem arises when I close the Graduated Filter panel. The profile should change back to my develop profile and the basic exposure slider should move, but it doesn't.
One more problem I figured out trying to solve this, is that if I stop the server and star it again the Midi2lr doesn't even make the first switch of profiles, from develop to filter profile. Instead I musti select once more the same profile folder I already head in settings.

 - OS:MacOS Mojave
 - Lightroom 8.3.1
 - MIDI2LR version

**Comment by rsjaffe** [comment]
The wiki explains this behavior: https://github.com/rsjaffe/MIDI2LR/wiki/Profiles#cautions .

> The application cannot guess when you are finished with the specialized profile. The best way to manage this is, if you are using specialized profiles, to assign the general develop module to all the develop panels and tools that don't have special profiles. That way, when you switch panels or switch tools, the general profile gets loaded. Don't worry about repetitive loading of the same profile: the program keeps track of the active profile file name, and won't reload it unless necessary.

I do admit it's a bit counterintuitive, and I'm going to revamp the code (not for this release, as the change needs further testing) so that you no longer have to assign the general profile to all the develop panels and tools.

**Comment by rsjaffe** [comment]
And Lightroom won't tell MIDI2LR which panel is open in the Develop module, so that first switch has to be manual by the user. I have a workaround when the user, in MIDI2LR, manipulates a control in the panel or opens the panel in MIDI2LR, but not when first opening Lightroom.

**Comment by leonlazic** [comment]
OK. It helped setting all of the other panel and module profiles to my default develop profile.xml. And I still have to move the slider manually the first time Lightroom opens, but after that midi2lr makes the switching automatically exactly like I wanted.
Thanks
