### ISSUE TITLE
Map CC to rating

### ISSUE THREAD

**Issue by rossburton** [rsjaffe/MIDI2LR#451]
Would it be possible to map a CC command to the rating, so by turning a dial I can move from 0 stars to 5 stars?  My intention is to stop using six buttons for the star rating.  I can see explicit 0-5 stars, and increase/decrease, but no 'map this dial'.

**Comment by rsjaffe** [comment]
Yes, I can add that pretty easily to the next release. In the meantime, you can do something similar by using the **Key 32 – Key 31** command (Turning knob clockwise sends Key32 signals to Lightroom, counterclockwise Key31. Not suitable for controls with hard stops like faders. ). 

Place **]** in Key 32 for _increase rating_ and **[** in Key 31 for _decrease rating_.

It's not quite the same as what I can do in the next release, as there's a direct API for increasing and decreasing rating, but it should work similarly.

**Comment by rossburton** [comment]
Confirmed that the key 32-31 trick works, but looking forward to a proper fix. Thanks!
