### ISSUE TITLE
Problem with assigning \ in develop module for before/after preview with x-touch mini

### ISSUE THREAD

**Issue by ThiaJay** [rsjaffe/MIDI2LR#453]
I am pretty sure that this used to work. However, now I find that I cannot use the key I assigned on my x-touch mini to toggle between before and after previews in the develop module. If I press the key on my keyboard it works but does not function when using the midi controller.

I have gone into 'Set Midi2LR Options' within Lightroom and chosen the 'Other' tab. Within the interface, \ is set to key 14. When I got into the button to key assignment screen, this corresponds and I can see the button triggering in your application. However, going back into Lightroom, it does not behave as expected and does not provide a before/after preview.

Also, if I close the application and start up, it does not load the configuration that I saved and goes back to assigning key 1 to this button.

https://i.imgur.com/Taxjlk1.png
https://i.imgur.com/5Hzfhck.png

Windows 10 64 bit
Adobe Photoshop Lightroom Classic 8.3.1
Midi2LR 3.2.3.0

**Comment by cccgi** [comment]
Same issue on Mac with Before/After using the '\' key.

In addition, LR Copy Settings & LR Paste Settings stopped working as well. I tried assigning keyboard shortcuts but that didn't work either.

**Comment by bam2000** [comment]
I can confirm that, both function doesn't work on a Mac with Lightroom Classic CC 8.4

**Comment by rsjaffe** [comment]
now have backslash alternative to fix this. closed
