### ISSUE TITLE
Lightroom unresponsive

### ISSUE THREAD

**Issue by Rory-A** [rsjaffe/MIDI2LR#454]
Since installing and setting up MIDI2LR Lightroom has become unresponsive to certain commands and generally sluggish. I'm running this on the 2018 top spec macbook pro 15inch and normally it handles Lightroom easily. It starts off fine, but, after 10-15 minutes of use I run into the following issues:

- I am unable to change photo whilst in develop mode. 
- I am also unable to undo actions.
- When I go from develop mode back into the library view, I don't see the changes to the photo, that I just made; it appears unedited.
- When I try to develop another photo, the photo doesn't show up, only the background grey screen.
- Right-clicking on a photo does nothing

I also have to force quit Lightroom every time now. I usually lose any changes I made to photos at this point as well.

**Comment by rsjaffe** [comment]
See Known Issue number 3 (https://github.com/rsjaffe/MIDI2LR/wiki#faqknown-issues) and see if that fixes it. If not, please post your issue on the MIDI2LR discussion group with the information requested at https://github.com/rsjaffe/MIDI2LR/wiki#support.
