### ISSUE TITLE
List of known compatible and incompatible controllers is gone

### ISSUE THREAD

**Issue by MortenHannemose** [rsjaffe/MIDI2LR#457]
When I open the list of known compatible and incompatible controllers is at https://goo.gl/Ev6S8R the columns only contain the letters a,b,c but no information about controllers.

Maybe someone has vandalized the page?

**Comment by rsjaffe** [comment]
fixed

**Comment by MortenHannemose** [comment]
Now rows 3 through 8 only contain the text "NRPN not useful for faders--they only send high 7 bits, skip low 7 (Cannot confirm this with latest firmware (1.10) and drivers (1.0.10) on Win10, NRPN works fine on motorized faders and encoder dials.)".
That seems unintentional.

**Comment by MortenHannemose** [comment]
I have now "restored" the document to 10 September, 10:42, which fixes the above mentioned problem.
