### ISSUE TITLE
Basic Install and setup

### ISSUE THREAD

**Issue by DavidWeaverPhoto** [rsjaffe/MIDI2LR#46]
Is there a place where a basic install and setup can kept?  I'm having sporadic failure issues at multiple points.  There are so many variables it would be nice if there was a set of instructions (especially sending config files to the controller via BC Manager).
Some notes and questions.
Which driver do you use?  The one that comes with WIN or the Behringer driver?
Any debugging hints/help to check communication between MIDI2LR and the BC?
Leaving LR and MIDI2LR running for a long period of unattended time seems to drop the connection even though MIDI2LR says it is connected to LR and BC Manager will test the hardware properly.
Yes, it could be this system and it's probably operator error. :-)

**Comment by rsjaffe** [comment]
If anyone can help me on this I'd appreciate it. I've started the [wiki](https://github.com/rsjaffe/MIDI2LR/wiki) for the documentation. If someone wants to write instructions, just put it in this thread and I’ll add it to the wiki. Particularly useful would be any Mac-specific info.

**Comment by Jekegraff** [comment]
I have too, a really unstable connection with my BCF2000. I try many things (drivers, port, ...) but each time i thought i had the solution, at the end it was not the case... 

Most of the time i lost connection after a massive update of the motorized faders. In fact it's just the inputs from the controller that are lost, if i move a parameter in lightroom, or change the photo the faders are still moving...

I don't know if i miss something in the setup (a checklist could be cool for that even i found some clue around the net), or maybe it's the driver on windows 10 that are the source of the problem (i didn't use a lot midi2lr on 7 before i migrate but i don't remember the same issues )

Any clues?

Thank's!

**Comment by DavidWeaverPhoto** [comment]
When people like me leave feedback / request help it is helpful to  state version of MIDI2LR, Version of Win/Mac and LR version.  As a weird example, when I upgraded from LR2015.2 to 2015.3 communication came back.  I'm in MIDI2LR 0.4.3 under Win8.1 Pro.  I'm using a BCF2000 with no other midi devices attached.

**Comment by Jekegraff** [comment]
I knew i was forgetting something! X )

It append on MIDI2LR 0.4.2 & 0.4.3 with LR6.2 & 6.3 on w10 family with the BCF2000.

I have maybe a track, i tweaked the global setups with BC manager, changing the transmission interval from 20 to 2. It seems to be more stable for now, but i have to test it more to be sure.

**Comment by rsjaffe** [comment]
Yes--there are significant interactions between the MIDI controller setup
and the quality of the user experience. I've put a standard setup for
channel two of the BCF2000 in the plugin directory. You can load that with
BC manager and see if it improves things.

**Comment by StevenKersting** [comment]
Video of setup and use w/ LR CC on El Captain.

https://youtu.be/uywZXCuqe0c
