### ISSUE TITLE
Error in 3.3.2.0 Mac (DMG) installer

### ISSUE THREAD

**Issue by boiing** [rsjaffe/MIDI2LR#461]
**Describe the bug**

The latest installer release contains an error, see this thread: https://groups.google.com/forum/#!topic/midi2lr/wXXVdtrSfOU (the MIDI2LR.app is contained in another MIDI2LR.app package). This causes the MIDI2LR app to not start automatically when LR starts. Previous installers do not have this problem.

**Comment by randomeizer** [comment]
Yeah, came across this also. The workaround is to move the internal app back up to the lrplugin folder manually.

**Comment by boiing** [comment]
True, found that out also but in that case an assigned keyboard shortcut crashes MIDI2LR. I don't know if that is related to this, but reverting to 3.3.1.0 solves both problems.

**Comment by rsjaffe** [comment]
I think it's fixed. Please download and test: https://github.com/rsjaffe/MIDI2LR/releases/tag/v3.3.2.0

**Comment by boiing** [comment]
Fixed! Many thanks. Keyboard shortcut crash still present in 3.3.2.0, so not related to the installer issue.
