### ISSUE TITLE
Midi2LRNot connected to Lightroom

### ISSUE THREAD

**Issue by pixelwiz** [rsjaffe/MIDI2LR#462]
**Describe the bug**
Hi, I recently updated my Midi2LR to the latest version (3.3.2.0) as well as Lightroom Classic (9.0 release,  ). Not it shows a message - Not Connected to Lightroom

Lightroom Classic version: 9.0 [ 201910151439-b660523e ]
License: Creative Cloud
Language setting: en
Operating system: Windows 10 - Business Edition
Version: 10.0.18362
Application architecture: x64
System architecture: x64
Logical processor count: 8
Processor speed: 4.0 GHz
Built-in memory: 16324.3 MB
Real memory available to Lightroom: 16324.3 MB
Real memory used by Lightroom: 5412.4 MB (33.1%)
Virtual memory used by Lightroom: 6644.3 MB
GDI objects count: 843
USER objects count: 2888
Process handles count: 3696
Memory cache size: 1803.7MB
Internal Camera Raw version: 12.0 [ 321 ]
Maximum thread count used by Camera Raw: 5
Camera Raw SIMD optimization: SSE2,AVX,AVX2
Camera Raw virtual memory: 2321MB / 8162MB (28%)
Camera Raw real memory: 2323MB / 16324MB (14%)
System DPI setting: 96 DPI
Desktop composition enabled: Yes
Displays: 1) 1920x1200, 2) 2560x1440
Input types: Multitouch: No, Integrated touch: No, Integrated pen: No, External touch: No, External pen: No, Keyboard: No

Graphics Processor Info: 
DirectX: NVIDIA GeForce GTX 1070 (23.21.13.8813)

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) .
