### ISSUE TITLE
selecting a slider

### ISSUE THREAD

**Issue by thorodt** [rsjaffe/MIDI2LR#463]
I need to select the main sliders of lightroom:  exposure, hightlights, shadows, blacks and more of basic and curves.

there is no way to just select them by a shortcut button, I just have to select them by mouse click one by one and them use a wheel to move the selected slide.

with this option,  we could use one big slide to move all the sliders, switching between them by selecting the buttons of the midi.

**Comment by rsjaffe** [comment]
no action planned
