### ISSUE TITLE
MIDI2LR does not recognize relative encoder positions anymore

### ISSUE THREAD

**Issue by TheDude-hr** [rsjaffe/MIDI2LR#464]
Original HuFux issue : #460 

Hi rsjaffe,

**Describe the bug**

Same problem with the same Arturia Beatstep controller .

The rotary knobs no longer pick up the parameters of each individual picture after switching between the pictures, but instead continue on the new picture with the value from the previous picture. Therefore there are sudden parameter jumps when rotating the knob the first time on a new picture.
This bug also appear when moving setting via knob, then mouse, then knob again. The value jump from "last knob" set value.

I confirm that this bug seems to be introduced with version 3.3.2.0. Everything is working fine with 3.3.1.0.
To complete HuFux post :

**To Reproduce :**

1. Arturia Beatstep knobs to "Relative 2" mode
2. Arturia Beatstep knobs acceleration to "OFF"
3. "two's complements", resolution 127 to all rotary knobs in MIDI2LR
4. Correct a setting via the knob
5. Move slider of the same setting with mouse
6. Correct the same setting via the knob

--> the setting move from value previously set by knob and not by mouse.

**Expected behavior :**

--> the setting move from value previously set by mouse.  (as in 3.3..1.0)

**System :**

Windows 10 Pro 1909 64 bit
Lightroom version 9.0
MIDI2LR version 3.3.2.0 and 3.4.2.1

**Comment by HuFux** [comment]
@rsjaffe Just tested latest version also on a different PC and it does still not work as expexted for all relative value types. Thanks @TheDude-hr for third party confirmation and re-opening. Action is definitely needed. Wirklich, das macht so keinen Spaß !

**Comment by rsjaffe** [comment]
OK, so let me repeat what I think you're saying--on the original bug report I was thinking that the report was that MIDI2LR didn't recognize relative encoders correctly. Now it seems to me the problem is that MIDI2LR ignores any updates to the Lightroom setting for that parameter, such as editing it directly in Lightroom or changing to a new picture, when using a relative encoder. Correct?

Second question: do you have "pickup" on or off?

**Comment by TheDude-hr** [comment]
1st question : Yes. Better explained like that !!!

2nd question : pickup off

tested with pickup on and same problem occurs.
- pickup on
- set temperature to  3740 via knob
- set temperature to 6800 via mouse
- moving knob to decrease temperature show "Temperature 3535 6800" with "Show status and activity" enabled

**Comment by rsjaffe** [comment]
Could you test the MIDI2LR.exe at https://www.dropbox.com/s/lyzq5az0iln2ixk/MIDI2LR.exe?dl=0 ? I think it fixes the problem. It turns out that, when cleaning up the code, I removed a side-effect that was needed in running what looked like an unnecessary function.

**Comment by rsjaffe** [comment]
See https://github.com/rsjaffe/MIDI2LR/releases/tag/v3.4.3.0

**Comment by TheDude-hr** [comment]
Fixed !!!

Many thanks rsjaffe.

**Comment by DDnepr** [comment]
> Could you test the MIDI2LR.exe at https://www.dropbox.com/s/lyzq5az0iln2ixk/MIDI2LR.exe?dl=0 ? I think it fixes the problem. It turns out that, when cleaning up the code, I removed a side-effect that was needed in running what looked like an unnecessary function.

_______________________
Hello! I experienced exactly the same problem on my MacBook Air M1 and Arturia BeatStep. Midi2LR version MIDI2LR-4.3.1.11-osx-installer.

I really need your help to solve this problem. Sorry for my english.
