### ISSUE TITLE
MIDI2LR qui unexpectedly at first launch

### ISSUE THREAD

**Issue by jbrialon** [rsjaffe/MIDI2LR#465]
**Describe the bug**
Hello, right after I installed MIDI2LR, when I launch Lightroom, MIDI2LR crashes and I get an error

**To Reproduce**
1. Launch Lightroom
2. wait 5s
3. MIDI2LR crashes and I get an error

**Expected behavior**
MIDI2LR to launch

**Screenshots**
<img width="1112" alt="Screenshot 2019-12-13 at 17 50 42" src="https://user-images.githubusercontent.com/5830909/70817094-1b343c80-1dd1-11ea-9413-36af6a12e6b4.png">

**System(please complete the following information):**
 - OS: MacOS Catalina 10.15.1
 - Lightroom version 9.1
 - MIDI2LR version 3.4.3.0

**Additional context**
[MIDI2LR.log](https://github.com/rsjaffe/MIDI2LR/files/3961807/MIDI2LR.log)

**Comment by jbrialon** [comment]
it's working with the MIDI2LR-3.3.1.0-MacOS-CATALINA release

**Comment by rsjaffe** [comment]
That information was pretty specific. Looks like there's a concurrency issue in rsj::GetKeyboardLayout in Ocpp.mm.  I'll try to lock the message loop there. Could you try replacing MIDI2LR.app with the version that's in [https://www.dropbox.com/s/j3qjexfevqqts7k/MIDI2LR1.zip?dl=0](https://www.dropbox.com/s/j3qjexfevqqts7k/MIDI2LR1.zip?dl=0) ? It has the lock.

**Comment by rsjaffe** [comment]
If my interpretation is correct, the latest release (3.3.4.0) should address the problem. https://github.com/rsjaffe/MIDI2LR/releases

**Comment by jbrialon** [comment]
when I installed 3.3.4.0 it wasn't working (fresh install), I had to install the 3.3.1.0 and I could use MIDI2LR, now I updated to 3.3.40 and it's working
