### ISSUE TITLE
Can not install Version 3.4.8

### ISSUE THREAD

**Issue by proart87** [rsjaffe/MIDI2LR#466]
**Describe the bug**
I'm mot able to install the current Version. When I'm launching the DMG installer, I'm getting an error message that says that the installer can not be opened because Apple can not search for malware 

**To Reproduce**
1. Download installer
2. Launch installer 

**Expected behavior**
Installer should launch as normal... 

**Screenshots**
<img width="547" alt="Bildschirmfoto 2019-12-19 um 11 36 26" src="https://user-images.githubusercontent.com/59050908/71167026-2c0f0300-2254-11ea-9b61-58841ab0e8ea.png">

**System(please complete the following information):**
 - OS: Mac OS 10.14.5 (18F132)
 - Lightroom version Lightroom Classic-Version: 9.1
 - MIDI2LR version 3.4.8

**Additional context**

**Comment by rsjaffe** [comment]
Lots of other people have downloaded and installed it properly on MacOS. Please re-download, and attempt to install while you have an active internet connection. The internet connection should not be needed normally, as the installer is notarized and stapled, but maybe the stapling didn't work, in which case the computer would check back with Apple to confirm the notarization using an internet connection.

**Comment by rsjaffe** [comment]
For additional support, use the MIDI2LR discussion group: https://groups.google.com/forum/#!forum/midi2lr
