### ISSUE TITLE
UNINTENTIONAL RESETTING of IMAGES that have already had a lot of settings modified. 

### ISSUE THREAD

**Issue by therotherman** [rsjaffe/MIDI2LR#467]
This program was AWESOME.  but I've been having a bug where when I go to modify a picture with even one command it RESETS ALL SETTINGS!  It seems to happen mostly when I enter a modification an image from the Gallery page.  Then I can't even hit CMD-Z, the history bugs out often and I have to go copy and paste from another image to get back to where I was. 

Please let me know if you have any ideas!

![Uploading Screen Shot 2020-01-16 at 10.55.19 PM.png…]()

I'm using the XTouchMini

![Screen Shot 2020-01-16 at 10 58 44 PM](https://user-images.githubusercontent.com/59993138/72590910-c1cd9a80-38b3-11ea-912a-23b61ff31db2.png)

MIDI2LR 3.3.2.0
Hackintosh that is otherwise running beautifully. 
Latest lightroom "classic" version from CC.

**Comment by therotherman** [comment]
![Screen Shot 2020-01-16 at 11 02 21 PM](https://user-images.githubusercontent.com/59993138/72591138-415b6980-38b4-11ea-8675-1bd207f3d8d4.png)
This was me trying to change the WB on a picture - and the resulting reset.  

This picture previously had a lot of settings applied.

**Comment by rsjaffe** [comment]
unable to replicate
