### ISSUE TITLE
"Previous" button

### ISSUE THREAD

**Issue by therotherman** [rsjaffe/MIDI2LR#468]
I would love to have a programmable button be "Previous" - like the button in Lightroom that allows you to copy EVERYTHING from the last picture without going through the copy and paste process.  

Thank you! 👍 :) 
Evan

**Comment by pathammer** [comment]
This is a cool idea. I think you could achieve this function with the ["Series of commands" functionality](
https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#series-of-commands)
Please post a working sample if you get it working!

**Comment by D-Noc** [comment]
Unless I misunderstand the issue, it can be done like this:
In Lightroom -> File -> Plugin Extras -> Midi2LR -> General Options you can set a list of user defined keys:
![image](https://user-images.githubusercontent.com/50765320/80338797-8b61cd00-885d-11ea-9544-a534bfd5abd5.png)
This one emulates Ctrl+Shift+V, which is the shortcut key for the "Previous" button in Lightroom.
Then, in the MIDI2LR control, you just set a button the use the Key you set up in options:
![image](https://user-images.githubusercontent.com/50765320/80338942-e8f61980-885d-11ea-9f36-d8d132275fa1.png)

**Comment by rsjaffe** [comment]
no action planned
