### ISSUE TITLE
Temperature adjustements accuracy problem

### ISSUE THREAD

**Issue by rojmagd** [rsjaffe/MIDI2LR#47]
In the last version, the temperature values are between 2000 and 50000. This is a problem for me now, because I can't make fine adjustments. When I move the temperature slide, the values changes 378 units in the next possition. This is too much if I want to make fine adjustments. The maximum temperature value that I use is 10000.

**Comment by rsjaffe** [comment]
Yes, we've had some real problems with temperature adjustments, and I disabled the range limits to address those, though I realize that created issues for others.

You can customize your own installation to enable temperature limits by editing the MIDI2LR_Client.lua file in Notepad or another plain text editor.  Just change the following section by removing the double dash (**--**) at the beginning of the lines. The double dash commented out the range adjustments. Also, you can change the 9000 to 10000 in the max lines (there are two of them) to change the range limit from 9000 to 10000. Reload the plugin or restart Lightroom to enable the changes after saving the file.

```lua
function midi_lerp_to_develop(param, midi_value)
    -- map midi range to develop parameter range
    local min,max = LrDevelopController.getRange(param)
--    if(param == 'Temperature') then
--        min = 3000
--        max = 9000
--    end
    
    local result = midi_value/127 * (max-min) + min
    return result
end

function develop_lerp_to_midi(param)
    -- map develop parameter range to midi range
    local min, max = LrDevelopController.getRange(param)
--    if(param == 'Temperature') then
--        min = 3000
--        max = 9000
--    end
    
    local result = (LrDevelopController.getValue(param)-min)/(max-min) * 127
    return result
end
```

**Comment by rojmagd** [comment]
Ok perfect, solved. Thank you very much for you quick response.
