### ISSUE TITLE
Slow transition while turning a knob

### ISSUE THREAD

**Issue by svenbluege** [rsjaffe/MIDI2LR#471]
**Describe the bug**
I use a MIDI-board with knobs (midi fighter twister). If I turn them from -100 to 100, the transition in Lightroom is pretty slow and takes some time. Today I did the update to the latest midi2lr-version. But also the older versions, which I installed afterward,  behave in the same way now. I did not notice that before, so I don't know if this is caused by the LR update or midi2lr. 

It is pretty hard to describe :) Please have a look at the attached video. 
https://www.youtube.com/watch?v=Dew7-KvgJro

Any hint to solve this would be awesome!

**To Reproduce**
1. Go to Develop module
2. Turn one or multiple slider/knob from -100 to 100 quickly
3. Check how long it takes to do the transition

**Expected behavior**
In the past, I did not notice going through all numbers from -100 to 100. I turn the knob and had immediately the right value for the setting.

**Screenshots**
https://www.youtube.com/watch?v=Dew7-KvgJro
In the last part of the video, I moved two sliders at the same time. 

**System(please complete the following information):**
 - OS: Windows 10
 - Lightroom version: 9.2
 - MIDI2LR version: 3.4.9.1

**Comment by mattnoir** [comment]
For now, you can make it run fast by going to general options and in the tab "other", uncheck "show status and activity"
Found out just now, hope it helps :)

**Comment by svenbluege** [comment]
@mattnoir thanks! That sounds great! I hope this helps others, I lost my chance to give it a try. Since nobody else complained but me, I'll close this ticket.

**Comment by mbylstra** [comment]
I'm having a similar problem. For example, when I move the exposure slider with my mouse, I see changes almost instantly - almost at 30FPS. The exposure will visually smoothly change from 0 to 100 as I move the slider with my house. However when I use my Ableton Push 2 to controller the exposure with one of the rotary knobs things slow down dramatically. It's very jerky and erratic. It might work alright for a second and then get stuck for several seconds and then suddenly jump to 100. Not only that, but I can hear the fan on my laptop get really loud as though the CPU is going crazy (Macbook Pro 2019). This doesn't happen when I use the mouse on the sliders. It's as though changes are being sent to the plugin faster than lightroom can keep up (perhaps the rate of change from the midi device needs to be throttled?). This is making the plugin unusable unfortunately. 

> For now, you can make it run fast by going to general options and in the tab "other", uncheck "show status and activity"
Found out just now, hope it helps :)

@mattnoir - Could you please explain further or screenshot what you mean? I can't see this setting anywhere in any of lightroom CC settings or in the settings for MIDI2LR. That would be much appreciated, thanks!
