### ISSUE TITLE
Develop-> Copy/Paste settings not working

### ISSUE THREAD

**Issue by roephoto** [rsjaffe/MIDI2LR#476]
After upgrading my MAC to 10.15.3 and MIDI2LR to 3.4.10.0 the copy/paste functions in the Develop Module won't work. I have tried uninstalling/reinstalling MIDI2LR, deleting and re-doing the accessibility function of system prefs, re-mapping to a different button on my xtouch-mini. Other keyboard shortcuts, sliders, etc. work fine. 

I'm running Lightroom 9.2 with camera raw 12.2. 

Any and all thoughts are appreciated.

**Comment by rsjaffe** [comment]
Please post this as a new question in the discussion group. That's where individual issues are addressed. Be sure to include your MIDI2LR.log and MIDI2LRinfo.txt files in the posting.

https://groups.google.com/forum/#!newtopic/midi2lr

**Comment by roephoto** [comment]
Will do, thank you!
