### ISSUE TITLE
Keyboard Shortcuts for User Menu Contains Typo

### ISSUE THREAD

**Issue by pixealhead** [rsjaffe/MIDI2LR#479]
In the MIDI2LR App, the Keyboard Shortcuts for User submenu includes the choice of "Key 26 - Key 24" which should be "Key 26 - Key 25". 

Choosing that option ignores what is assigned to Key 24 and instead uses Key 25. 

It is mentioned correctly in the documentation and key 24 is the only key mentioned twice in the choices that can be assigned to a CC input in that menu. It looks to be a simple typo. 

**Expected behavior**
No keys are listed more than once within those that can be assigned to a CC input. If the command is listed as Key 26 and Key 24, then it should map to those fields within the LR plug-in.

**System**
LR Classic 9.2.1
MIDI2LR 3.4.10.0
Behringer Xtouch Mini
macOS 10.15.4

**Comment by rsjaffe** [comment]
Thanks! Fix committed to develop branch and will be in next release.
