### ISSUE TITLE
Request for help: sending keystrokes to Lightroom

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#48]
If anyone can contribute code for sending keystrokes to LR, I'd appreciate it. Particularly if it is compatible with both OSX and Windows. Code should either be in C++ or Lua, though if it is in Lua, it'll have to follow the rules LR imposes on Lua programs (limited access to some system resources).

thanks

Rory

**Comment by stevejmu** [comment]
Unfortunately I don't know enough C++ or LUA to help out with this, but maybe the VSCO Keys plugin can be a good springboard to incorporate keystrokes for MIDI2LR.

https://github.com/vsco/keys

**Comment by Jewest** [comment]
Please explain what is the goal of the feature request.
What do you want to achieve? Maybe there is another way to solve the problem.

otherwise: 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms646310(v=vs.85).aspx
is an option.

**Comment by rsjaffe** [comment]
The Lightroom SDK interface doesn't provide complete control of Lightroom.

Sending keystrokes would complement the SDK to provide complete control.

So we're looking at stuffing keystrokes into the LR application, either from the MIDI2LR app (which is a separate app from LR) or from the Lua plugin (which runs as part of LR).

**Comment by seweil** [comment]
If you are still looking...

It's unlikely that there is a portable way to do this in C++ (I don't know anything about LUA)

I could probably put something together for Windows. Mac would require more research.

**Comment by StevenKersting** [comment]
http://www.music.mcgill.ca/~gary/rtmidi/ ???

**Comment by Jewest** [comment]
The first test edition is added to the pull request of the develop tree.
Looking for feedback if it works for other users.
Op 6 feb. 2016 17:29 schreef "StevenKersting" <notifications@github.com>:
