### ISSUE TITLE
Unable to install Version 3.4.10.0 on High Sierra v. 10.13.6

### ISSUE THREAD

**Issue by thatoneguyeric** [rsjaffe/MIDI2LR#480]
**Describe the bug**
I'm mot able to install the current Version. When I'm launching the DMG installer, it goes through the entire install. However, no software appears installed. 

**To Reproduce**
1- Download installer
2- Launch installer

**Expected behavior**
Software should be installed after going through the installation wizard.
NOTE: Installation says this is the location directory-
/Users/ericortiz/Library/Application Support/Adobe/Lightroom/Modules

However, no file structure exists in that location. 

**Screenshots**
**System(please complete the following information):**
 - OS: [MacOS High Sierra v. 10.13.6]
 - Lightroom version: 3.2.1 [ 20200403-1047-0e59df2 ] (Apr  3 2020)
 - MIDI2LR Version 3.4.10.0

**Additional context**

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.
