### ISSUE TITLE
Not connected to Lightroom

### ISSUE THREAD

**Issue by niccolobusato** [rsjaffe/MIDI2LR#481]
**Describe the bug**
Can't figure out why does not connect to Lightroom correctly.
would be nice to have some more information of what is not working on the connection with LR right now i'm stuck

**Expected behavior**
Installed, opened but not woking.. already searched online to find a fix but nothing is working...

**Screenshots**
<img width="745" alt="Schermata 2020-05-26 alle 21 22 40" src="https://user-images.githubusercontent.com/44100360/82941698-1df9a700-9f97-11ea-9c76-7df559ce9ad7.png">
<img width="1440" alt="Schermata 2020-05-26 alle 21 22 14" src="https://user-images.githubusercontent.com/44100360/82941694-1934f300-9f97-11ea-8856-33fb922fa3e8.png">

**System(please complete the following information):**
 - OS: MacOs Catalina 10.15
 - Lightroom version 9.2.1
 - MIDI2LR version 3.4.10.0

**Additional context**

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.

**Comment by niccolobusato** [comment]
it's also a integration request:

"would be nice to have some more information of what is not working on the connection with LR"

like some more indicator showing if lightroom i working, if firewall il blocking connections and so on..
