### ISSUE TITLE
Compatibility with X-Touch Universal board

### ISSUE THREAD

**Issue by SupperCutz** [rsjaffe/MIDI2LR#482]
Hey! I bought the XTouch Universal board (with motorized faders) and it looks like the Fader Bank buttons (similar to Layer buttons on the XTouch Mini) just behave like midi buttons and don't switch to my next bank of faders. 

Do you have any suggestions for how to trigger the bank changeover?

I love your software and will certainly make a donation.

**Comment by SupperCutz** [comment]
PS - I'd love to send you some money for doing this, but I can't in good conscience pay the PayPal fee. If there's an email that I can send some $$ to, please send it my way (just remove the periods) t.r..a.v..iswd.at. protonmail.com

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) .
