### ISSUE TITLE
Finer adjustment for colour temperature Mac

### ISSUE THREAD

**Issue by MrNeedSomeHelp** [rsjaffe/MIDI2LR#485]
Sorry if this has been covered (i have searched only found PC instructions) is it possible to create finer adjustment for of colour temperature on the Mac version please?

**Comment by rsjaffe** [comment]
See https://groups.google.com/forum/#!topic/midi2lr/u2y4ILkKxzQ and, in the future, ask questions on the forum page. Thanks.
