### ISSUE TITLE
Mac installer wizard blank screens no refresh

### ISSUE THREAD

**Issue by jcr-** [rsjaffe/MIDI2LR#486]
**Describe the bug**
Under MacOS Mojave (10.14.x), the MIDI2LR installer wizard shows blank screens initially. Scrubbing the installer window with the mouse cursor causes screen UI elements to turn into black boxes, and then they disappear to reveal the controls and instructions text. I can then successfully install. This has been the case for at least the last few releases. 

Under MacOS Catalina (10.15.6) the installer wizard is also blank, but scrubbing the window does not reveal any visible text nor controls. I was only able to install the latest version by simultaneously running the installer on another Mac running Mojave next to my Catalina Mac, and guessing at the button locations using the Mojave-based screens as a guide. I was successful after a few attempts, but obviously this is a huge PITA and not the intended installer behavior. 

**To Reproduce**
1. Run the Mac installer under Catalina
2. Observe a blank window
3. If possible, also run the installer under Mojave and scrub to reveal button locations 
4. click on the same locations in the blank windows in Catalina and note that install can be completed (with great difficulty)

**Expected behavior**
Installer wizard should have visible controls under Mojave and Catalina, and not require scrubbing the screen with a mouse under Mojave to reveal controls.

**Screenshots**
![2020-08-04_12-56-41](https://user-images.githubusercontent.com/10791802/89322345-19fe9b00-d652-11ea-8840-44489d46d51c.png)
![2020-08-04_12-56-40](https://user-images.githubusercontent.com/10791802/89322347-1a973180-d652-11ea-8f74-4c8fe6b32b99.png)
![2020-08-04_12-55-13](https://user-images.githubusercontent.com/10791802/89322348-1a973180-d652-11ea-9014-9b71fb16c671.png)

**System(please complete the following information):**
 - OS: [e.g. MacOS Mojave] MacOS Catalina
 - Lightroom version 9.3 [202005281810-476e492c] but probably not relevant
 - MIDI2LR version latest and past few installers

**Additional context**
This is, I presume, a problem with the Bitrock cross-platform installer, but I don't have a way to file a bug on that. Thanks for the great product, and let me know if I can test Mac installers for you!

**Comment by rsjaffe** [comment]
Appears to be a sporadic issue that other users are not seeing. Will close for now.

**Comment by jcr-** [comment]
I'm still seeing this issue consistently on two different macs running Catalina. Truly frustrating; no way to update to latest version because all installer screens are blank. Is there another way to get the latest compiled app for Mac? Thanks.

**Comment by rsjaffe** [comment]
Here's a zip file. Just unzip all the contents into your MIDI2LR.lrplugin folder. For a cleaner installation, you could first delete all the contents in the MIDI2LR.plugin folder, but I would temporarily save the deleted files just in case something goes wrong, so that you could roll back the installation.
[MIDI2LR4320.zip](https://github.com/rsjaffe/MIDI2LR/files/6332040/MIDI2LR4320.zip)
