### ISSUE TITLE
Copy/Paste Settings Crash

### ISSUE THREAD

**Issue by DavidEsser1** [rsjaffe/MIDI2LR#487]
I use the Behringer X-Touch Mini and want to use the Copy and Paste setting on specific buttons (Copy settings should open the window where I can check boxes for the settings I want to copy / Paste settings should just do what I says). When I push the specified button the Midi2Lr Server crashes. This is the error message *** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may only be invoked from the main thread. Behavior on other threads is undefined.'
abort() called
terminating with uncaught exception of type NSException

I didn't use the plugin for a while, but last time this function worked fine. 

 - OS: OSX 10.15.6 Catalina
 - Lightroom CC Classic Version 9.4 
 - MIDI2LR version 2.9.5.0

**Comment by rsjaffe** [comment]
Selective copy/paste was deprecated in version 2.7.0.4 in Feb 2018 and removed after that. It is no longer supported. Please upgrade to the latest version and use Lightroom's copy/paste shortcuts, which are available in the MIDI2LR list of commands.
