### ISSUE TITLE
filter by rating / flag / color

### ISSUE THREAD

**Issue by sbv3** [rsjaffe/MIDI2LR#488]
New feature, not related to a problem. 
I think it'd be great to filter the grid or the filmstrip by rating and/or by flag-status and/or by color-label. 

Tried to set it up via Library filter, but this does not allow to filter by "3-stars or more", only be "is rated". So more granular would be great. 

This would allow a workflow, e.g. of a quick run through rejecting images and then selecting a "delete rejected".
Or: rate pics with 1 star, then filter the 1-stars and rate to 2-stars, then filter the 2-stars and pick the 3-stars. This would enable a workflow where you work through a funnel of picture-rating before arriving the top rated.

**Comment by rsjaffe** [comment]
You can set up new filters in Lightroom by using the Library Filter section at the top of the Grid View, then save that as a named filter. Then, you can set that up in MIDI2LR using the Library filters setup under "Set MIDI2LR options" to assign them to commands. So this can already be done.

**Comment by sbv3** [comment]
Indeed!!! Thank you! After setting up of saved filters, one needs to restart, but then it works!
