### ISSUE TITLE
Series of commands results in "an internal error has occured: ?:0: attempt to index field 'libraryImage' (a nil value)

### ISSUE THREAD

**Issue by sbv3** [rsjaffe/MIDI2LR#489]
I set up a "Series of Commands" with the intent to go to develop mode and change the profile. 
I have three buttons programmed to address a different set of functions all within the develop mode - thus three "Series of Commands", each with its own profile.

When triggering the commands in grid mode, LR switches to develop mode and returns above error message.

To reproduce: 
setup Series of Commands with 
1: SwToMdevelop profile1
2: SwToMdevelop profile2
3: SwToMdevelop profile3

Assign the Commands to a button
Open lightroom in grid mode
Select a pic
trigger the function

What should happen is, LR should switch to develop mode and load profile x. 

 - OS: Win10
 - LRC 9.4
 - MIDI2LR 3.5.03

**Comment by rsjaffe** [comment]
what's the error message? it's missing

**Comment by rsjaffe** [comment]
Oh, it's in your title. Were any photos selected when you did that? `libraryImage` is not addressed in MIDI2LR, so that's an internal Lightroom error.

**Comment by sbv3** [comment]
It occurs only if an image is selected in grid view. 
If no image is selected in grid view, there is no error. 
It is irrespective if the image has been edited or not. 
It is also irrespective of the image type (jpg or RAW). 
It also happens if a movie is selected - for what it's worth...
It is repeatable and irrespective of the image itself.

**Comment by rsjaffe** [comment]
Given your excellent description of what's going on, I tried replicating the issue. I don't have any errors when doing that series of commands, whether or not a photo is selected in grid view. Note that I'm using a newer version of MIDI2LR that will be released when the next version of Adobe Lightroom Classic is released (very soon I hope). When that happens, please upgrade and see if you still have issues. I'm going to close this for now. Reopen if the problem persists after updating.
