### ISSUE TITLE
Request for help: copy/paste settings

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#49]
I've been working on copy/paste settings for several weeks now, and am running up against some odd behavior in LR. If anyone is familiar with Lua programming and the Lightroom SDK and wants to take a crack at it, I'd appreciate the help.

I will continue to work on this issue, but it's been strangely difficult to accomplish.

**Comment by Jewest** [comment]
https://forums.adobe.com/thread/1995019
for possible solution.
Will have a look at it when I have the time.

**Comment by rsjaffe** [comment]
Completed. Thanks.
