### ISSUE TITLE
Stopped Working Today ClientUtilities.lua 52 Table index is nil

### ISSUE THREAD

**Issue by pixelwiz** [rsjaffe/MIDI2LR#492]
**Describe the bug**
Was working fine yesterday, today started getting an error when opening.  tried to update to the latest version, the error message changed to An Internal Error has occurred: [string "ClientUtilities.lua"]:52 table index is nil

**To Reproduce**
1. Open Lightroom Classic

**Expected behavior**
Expect the Midi2LR to open and connect to Lightroom Classic so I can use my midi controller knobs

**Screenshots**
https://snipboard.io/MCinc2.jpg

**System(please complete the following information):**
 - OS: Windows 10
 - Lightroom version: 9.4
 - MIDI2LR version: 4.0.1.0

**Additional context**
There were 2 different errors today before I updated to the latest Midi2lr version
![Midi2LR Error](https://user-images.githubusercontent.com/485516/96620807-e983e000-12d5-11eb-8605-2f7c59c2fae7.png)

**Comment by rsjaffe** [comment]
Version 4+ is marked as only supporting LR version 10+
