### ISSUE TITLE
Exception argument not found virtual void VersionChecker::handleAsyncUpdate().

### ISSUE THREAD

**Issue by aaron80** [rsjaffe/MIDI2LR#493]
**Describe the bug**
When Midi2LR starts it makes those errors:

"Exception argument not found virtual void VersionChecker::handleAsyncUpdate()."

"Not managed exception argument not found, ../../external/JuceLibraryCode/modules/juce_events/native/juce_osx_MessageQueue.h line 84. Total uncaught 0."

Version 3.5.0.3 on Lightroom 9.4.

**To Reproduce**
Start Lightroom, when plugin automatically load this error appear.

**Screenshots**

**System(please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Lightroom version 9.4
 - MIDI2LR version 3.5.0.3

**Comment by aaron80** [comment]
I forgot to mention that midi2lr crash after those two errors.

**Comment by kutyla-philipp** [comment]
Hey! Can confirm! Same for me. Moving those errors to a different screen works for me at the moment. :)

**Comment by meuch** [comment]
Same here !

midi2lr crash after these 2 messages -

Error
Exception argument not found virtual void VersionChecker::handleAsyncUpdate().

Error
unhandled exception argument not found, ../../external/JuceLibraryCode/modules/juce_events/native/juce_osx_MessageQueue.h line 84. Total uncaught 0.

Version 3.5.0.3 on Lightroom 9.4 in Mac OS 10.13.6

**Comment by rsjaffe** [comment]
The update checker is broken in 3.5.0.3. The problem should have been fixed yesterday about 9 am PST. If you update Lightroom to 10, you can use the new version of MIDI2LR, where the problem also is fixed. Otherwise, if you are still having issues, you can downgrade temporarily to 3.5.0.2.
