### ISSUE TITLE
Button react twice on single click

### ISSUE THREAD

**Issue by meefox** [rsjaffe/MIDI2LR#494]
**Describe the bug**
Clicking on a simple button (0-127)
it correctly is shown in the console (as a single click)
but the action is sending twice to the lightroom.
For example, set Next photo action will actually scroll to +2 pictures.

**To Reproduce**
1. Single click on the Button
2. Action happening twice

**Expected behavior**
Action is happening once per each click

**System(please complete the following information):**
 - OS: MacOS [Big Sur]
 - Lightroom Classic 10
 - MIDI2LR 4.0.4.0

**Additional context**
Using TouchOSC for iPad as a midi device.

**Comment by rsjaffe** [comment]
This sounds like a TouchOSC configuration problem.  Please continue this conversation in the google groups for MIDI2LR, and include a copy of your MID2LR.log file.

For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . The Github issues page is for development planning only.
