### ISSUE TITLE
module doesn't work, designed for lightroom 10?

### ISSUE THREAD

**Issue by drummatze** [rsjaffe/MIDI2LR#497]
Hi,

finale i have my behringer and downloaded the newest version for mac.

i have:
Mac 10.14.6
lightroom 2015.12

the midi2lr.lrplugin is already in the plugin list from Lightroom.

but Lightroom say:

![Bildschirmfoto 2020-12-17 um 20 40 30](https://user-images.githubusercontent.com/76181735/102535174-2424b180-40a8-11eb-9d5f-b111c2ec4cc4.png)

[](url)

_**_An error occurred while loading this additional module. the additional module is designed for lightroom 10_**_

i have close all firewalls

try it again and again, no success...

Please, can you help me?

Thank
Best Regards Matthias

PS: i will give a nice PayPal donation if its work :-)

**Comment by rsjaffe** [comment]
Version 4+ is only for Lightroom 10. Use version 3.5 for earlier versions of Lightroom. https://github.com/rsjaffe/MIDI2LR/releases/tag/v3.5.0.3.
