### ISSUE TITLE
Toggle the pick flag

### ISSUE THREAD

**Issue by Gadgetgeek2000** [rsjaffe/MIDI2LR#498]
I have added a custom key for this function, but it would be great to include in the Flagging section:

Pressing the tick mark on the top left of the keyboard toggles the pick flag. If it's set, it turns it off. If not set, it turns it on.

Add Flagging > Toggle Pick Flag

In the meantime, I'll continue to use my custom keyboard shortcut. Thanks!

**Comment by rsjaffe** [comment]
will add to next release

**Comment by Gadgetgeek2000** [comment]
Sounds great! Thank you. I’m just diving into this and loving it so far. If I find anything else like that I will submit more.

Regards,
Geoff Faulkner
