### ISSUE TITLE
BCF2000 double button pressing

### ISSUE THREAD

**Issue by EugeneMichel** [rsjaffe/MIDI2LR#50]
Hi! Great work on MIDI2LR! Loving it!

Have one question: On the BCF2000 that I use, anytime I use a button I need to press it twice to activate the effect that is programmed, is there a reason to this? It seems that It has something to do with the buttons lighting up and carrying a different “CC code” when they light up or if they don’t. (one press-button lights up, one more press-button lights off) For example, in the MIDI2LR window when I press a sample button it shows as 1 | CC:91 and on the top right its shows as 1:CC91 [0]

But when I press the same button again and it lights up it shows as 1 | CC:91 but on the top right its shows as 1:CC91 [127]

Anything I can do to fix that? 

Thanks much!

**Comment by rsjaffe** [comment]
Yes, you can reprogram the buttons. The default action is toggle--one press turns it "on", one press turns it "off". MIDI2LR acts on the "on" signal (127) only and ignores the "off" signal (0). In the plugin directory is a text file to reprogram program number 2 on the BCF2000 to work best with the program. You can use a utility like [BC Manager](http://mountainutilities.eu/) to load it on your machine.

**Comment by EugeneMichel** [comment]
Got the program thanks! To change it do I need to set "Toggle ON" for each button or "Increment", or need to change it to another type of control? Thanks for your help!

**Comment by rsjaffe** [comment]
Toggleoff is the only change. The quickest way to do this is to use BC Manager to load the file BCF2000.txt found in the MID2LR plugin directory. That will program channel two of your controller to work best with the application.

**Comment by EugeneMichel** [comment]
took a while to figure out but it works now! thanks man!
