### ISSUE TITLE
Help me, Please!

### ISSUE THREAD

**Issue by Torhuta** [rsjaffe/MIDI2LR#500]
I'm using macbook air 2019
Mac OS Catalina 10.15.5

I'm using lightroom cc
and I already install the Midi2LR 4.3.0

but it won't connect with the lightroom.

can you help me please?

thanks!

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.
