### ISSUE TITLE
Midi 2 LR stops working after windows 10 goes to sleep

### ISSUE THREAD

**Issue by Jagimaging** [rsjaffe/MIDI2LR#501]
#The Github issues section is closed.

Post any comments, questions, bug reports, etc., at our new google groups discussion page: https://groups.google.com/forum/#!forum/midi2lr . **Do not post here.**

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.

If MIDI2LR appears to be functioning incorrectly, include the contents of the MIDI2LRinfo.txt file and the log file (MIDI2LR.log) in your message. These files are found in %AppData%\MIDI2LR (for Windows users) or ~/Library/Logs/MIDI2LR (MacOS users).
