### ISSUE TITLE
Using a non x touch mini

### ISSUE THREAD

**Issue by generalgrandma** [rsjaffe/MIDI2LR#504]
**Describe the bug**
My x touch mini broke so I'm trying two different options for midi controllers.
Trying an arturia beatstep and a akai midi mix.

When I use these the knobs do not start from the current settings on a picture. 
So if I adjust exposure to .5 on one photo and the next photo is at 0 and I need to bring it down or up, the second I touch the exposure on the second photo, it will leave off at .5 (the settings of the first photo). It does this with every knob.

**Expected behavior**
I expect it to adjust a second photo at its beginning settings/ starting point no matter where the knob is placed after the first photo.
For example: if I just adjusted the first photo to .5 that is where the knob is set and on the second photo if I mess with the same knob it should still start at 0, not .5

**System(please complete the following information):**
 - OS: Mac OS Catalina
 - Lightroom Classic 10.1.1
 - MIDI2LR 4.3.1.11

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.
