### ISSUE TITLE
An internal error has occurred: [string "ClientUtilities.lua"]:316: attempt to index upvalue 'preset' (a nil value)

### ISSUE THREAD

**Issue by orightok** [rsjaffe/MIDI2LR#505]
Lightroom Classic CC 8.1.2
Midi2LR 3.5.0.3
Behringer X Touch mini

Lightroom recognize the mixer and the dials are sending the right commands.
However when clicking on any of my (16) buttons of presets (all which already been set up long time ago and worked fine till now)  - they don't work and I'm getting the following error:
"An internal error has occurred: [string "ClientUtilities.lua"]:316: attempt to index upvalue 'preset' (a nil value)"
I tried closing, resetting - of both the plugin and lightroom itself - it doesn't fix it.

Any idea how I can solve this?
Thanks!

![Midi2LR error](https://user-images.githubusercontent.com/80195304/110234814-3c80cb80-7f35-11eb-96f5-0d0a1a293c4c.jpg)

**Comment by rsjaffe** [comment]
You're going to have to reassign your presets in the MIDI2LR plugin develop presets dialog.

Version 3.5.0.3 is no longer under development, so any bugs will not be fixed. 

Ask further questions about this version in the MIDI2LR forum https://groups.google.com/forum/#!forum/midi2lr.
