### ISSUE TITLE
M1 Bigsur & BCF2000

### ISSUE THREAD

**Issue by jasperJT** [rsjaffe/MIDI2LR#506]
Midi2LR is not picking up motorized faders.

enable pickop mode (Vinked)

Running:
LR 10.2
Midi2LR 4.3.1.11
OSX 11.2.3 Macbook Air M1

**Comment by rsjaffe** [comment]
Use the [MIDI2LR discussion forum](https://groups.google.com/forum/#!forum/midi2lr) for support. If MIDI2LR appears to be functioning incorrectly, include the contents of the MIDI2LRinfo.txt file and the log file (MIDI2LR.log) in your message. These files are found in %AppData%\MIDI2LR (for Windows users) or ~/Library/Logs/MIDI2LR (MacOS users).
