### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by ertz97** [rsjaffe/MIDI2LR#507]
Like 3 out of 5 times the plugin crashes if I want to start Lightroom Classic. I have set to start MIDI2LR automatically if I start LR.
I then have to force stop the Plusgin and start it again.

Windows 10 (latest update)
Midi2LR: 4.3.1.11
LrC: 10.2

But other than that issue, I really love to use this plugin, thanks for creating it.

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.

 If MIDI2LR appears to be functioning incorrectly, include the contents of the MIDI2LRinfo.txt file and the log file (MIDI2LR.log) in your message. These files are found in %AppData%\MIDI2LR (for Windows users) or ~/Library/Logs/MIDI2LR (MacOS users).
