### ISSUE TITLE
Incorrect English spelling: Luminence

### ISSUE THREAD

**Issue by GusKemper** [rsjaffe/MIDI2LR#508]
**Describe the bug**
Under "Reset Local Adjustments" (see below: screenshot) is written: Reset Local Adjustments **Luminence** Noise Reduction (PV 3+). Should be: Reset Local Adjustments **Luminance** Noise Reduction (PV 3+).
![label-124](https://user-images.githubusercontent.com/82834907/115279814-76094100-a147-11eb-9d68-549fe77647d5.jpg)

**To Reproduce**
1. Go to 'Reset Local Adjustment'

**Expected behavior**

**Screenshots**

**System(please complete the following information):**
 - OS: Windows 10 pro
 - Lightroom version 10.2
 - MIDI2LR version 4.3.1.11

**Additional context**
Just an incorrect English spelling.

**Comment by rsjaffe** [comment]
Thanks! Fixed in next release.
