### ISSUE TITLE
Missing: CAPITAL letter in Dutch version: huidig herstellen

### ISSUE THREAD

**Issue by GusKemper** [rsjaffe/MIDI2LR#509]
**Describe the bug**
Under "Kleurverlopen toepassen" (see below: screenshot) is written: **h**uidig herstellen. Should be: **H**uidig herstellen.

**Screenshots**
![label-015](https://user-images.githubusercontent.com/82834907/115519866-e324ef80-a289-11eb-90cb-b3e040d2eeff.jpg)

**System(please complete the following information):**
 - OS: Windows 10 pro (Dutch version)
 - Lightroom version 10.2
 - MIDI2LR version 4.3.1.11

**Additional context**
Just a typo error.

**Comment by rsjaffe** [comment]
Thanks. That's an error in Adobe's localization files. I've posted a bug report.
