### ISSUE TITLE
Midi2Lr not controlling Lightroom CC

### ISSUE THREAD

**Issue by jstenlake** [rsjaffe/MIDI2LR#51]
Have a strange problem. I installed the latest version of Midi2LR v0.4.3 and it worked great the first day. Now it loads and starts in LR and the Mid2LR panel says its connected to LR and midi values change but nothing happens in Lightroom when the controller sliders are moved.

Nothing has changed in the setup, lightroom has not updated and settings were saved.

Totally frustrated now.

Any ideas?

**Comment by rsjaffe** [comment]
I'd try rebooting. Also, do you have any other midi programs or midi utilities running? They'd interfere as well.

**Comment by jstenlake** [comment]
I think I narrowed it down. If I have little snitch blocking network access the midi2Lr won’t control Lightroom whereas if I disable the network filter it worksand sends to Lightroom.

Not quite sure why Midi2Lr would need network access though?Any idea why?

Regards
James

**Comment by rsjaffe** [comment]
That explains it. The MIDI app and the Lightroom plugin communicate through the network loopback interface. The plugin uses port 58763 and 58764. I forget which ports the MIDI app uses.
