### ISSUE TITLE
COPY,PASTE, And RETURN buttons not work on any mapped position

### ISSUE THREAD

**Issue by hobbsvisuals** [rsjaffe/MIDI2LR#511]
COPY, PASTE, And RETURN buttons are not working on any mapped position. Behringer x touch mini.

Many other actions work on all buttons but these. I also just updated my MAC operating system. I tried making a custom key but it wasn't working for me. Any ideas?

macOS : Catilina 10:15:7
LR version: Lightroom cc Classic 2018
M2LR Version: 3.5.0.3

-Jeremy

**Comment by rsjaffe** [comment]
Use the [MIDI2LR discussion forum for support](https://groups.google.com/g/midi2lr). If MIDI2LR appears to be functioning incorrectly, include the contents of the log file (MIDI2LR.log) in your message. This file is found in %AppData%\MIDI2LR (for Windows users) or ~/Library/Logs/MIDI2LR (MacOS users).
