### ISSUE TITLE
can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by ConwayMX** [rsjaffe/MIDI2LR#512]
Hey guys, feel like i'm falling at the first hurdle here, but OSX won't let me install the dmg file?  Just says:

“MIDI2LR-4.3.1.11-osx-installer.dmg” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

There no option for me to overide this in privacy settings either.

 - OS: MoJave 10.14.5
 - MIDI2LR version - tried it with a few and getting the same response on all of them

**Comment by rsjaffe** [comment]
For MIDI2LR support, post any comments, questions, bug reports, etc., at [our google groups discussion page](https://groups.google.com/forum/#!forum/midi2lr) . Do not post here as you will not get replies here. The Github issues page is for development planning only.

The installer is signed. Post on forum if you want to ask others for assistance.
