### ISSUE TITLE
Lightroom Masking update = no bind for masking, local adjustment presets stopped working

### ISSUE THREAD

**Issue by vogga** [rsjaffe/MIDI2LR#515]
**Describe the bug**
I used to use bind for radials and gradients but with new LR update those doesnt really work the way it used to. Most irritating is not being able to go out from "masking" after double tapping "radials" or "gradients" as I used to. There is now way to go out from masking by using midi2lr.
Also  local adjustment presets are broken after update.

**To Reproduce**
1. Open updated LR with new masking
2. Try binds with radials/gradients and local adjustments presets

**Expected behavior**
local adjustment presets should work as they used to. a new option/bind should be added for "masking" tab 

**Screenshots**

**System(please complete the following information):**
 - windows10
 - Lightroom version 11
 - MIDI2LR version 4.0.2.1

**Additional context**

**Comment by Enricopez** [comment]
There is also another problem, the commands to apply the local adjustment presets do not work ... @rsjaffe do you by any chance know if everything will be solved in the new release? 🙏🏻

**Comment by rsjaffe** [comment]
Should be fixed in latest release
