### ISSUE TITLE
Local Adustments : Show Spot Removal doesn't work

### ISSUE THREAD

**Issue by Niper8** [rsjaffe/MIDI2LR#525]
**Describe the bug**
Assigning a button to "Local Adjustments : Show Spot Removal" doesn't open the spot removal tool

**To Reproduce**
1. press midi button to be assigned
2. assign "Local Adjustments : Show Spot Removal"
3. press button
4. nothing happens

**Expected behavior**
The spot removal tool opens

**Screenshots**
![image](https://user-images.githubusercontent.com/64698962/140624368-723e9d37-384d-482c-9aed-d582e63bc4a2.png)

**System(please complete the following information):**
 - OS: windows 10 21H1
 - Lightroom version 11
 - MIDI2LR version 5.0.02

**Comment by rsjaffe** [comment]
Could you try the following proposed fix? Unzip ClientUtilities.lua from the following zip file: [ClientUtilities.zip](https://github.com/rsjaffe/MIDI2LR/files/7492685/ClientUtilities.zip). Then place that in the MIDI2LR.lrplugin folder to replace the current ClientUtilities.lua files there. Show spot removal should then work.

**Comment by Niper8** [comment]
Perfect, that fixed it.

**Comment by rsjaffe** [comment]
version 5.1.0.0 fixes this
