### ISSUE TITLE
Keyboard Shortcut doesn't work on new release

### ISSUE THREAD

**Issue by Enricopez** [rsjaffe/MIDI2LR#527]
With the new release, some keyboard shortcuts have stopped working.
For example:
cmd + opt + v = copy from previous settings,
H = Toggle show edit pins,
\ = before and after
Toggle Flag = Do not Work.
Is there any way to re-establish these commands?
Please 🙏🏻

Ps:
If there is someone else whose shortcuts do not work (these shortcuts, others work) please write to me, because if the problem was only related to me, I try to figure out how to solve.

**Comment by rsjaffe** [comment]
If you’re using a Mac, try the advice in FAQ 2. https://github.com/rsjaffe/MIDI2LR/wiki

**Comment by Enricopez** [comment]
Thanks, you're right. Now the shortcut works.
The only thing that keep not working is the command Toggle Flag. When you press the command it show before and after.

**Comment by Enricopez** [comment]
> If you’re using a Mac, try the advice in FAQ 2. https://github.com/rsjaffe/MIDI2LR/wiki

Thanks, you're right. Now the shortcut works.
The only thing that keep not working is the command Toggle Flag. When you press the command it show before and after.

**Comment by rsjaffe** [comment]
Could you open a separate issue for toggle flag?
