### ISSUE TITLE
Encoder not working

### ISSUE THREAD

**Issue by EricKaiser** [rsjaffe/MIDI2LR#53]
First of a big "Thank you" for the time and hard work you've spent so far for developing this plugin. Really awesome.

Today I got my two (low cost; 35€ each) behringer CMD DV-1 and CMD LC-1 midi controllers.
I've installed the plugin and let the plugin recognize all buttons and (endless) encoders. They have no sliders/faders.
I've assigned the lightroom sliders e.g. for Exposure, Contrast to an encoder each. 
In the MIDI2LR GUI I can see in the right topmost corner the channel, control code and the value when I turn the encoder. The value in the [ ] brackets only changes between 63 and 65. In lightroom the corresponding slider also changes in this small area. 
The buttons are working fine. I've tested the option in the settings "Enable Pickup Mode".  I've also tested your beta announcement without success.
I've attached my saved configuration file.
If you need any additional informations please let me know.

PS:
I'm using LR CC 2015.3 on windows 7 x64

I've added the default.xml in txt-format as it is mapped so far.
[default.txt](https://github.com/rsjaffe/MIDI2LR/files/42892/default.txt)

The mapping documents from behringer are:
http://origin.behringer.com/assets/CMD_LC-1_MAP.pdf
http://origin.behringer.com/assets/CMD_DV-1_MAP.pdf

**Comment by rsjaffe** [comment]
Sounds like you need to reprogram the controllers, as it appears that the encoders are only giving values in a narrow range.

**Comment by EricKaiser** [comment]
Thank you very much for answering. I've unpacked these brand new controllers today. I'm going to find informations if and how such a reprogramming is possible. 
I will test them in an audio application too, to see if they are working correctly there.

Once again thank you for your response.
