### ISSUE TITLE
OSX build issues

### ISSUE THREAD

**Issue by mischnic** [rsjaffe/MIDI2LR#54]
What is the problem you mentioned in the release description?

**Comment by mischnic** [comment]
I can only get it to compile, if the deployment target is set to at least 10.9, otherwise "unordered_map" can't be found. Maybe that helps you?

**Comment by rsjaffe** [comment]
yes, the biggest problem I face is the unordered_map issue. I'm unable to compile it to any target without that. I'm also doing this on an old Mac that isn't behaving very well.

If you could compile this for release (target 10.9) and email it to me I can post it in the releases section. Just email it to rsjaffe@gmail.com.

**Comment by mischnic** [comment]
Sent

**Comment by rsjaffe** [comment]
Thanks! Updated releases with the OSX version.
