### ISSUE TITLE
Auto populate prefs name in load/save dialogs

### ISSUE THREAD

**Issue by lfrancis** [rsjaffe/MIDI2LR#553]
Right now whenever I make a change I have to remember the name I assigned to the prefs file before I save it -- ideally this would be remembered between sessions so I wouldn't have to go digging through my docs folder to find it. Thanks!

**Comment by rsjaffe** [comment]
That's intentional. The load/save dialogs are only there for occasional use when sharing preferences with others or moving to another machine. They're not intended to be used on a frequent basis.

**Comment by lfrancis** [comment]
> That's intentional. The load/save dialogs are only there for occasional use when sharing preferences with others or moving to another machine. They're not intended to be used on a frequent basis.
> 
> Preferences for the current machine are automatically saved by Lightroom without you doing anything.

Oh, so we should think of this feature as an import/export feature rather than a save prefs feature? So when I make changes are they automatically saved when I exit my LR session?

**Comment by lfrancis** [comment]
> > That's intentional. The load/save dialogs are only there for occasional use when sharing preferences with others or moving to another machine. They're not intended to be used on a frequent basis.
> > Preferences for the current machine are automatically saved by Lightroom without you doing anything.
> 
> Oh, so we should think of this feature as an import/export feature rather than a save prefs feature? So when I make changes are they automatically saved when I exit my LR session?

Never mind, re-read your response and saw that you already clarified this -- thanks!
