### ISSUE TITLE
Can't set command to more than one control

### ISSUE THREAD

**Issue by hzamir** [rsjaffe/MIDI2LR#58]
I am using A Novation Nocturn, with multiple pages. With Knobroom, I am able to set more than one controller to the same parameter, but in MIDI2LR, once a parameter has been assigned to a controller it is disabled and cannot be assigned again.

The use case is to have some common controls available in more than one context when it makes sense.

**Comment by rsjaffe** [comment]
This feature was removed in an earlier version because multiple assignments to a slider/knob created problems. We'll work on reinstating it.

**Comment by rsjaffe** [comment]
see #31 for more informationn
