### ISSUE TITLE
MIDI2LR doesn't accept several cropping commands

### ISSUE THREAD

**Issue by hzamir** [rsjaffe/MIDI2LR#61]
These parameters (CropLeft,CropTop,CropRight,CropBottom,CropAngle) work in knobroom, so it is easy to dial in the edges of the image. I attempted to directly editing the settings XML to assign these same commands via MIDI2LR (being missing from the menu notwithstanding), but apparently those values were rejected.

**Comment by rsjaffe** [comment]
Right. If it's not in the menu options, it's not available. I can put this into the request queue (Issue #31 ).
