### ISSUE TITLE
Copy and paste problem

### ISSUE THREAD

**Issue by rojmagd** [rsjaffe/MIDI2LR#63]
First of all, I would like to thank you for your work. It helps me a lot.

I was waiting impatiently for the last release, for copy and paste options. However, it doesn't work as I thought, because I only need to copy some parameters (for example contrast and temperature). When I assign and use copy and paste in MIDI2LR, ir paste all parameters, including spot removal or other zone tools, and this is a problem.

Tank you very nuch.

**Comment by rsjaffe** [comment]
Currently, that would require customization for each use case, which would be impractical. However, I might be able to add something to the options dialog to allow a customized version. I'll look into it for a possible future release. I'm folding this into the requests posting ( #31 ).

**Comment by rsjaffe** [comment]
I've written the code to do this and it looks like it will work. There'll be a new tab in the options dialog. Look for this feature in the next release.

**Comment by rojmagd** [comment]
Ok perfect. Thank you very much.
