### ISSUE TITLE
Midi2LR 3.5.0.3 won't connect to LR

### ISSUE THREAD

**Issue by ChristianBirzer** [rsjaffe/MIDI2LR#631]
**Describe the bug**
Since some time the old 3.5.0.3 won't connect to LR 6. I get the red "not connecte to Lightroom" message and nothing works.

**To Reproduce**
1. Start lightroom
2. The Midi2Lr plugin automagically starts the external application
2. Wait a few seconds and look at the red bar

**Expected behavior**
A green bar showing "connected to Lightroom"

**System(please complete the following information):**
 - Win10 21H1 19043.1526
 - Lightroom 6.16
 - MIDI2LR 3.5.0.3

**Additional context**
It seems that Midi2Lr tries to open the https port on 185.199.110.153:443 which seems to be a non existing github page. At least, when I open this address in my browser it loads forever and nothing happens. 

After disabling the network completely, Midi2Lr could connect to Lightroom immediately and everything worked fine. It still works after reconnecting the network but I fear that this is some kind of update check that will break the connection the next day/week/whatever again.

BTW: When the LR plugin is active, the LR process also has an open connection to that address.

If it is a problem with the version check: is there a way to disable it completely? Since I won't upgrade to a newer version of LR, I'm also stuck with the 3.5.0.3 Midi2LR.

**Comment by rsjaffe** [comment]
There's no way to disable the version check. However, the version check should not cause problems as newer versions check a different part of the version file. Older versions don't see any version changes when they check online. 

I don't know why it is causing issues with your installation, but I'm no longer supporting older versions of MIDI2LR.
