### ISSUE TITLE
Unassigned lines not removed in localized install (french)

### ISSUE THREAD

**Issue by edaubie** [rsjaffe/MIDI2LR#646]
I run a french version of Lightroom and MIDI2LR.

When an "unassigned" line is created in the MIDI2LR configuration, it cannot be removed by the "remove unassigned" button.

The label on the button is translated correctly (Non assigné) and also the remove button (Supprimer les lignes non attribuées).
However, in the xml configuration file generated when you save your configuration, it is still labeled "Unassigned" which might be the cause of the problem. (I guess the erase button function uses the localized label to search for lines to erase).

If I reverse back to english for Lightroom, MIDI2LR is launched in english and the button is now working again.

I'm on OSX 10.4.6 french (Mojave), Lightroom Classic 10.4 and MIDI2LR 4.3.1.11

[Exposure.xml.zip](https://github.com/rsjaffe/MIDI2LR/files/8453625/Exposure.xml.zip)

[ Screenshot 2022-04-08 à 18 02 14](https://user-images.githubusercontent.com/103272982/162479792-0889c83b-13f4-405b-a159-e4f612824fe4.jpg)

**Comment by rsjaffe** [comment]
I tested foreign languages in the current release (which is the only release I will fix), and delete unassigned worked correctly. I did take this opportunity to simplify the class involved (will be in new release, not pushed to github yet).
