### ISSUE TITLE
App loses all assigned commands at startup

### ISSUE THREAD

**Issue by Slelmo** [rsjaffe/MIDI2LR#66]
I need to load a saved preset every time at startup. This started to happen with 0.6.0.
Running Win 8.1 with LR 6 CC, for now.

But I still love the app, saved the day when Paddy died.

**Comment by rsjaffe** [comment]
Are others having this issue?

As a first try, why don't you save the preset (even though you haven't changed any settings). I wonder if the app somehow forgot where it was saving the preset so was missing it on load.

**Comment by Slelmo** [comment]
I do have saved an XML which I load at every startup. It's even saved in an convinient place as the load window doesn't remember where it loaded the file the last time :).

I now have reverted to 0.5.0 because it seems like the most functioning version. 0.7.0 wouldn't move the sliders to theit Lightroom positions. Meaning that the motorized faders didn't move when swapping pictures. Actually very oddly some wouldn't move.

I'll try out the 0.7.0 and do a few reinstalls later, now I need to work.

**Comment by Slelmo** [comment]
Reverting to 0.5.0 didn't help on the losing assigned controls issue. The problem actually appeared on 0.5.0 also :). So it originally emerged between the update from 0.5.0 to 0.6.0 and seems to be global now. It's a minor issue to reload the commands for the sliders. There seems to be some problems to get the motorized sliders to work, needs a few restarts which is kind of a bummer. 
Now there is an issue when I try to load the XML the load window is borken. Which means it's hard to load a file :). 
![capture](https://cloud.githubusercontent.com/assets/16116994/11597606/5d840018-9ac5-11e5-92d2-2324fd3c8d8d.PNG)
Oh, well, maybe some reboots and restarts.... Another issue, see capture2 and my solution
![capture2](https://cloud.githubusercontent.com/assets/16116994/11597822/d7d5150e-9ac6-11e5-8b88-7626f6a4e75d.PNG)

**Comment by Slelmo** [comment]
Okay, just pinned down the problem with the sliders!
So I'm used to navigate just with two buttons on the behringer, next and previous picture. To wake up the behringer I need first to click on a photo with the mouse and then it works, sliders make their whooshclick!-sound. Nice. Now there are no real issues for me anymore.
