### ISSUE TITLE
MIDI2LR.exe doesn't start

### ISSUE THREAD

**Issue by skalinkin** [rsjaffe/MIDI2LR#668]
**Describe the bug**
application does not start. Start the Lightroom Classic 11.4.1 and no application. go to plugin folder double click on MIDI2LR.exe nothing happens. Click menu File -> Plug-in Extras  -> Start application nothing happens.

**To Reproduce**

**Expected behavior**
application should start

**Screenshots**

**System(please complete the following information):**
 - OS: Windows 10 
 - Lightroom version - Classic 11.4.1
 - MIDI2LR version 5.4.0.0

**Additional context**
After disable, enable and reload plugin via Plugin Manager following messages where printed.

Plug-in error log for plug-in at: C:\Users\SK\AppData\Roaming\Adobe\Lightroom\Modules\MIDI2LR.lrplugin

**** Error 1

An error occurred while attempting to run one of the plug-in’s scripts.
?:0: attempt to call method 'send' (a nil value)

**** Error 2

An error occurred while attempting to shut down the plugin.
?:0: attempt to call method 'send' (a nil value)

**Comment by Hammaryd** [comment]
Same here since a crash. Any suggestion?

**Comment by Hammaryd** [comment]
Delete C:\Users\Admin\AppData\Roaming\MIDI2LR
Delete MIDI2LR.lrplugin
Reinstall MIDI2LR

worked for me!
