### ISSUE TITLE
CPU hog :-(

### ISSUE THREAD

**Issue by bighugs** [rsjaffe/MIDI2LR#67]
I've used previous versions in another photographer's studio with no issues.

I've just installed v6 on 10.10.5 with the latest version of lightroom and my CPU is smashed at 100% which makes LR unusable...

<img width="557" alt="screen shot 2015-12-03 at 10 56 18 am" src="https://cloud.githubusercontent.com/assets/16103552/11550691/20cbb33c-99ad-11e5-9c78-03f17fbceab0.png">

**Comment by rsjaffe** [comment]
Very odd. Looks like you're on OSX. On my PC, which has a pretty old processor, MIDI2LR.exe 0.7.0 is using about 0.05% of the CPU capacity. Is anyone else on a Mac having CPU issues?

Have you tried rebooting then reinstalling? I wonder if something's gone wrong with the install. Also, may want to try the latest version (0.7.0) as it's the first one that's had significant work on the application for some time.

**Comment by bighugs** [comment]
v7.0 does not do this... 

Lightroom CC 2015.3 is a pig... 

My initial problems with speed were due to "Use Graphics Processor" settings which is an issue in 2015.3

**Comment by bighugs** [comment]
Darn, still happening with v7.0 

![midi2lr](https://cloud.githubusercontent.com/assets/16103552/11612743/38699392-9c41-11e5-91db-e8740caa2f00.jpg)

**Comment by rsjaffe** [comment]
Is anyone else having this issue?

**Comment by Jewest** [comment]
Maybe the network link got lost causing a high cpu load. 
(I have seen this is the past om a windows 7 environment, restarting fixed it for me)
What happens if you "kill" the Midi2lr application and start it again?
thank you for your reply.

**Comment by emkorec** [comment]
I have the same problem. Mac El Capitan. MIDI2LR uses about 2% CPU most of the time but after Lightroom is idle for a couple of hours it goes up to 97% usage and my Mac mini keeps cooling. I noticed this issue first with 0.9 or 0.9.5 version (do not remember), now I have the 0.9.6 and things are the same.
