### ISSUE TITLE
Selective copy and paste problem

### ISSUE THREAD

**Issue by rojmagd** [rsjaffe/MIDI2LR#70]
Hello. As always, thank you very much for your work.

I have tested the new selective copy and paste option and it dosen't work well. First of all, I click all the parameters in the paste options dialog. Then, I copy and paste selected settings, and the next parameters doesn't copy and paste:

- Temperature
- Tint
- Exposure
- Contrast
- Highlights
- Shadows
- Whites
- Blacks
- Clarity

I think the other parameters copy and paste correctly.

Thanks.

**Comment by rsjaffe** [comment]
Should be fixed in latest version https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.8.0
