### ISSUE TITLE
Midi2LR not opening. 

### ISSUE THREAD

**Issue by smoriginal** [rsjaffe/MIDI2LR#708]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System(please complete the following information):**
 - OS: [e.g. MacOS Mojave]
 - Lightroom version
 - MIDI2LR version

**Additional context**

**Comment by smoriginal** [comment]
It was working and then just stopped. Mac os Monterey 12.6 on an iMac. The app started when Started LR. It popped up in my application bar then disappeared. I reinstalled it several times but no luck. Deleted the MIDI2LR.lrplugin and then reinstalled but nothing. Under LR Plug in manager I disabled it . restarted LR enabled it. then closed down LR and reopened it...no luck.
During one of the installs I got this msg: 

"MIDI2LR requires ports 58763
and 58764 to communicate to
Lightroom. At least one of those
ports is currently unavailable. If
you are running MIDI2LR right
now, disregard this message.
Otherwise, you will have to
identify what is blocking those
ports to enable MIDI2LR to
function properly." 

Im not sure how to make this ports available..


I read I think under discussion that it may be a firewall issue. Turned the firewall off. Reinstalled it.. nothing  I reinstalled the program a few times but didn't get that message again. I even moved the USB connector to a different physical port.. that didn't do anything. I'm using MIDI2LR version 5.4.0.0.

Thanks in advance for your help.

**Comment by smoriginal** [comment]
Sorry LR classic v 12

**Comment by fiveam-lukas** [comment]
Same Problem here unfortunately.

I've downloaded v6.0.1.0 for osx. But when i open the .dmg and click on the installer, only a dock icon shows up but nothing else happens. No window or anything.
Same with the latter v5 versions.

Mac Mini M1,
OSX Sonoma 14.1.1

Screenshot of Stage Manager view: https://cln.sh/PDRgrtcV

**Comment by krichel89** [comment]
Same here.
Lightroom Classic v 13.1 on Windows 11
I think it stopped around the Lightroom update to 13 or 13.1
I upgraded Midi2Lr from 5.0.4 to 6.0.2 but the MIDI2LR.exe didn't start before and doesn't start now.

**Comment by rsjaffe** [comment]
> Same here. Lightroom Classic v 13.1 on Windows 11 I think it stopped around the Lightroom update to 13 or 13.1 I upgraded Midi2Lr from 5.0.4 to 6.0.2 but the MIDI2LR.exe didn't start before and doesn't start now.

Windows and MacOS machines have different installations, so your problem is probably not related to the earlier messages in this thread. Try deleting MIDI2LR.lrplugin from wherever you installed it, and delete C:\Users\MYNAMEHERE\AppData\Roaming\MIDI2LR directory (replace "MYNAMEHERE" with your user directory name to find it). Then reinstall MIDI2LR.

**Comment by krichel89** [comment]
Thanks. That did not work. 
So I installed the program in a different folder and added it manually. This works, but might be a very specific problem I created with my Windows configuration.
