### ISSUE TITLE
Contrast and Shadows nob not recognize preset value

### ISSUE THREAD

**Issue by adrianpytlikadrian** [rsjaffe/MIDI2LR#709]
### Discussed in https://github.com/rsjaffe/MIDI2LR/discussions/697

<div type='discussions-op-text'>

<sup>Originally posted by **kindian123** September 10, 2022</sup>
Hi, after updating to the latest release I have this issue. Currently using updated Lightroom with Behringer X Touch Mini and latest MIDI2LR. I have a preset with +30 contrast, +30 shadows, using Behringer top nobs before with no issues. Now I have to drag them down to reach something above +30, I guess it starts Contrast with +54 or something when it's actually at +30, doesn't always happen with Shadows. This issue always happened to me with the vertical slider never with the top nobs. Anyone with this issue?

Update: tested the Quick Develop Contrast and Quick Develop Shadows and it works fine, too bad because I have only -5/+5 steps not -1/1 like in Basic Tone
adrianpytlikadrian:
I have a problem with the contrast and shadow knob. The values are "stuck" on some number and to change the value you have to go back to the given value to make it work.</div>

**Comment by darthdurden** [comment]
@adrianpytlikadrian are you still having this issue? I'm seeing similar issues with the X Touch Mini. I think I've tracked it down to when I switch between layer A and layer B on the controller. Is that what you're seeing as well? @rsjaffe When these don't work (at least for me) I see 2 different values in the adjustment overlay, both the new value that is trying to be set as the dial twists as well as the stuck value. Once I reach close to the stuck value, it goes down to a single value and works as usual.

**Comment by adrianpytlikadrian** [comment]
Hi! 
Still same problem on my xtouch mini. But I don't see problem in switching between layers. Problem is only in contrast and shadows dial.

**Comment by darthdurden** [comment]
@adrianpytlikadrian ah gotcha, its weird. Can you confirm something  for me. If you're on a photo and switch layers, do the LEDS on the dials always match the values of the photo? I seem to have some issues there. Especially if I double tap the A layer, it puts all of the LEDs to 0 and then causes weird behavior. Trying to determine if that is a software or hardware issue. Thanks!

**Comment by rsjaffe** [comment]
Fixed in https://github.com/rsjaffe/MIDI2LR/commit/4605af1b46ef52cae9ecfabf0a35fdca7a5718d5
