### ISSUE TITLE
connected to LR but nothing happening

### ISSUE THREAD

**Issue by ajaxandy** [rsjaffe/MIDI2LR#71]
Hi,

I've installed the plugin and Midi2LR is open, LR states the plugin is 'installed and running'.  However when I move the faders etc on the Midi controller (Behringer) nothing happens.  I looked on-line and noticed the Midi2LR window should become populated with what I'm doing but there is nothing happening at all.  Midi2LR states 'connected to LR' so I'm a little confused.  The midi controller is connected to the PC with a USB cable which I presume is correct?  Any help would be great! :)

Using LR CC on PC.

**Comment by DavidWeaverPhoto** [comment]
Some ideas:
Before you start LR and MIDI2LR run BC Manager and make sure your have a connected device.  Then CLOSE BC manager (keeping it open will cause issues).
Start LR.
See what happens...
This works for me most of the time

**Comment by ajaxandy** [comment]
Thank you for the reply David :)  I ran BC manager and it states midi input port and output port are absent and personality is 'offline'.  I have no idea what this means though.... any advice?

**Comment by DavidWeaverPhoto** [comment]
(assuming only one MIDI device and that it is the BCF2000)
From the main BCM screen select Options -> Midi Devices.  Make sure you have the BCF2000 enabled in the Input Tab and in the Output Tab.  When you close this window it should test for a controller.
From the main BCM window select View -> B-Controls
It should display a controller.  If there is nothing in the file name column you need to open (from the B-Controls window: File -> Open) the BCF2000.txt file.
Now you need to send the data into the controller (from the B-Controls window: MIDI-> Send All Data).
Just to check / troubleshoot test the3 hardware to make sure your MIDI connections are working.  (from the B-Controls window: MIDI-> Maintenance - > Test Hardware ).

**Comment by ajaxandy** [comment]
Thanks David, I feel I'm missing something here a the BCF2000 is listed in both input and output as 'Absent BCF2000' and 'Personality' is listed as 'Offline'.  

I highlight it and then go to 'Midi' but 'send all' is greyed out.  The only thing I can click in that menu is 'Options' and 'Global Setup History'... 'Test Hardware' is greyed out.  I've attached a screen shot if B-Controls so you can see what I mean.  

I've connected the controller to the PC with the USB lead, is that all I need to do or have I missed a step maybe?

![b-controls](https://cloud.githubusercontent.com/assets/16177532/11658427/6d7c5112-9dba-11e5-93f9-4f48eb92f119.jpg)

**Comment by ajaxandy** [comment]
Anybody?

**Comment by ajaxandy** [comment]
Ok managed to resolve part of this issue, factory reset on the Midi controller and then I could switch it to USB mode which wasn't working before.  Now I can get the nobs at the top to be recognised in LR but the sliders aren't being picked up in Midi2LR.  If I turn the nobs I get 'unmapped' appearing but the sliders don't seem to do anything at all

**Comment by ajaxandy** [comment]
Please close this issue... turned out I needed to learn how to program a midi controller before I worried about using LR2Midi.  Now have it working so no help needed regarding this issue.
