### ISSUE TITLE
Lightroom 12.01

### ISSUE THREAD

**Issue by dannephoto** [rsjaffe/MIDI2LR#712]
Hi! Just recently started using this program with a nehringe xtouch mini. Any plans updating keys for lightroom version 12.01? What I am really missing is to be able and assign a dedicated button for the mask function 'Objects' added recently in lightroom. Not possible to use this with a short cut. Would be perfect to be able and use it with Add To Mask With for instance.

**Comment by rsjaffe** [comment]
See https://github.com/rsjaffe/MIDI2LR/discussions/759#discussion-5924718
