### ISSUE TITLE
Version for Capture One

### ISSUE THREAD

**Issue by BKapelari** [rsjaffe/MIDI2LR#713]
Hey,

I really like your software. It's super intuitive and easy to use.
It would be great if there was also a version for Capture One.

Is it complicated to parse the code for Capture One?

**Comment by wunditta** [comment]
Realistically this will not happen. It would be a complete rewrite and I doubt both programs offer the same functions over their API:
* Capture One uses AppleScript; Lr uses LUA = different programming languages
* API differs = functions do not match, and even if both offer the same function, the function call will be different
* MIDI2Lr is for Windows and Mac, Capture One only supports scripting for Mac as far as I know

I think it is safe to say that you can close this issue as resolved, i.e. this will never happen here. Maybe someone will start a new project for Capture One. But this is a different story then...
