### ISSUE TITLE
Installation help please - Motorised sliders not responding BCF2000

### ISSUE THREAD

**Issue by b3nb123** [rsjaffe/MIDI2LR#72]
Sorry if this is something dumb, but the motorised sliders on my BCF2000 don't move when the next image loads. I have to move them up to pick up the point they are at, as you do on a non-motorised unit.
The BCF2000 is up and running OK with Paddy in Lightroom 5, and that setup involved sending the commands to the BCF2000 in order for it to load the settings into it too (Not sure why it requires that!) Now I'm trying to move over to MIDI2LR and lightroom 6, do I need to factory reset my unit before it will work?

Also, how do I select which develop preset is which, when it just says 'preset 1' etc

Thanks

**Comment by bigbasec** [comment]
Same problem here, though the first slider does move w/ a photo change, the rest do not.

**Comment by krakozavr** [comment]
Same here :( BCF2000 is working fine with PADDY under LR5 but I must switch to the latest one because my camera is unsupported with the 5 version.

**Comment by bigbasec** [comment]
Nevermind, wound up fixing this myself.  Reset the BCF to factory, clicked to Rescan Midi devices after a restart and everything is working as expected.  Likely broke Paddy in the process, but I'm ok with that.  Thank you!

**Comment by b3nb123** [comment]
That's good to know. I'm scared to reset my BCF2000 at the moment, as 
I'm in the middle of a run of weddings right now and don't want to have 
to spend time setting things up until they'll all edited at least!

**Comment by bigbasec** [comment]
If you're coming from Paddy, the experience is about to be life changing for you.  It's pretty smooth on LR6.

**Comment by b3nb123** [comment]
I got it working today by resetting the BCF2000. However there are a couple of issues with mine:
PasteSettings doesn't work to paste the  previous image's changes. It shows on the MIDI2LR setup window, but nothing happens in LR. Not sure why that is but it's something I really need

The motorised faders twitch a little but actually don't move to position, which is quite a problem, one I hope I can get to the bottom of. 
I had to turn off 'pickup mode'. That was correct wasn't it?

**Comment by krakozavr** [comment]
well done!
Just one small cosmetic issue: values doesn't matching to the space.
And, BTW, it will be cool to make the input fields there because it is not easy to set a precise values with a sliders :)
![screenshot](http://minsk2000.to/temp/limits-values.png)

**Comment by rsjaffe** [comment]
PasteSettings requires you to first CopySettings. Have you done that? Once you've copied settings, you can paste to as many photos as you desire.

**Comment by b3nb123** [comment]
Thank you, I thought it was paste previous, now I understand. How do I
specify which develop preset is which when it just refers to them by
number?

**Comment by rsjaffe** [comment]
There are two different types of "paste". One is paste preset, which has
numbers. To specify which preset goes to which number, open up the options
menu for MIDI2LR in File->Plugin Extras->MIDI2LR->Options. Follow the
instructions at https://github.com/rsjaffe/MIDI2LR/wiki/Commands:-Presets .
Copy/paste settings is described near the bottom of the page here:
https://github.com/rsjaffe/MIDI2LR/wiki/Commands:-Photo-Actions and is used
for copying the settings you used on another photo.
