### ISSUE TITLE
Sliders works with a delay 

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#74]
Behringer BCF2000, LR CC, Windows 10, MIDI2LR 0.7.0

When I try to move sliders, them working with a strong delay.
A little adjustments works fine.
But when I try to do loong move (full-diapason), especially if I move a slider fast - I see that it have no affect to LR; value next to a lightroom slider changing just a little, and the moved slider at BCF will return into position corresponding to these almost unchanged value after short time.

**Comment by MrGBCF2000** [comment]
Hi,
Have you tried in Midi2LR settings uncheck "enable pick up mode" ?

**Comment by krakozavr** [comment]
Thank you! Yes, you are right, solved.
