### ISSUE TITLE
MIDI Button "Develop: Lightroom Paste Settings" causes permanently active Ctrl button

### ISSUE THREAD

**Issue by Retroguru** [rsjaffe/MIDI2LR#740]
**Describe the bug**
After hitting the MIDI Command "Develop: Lightroom Paste Settings" with the X-Touch Mini, the Ctrl button is permanently active (like Caps Lock), even outside Lightroom.

Until fix, a workaround: press the MIDI Command "Develop: Lightroom **Copy** Settings", then the Ctrl button is released.

Let me know if you need more information.

**System:**
 - OS: Windows 11 Pro
 - Lightroom version: 12.4 (happened on earlier versions, too)
 - MIDI2LR version: 5.4.0.0

**Comment by wunditta** [comment]
Sorry, but I cannot confirm this one, at least for the X-Touch Compact. Everything seems to work fine. Maybe an issue with the Mini.

**Comment by Retroguru** [comment]
Now I can't reproduce this issue. Seems to be fixed by Lightroom.
