### ISSUE TITLE
Fork wunditta/MIDI2LR

### ISSUE THREAD

**Issue by wunditta** [rsjaffe/MIDI2LR#746]
Currently it is very difficult to decide how to proceed with this project. I started with my fork [wunditta/MIDI2LR](https://github.com/wunditta/MIDI2LR) to iron out some smaller issues and some little changes. But now I am afraid it gets out of hands. Before it can or never will be accepted to join with this repository I urgently would need some feedback from you, rsjaffe.

What are your plans with this? Will you maintain it further? If so, do you see any chance to join our forks? I am willing to contribute in any helpful way. I could also undo some changes and add them step by step.

One of the major issues is, that I am now moving most functions from Profiles to ClientUtilities as there were functions in each requesting functions from the other (after I added some features). I am afraid that soon it will be impossible to join both forks. This change is not reflected on Git so far, only locally. But as I will fix some bugs with the current pre-release I will have to upload that as well.

**Comment by antzpantz** [comment]
I hope we hear from rsjaffe soon and also that they are well.

**Comment by rsjaffe** [comment]
I hope to join the forks sometime soon. I stepped away because I was getting burnt out with some of the more obscure bugs and wasn't getting any help. Now that you're working on it too, I feel better about getting back. I should do so within a month (can't get to it until then). Still need significant help with Mac Silicon processor peculiarities as I don't have a machine set up to debug that processor.

**Comment by antzpantz** [comment]
I've started to look into what goes on behind scripting for Lightroom with
MIDI2LR but my programming skills haven't been used in nearly 10 years!

**Comment by wunditta** [comment]
> I hope to join the forks sometime soon. I stepped away because I was getting burnt out with some of the more obscure bugs and wasn't getting any help. Now that you're working on it too, I feel better about getting back. I should do so within a month (can't get to it until then). Still need significant help with Mac Silicon processor peculiarities as I don't have a machine set up to debug that processor.

Very nice to hear from you :-) . I really hope I did not mess things up in an uncontrollable way... ;-)

Just for reference, this are the issues which should be solved with my fork:
* #712 
* #706 
* #666 
* #608 (that was a nightmare)

**Comment by rsjaffe** [comment]
I'm now actively working on the update. It's going to take a while because there's a lot to do.

**Comment by rsjaffe** [comment]
6.0 is out for testing ([see discussion forum](https://github.com/rsjaffe/MIDI2LR/discussions/759#discussion-5924718)). It has some of your simpler updates. I am slowly reviewing the other ones for possible future release.

**Comment by rsjaffe** [comment]
Undoing some of the changes I haven't yet included and reintroducing them step-by-step would help greatly.

Normally when I'm developing a new feature, I commit all the changes for that specific feature as a single commit, with all the changes in the affected files included. That way, it is much easier to understand the changes and correct issues as they arise.

Thanks again for your work!

**Comment by wunditta** [comment]
Hi,

 

I am deeply sorry for being silent so long. I had a rough time and would need another one or two weeks until I can concentrate on this project again. Things should be cleared up then and I can continue with the work.

Are you still interested in merging the two repositories?

 

Best regards, Dieter
