### ISSUE TITLE
Setting up the button: Up, Hold, Down

### ISSUE THREAD

**Issue by dhpro100** [rsjaffe/MIDI2LR#752]
1. I want to configure some buttons so that when pressed for a long time to repeat the action
2. Know when releasing is performed - perform another action (before/after, for example)

When you right-click on the currently configured button, a modal window opens for selecting/configuring the `noteup` function (when pressed), `noteup-hold` (when pressed for a long time) and `notedown` (when released).
The command assigned to `noteup-hold` will be executed only if the user presses the key for a long time (Perhaps after 2 seconds of pressing, if he still hasn't released it).
Next to the `noteup-hold` check mark on "`repeat`":
When the "`repeat`" checkmark is pressed, the command is repeated until the key is released.

**Comment by dhpro100** [comment]
> There isn't any noteup-hold message in MIDI. What are you suggesting?
> 
> https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message

I'm sorry, I didn't delve into the existing midi events, but thanks for the useful material!
I am also not familiar with and have not read the documentation of the language in which the plugin is written, but I think it can be done programmatically.

To poll the last pressed key every (optimal time interval, maybe 150ms) for 2 seconds or as long as the key is pressed. This way we will know when the moment of the button is up and how long it has been pressed.

The feature suggestion was based on what I saw in the driver for arturia beatstep.

Thank you!

**Comment by friedmanwd** [comment]
Does "closed this as completed" mean this wasn't done and will never be done? Assigning actions to long-press keys seems to me to be a very reasonable, if not essential, capability. It certainly doesn't seem to work this way in 6.2.1.0.

**Comment by antzpantz** [comment]
You've revived an old thread. rsjaffe's even older comment suggests that
MIDI controllers are not designed to long hold, or something to that effect.

https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message
