### ISSUE TITLE
Premiere Pro support

### ISSUE THREAD

**Issue by BernhardSchlegel** [rsjaffe/MIDI2LR#772]
Maybe already existing? Couldn't find it. Happy to contribute.

**Comment by rsjaffe** [comment]
Would need complete rewrite of plugin. It has a different SDK and uses C++, not lua. But the executable part of MIDI2LR could work with a new plugin.

If someone wants to do that, they can, but it is not in my plans.

**Comment by BernhardSchlegel** [comment]
Thanks for the response!
