### ISSUE TITLE
你好开发者 无法使用用户的键盘快捷键

### ISSUE THREAD

**Issue by Qq462626562** [rsjaffe/MIDI2LR#777]
<img width="733" alt="截屏2024-01-31 下午6 06 38" src="https://github.com/rsjaffe/MIDI2LR/assets/116749640/394cfbba-6151-4008-a1d9-2d6dc20ca504">
<img width="652" alt="截屏2024-01-31 下午6 07 06" src="https://github.com/rsjaffe/MIDI2LR/assets/116749640/bb7b05e4-ce68-4fb2-bff2-8cb76c6c6d44">
<img width="1195" alt="截屏2024-01-31 下午6 14 56" src="https://github.com/rsjaffe/MIDI2LR/assets/116749640/15218bde-324f-4784-8201-16c1bcc11c32">

**Comment by Qq462626562** [comment]
![Uploading 截屏2024-01-31 下午6.07.06.png…]()

**Comment by Qq462626562** [comment]
<img width="1195" alt="截屏2024-01-31 下午6 14 56" src="https://github.com/rsjaffe/MIDI2LR/assets/116749640/47cb1c5f-62ca-4498-8b82-d196d3fbc5ba">

**Comment by Qq462626562** [comment]
<img width="733" alt="截屏2024-01-31 下午6 06 38" src="https://github.com/rsjaffe/MIDI2LR/assets/116749640/d9e3f0d1-a9c6-4b1f-902a-efa7aee8d340">

**Comment by Qq462626562** [comment]
<img width="652" alt="截屏2024-01-31 下午6 07 06" src="https://github.com/rsjaffe/MIDI2LR/assets/116749640/a436b998-8f57-4c0e-87c6-53e26b7847ac">

**Comment by 153957** [comment]
Translation of the title:
> Hello Developers, Unable to use user's keyboard shortcuts

Perhaps the different keyboard layout/localization is causing issues?

**Comment by rsjaffe** [comment]
Could you show the log file where you had that error? See https://github.com/rsjaffe/MIDI2LR/wiki/Lightroom-Menus for instructions on finding the log file. Also, what was the keyboard shortcut you tried adding?
