### ISSUE TITLE
some functions in Lens Correction is unavailable

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#78]
Can you please add possibility to assign action "upright:type" (like "upright - auto" or "vertical"), and "recalculate"?

When I tried to use "upright" option, it worked wired and slow, and finally only "vertical" can be selected.

Thank you!

**Comment by krakozavr** [comment]
yeas, I dig dipper into this option.
I fount that it's working, but wired. The "Perspective-upright" option is working for me only if is assigned to a knob, and modes are changing with 25-step increment, approximately.

It is not very easy to handing :) Is it possible to assign this (and some similar) functions to a button, with cycling-change (each press change the mode to the next one), more-less like with "rating increase-decrease" was doing?

BTW, I tried to re-programming a button at my controller to "increment" type, with 25-step increment (and I tried other options there), but unsuccessful. Maybe somebody have any ideas about it?

**Comment by rsjaffe** [comment]
Yes, that's how LR implemented that control. But you have given me an idea.
Can you give me some midi values that consistently produce each of the
modes? I can then assign an "action" that sends the right value. This way,
the modes can each be supplied to a button (and/or the modes can be cycled
through by button presses).

**Comment by krakozavr** [comment]
With my pleasure, if you will explain me how to get they values :) I'm totally nub with a MIDI-interface :)
krakozavr _at_ gmail

**Comment by krakozavr** [comment]
Or: do you mean just the simple value which displayed bottom of MIDI2LR interface which what each mode switching on?

If YES:
0-15: OFF
16-47: AUTO
48-80: FULL
80-120: Level
120-127: Vertical

But these edges of the diapasons are not firm. I received them by turning from 0 to 127 one-after-one, and even in this conditions edges was floated in relatively wide range. But they are depend of the knob's rotation direction, and probably speed. They are definitely depend also of the starting value of rotation - looks like these value are relative (?) - i received very different value in when I played with my knob, trying to select the specific parameter started from custom other. I think, this is a reason why knob or slider provide a bad control for this parameters - they will activate each time at different positions. But if you will assign the constant values for cycled button, it may working in different way, I can't tell. Or, probably, parameters like these should be handled like relative, with a fixed increments.

**Comment by rsjaffe** [comment]
Thanks. This information will help. I'll try and see what I can do.

**Comment by rsjaffe** [comment]
see #31
