### ISSUE TITLE
ToggleFlag does not work on LRC 13.2 / Finnish keyboard

### ISSUE THREAD

**Issue by tazle** [rsjaffe/MIDI2LR#782]
**Describe the bug**
"Toggle Flag" function does not seem to be working.

**To Reproduce**
1. Assign "Flagging -> Toggle Flag" to a MIDI note.
2. Play the note.

**Expected behavior**
Expected "pick" flag to toggle.

**System(please complete the following information):**
 - OS: 14.3.1
 - LR Classic 13.2
 - MIDI2LR 6.1.0.0

**Comment by rsjaffe** [comment]
How high is the value that the note sends? If you don't hit a note hard enough, MIDI2LR will ignore it as a possible false-positive. Ideally, you'd be sending 127 (the maximum), but anything higher than about 52 or so should work.

**Comment by tazle** [comment]
It's 127. Also, I was able to bind other actions to the note successfully.

**Comment by rsjaffe** [comment]
First, look at step 6 of installation and see if that helps: https://github.com/rsjaffe/MIDI2LR/wiki#installation . If not post a copy of MIDI2LR.log that includes you trying that command. If you don’t know where the log is, Lightroom’s help menu will have “generate diagnostic report” in the MIDI2LR section that will show you where it is. https://github.com/rsjaffe/MIDI2LR/wiki/Lightroom-Menus

**Comment by rsjaffe** [comment]
Also see https://github.com/rsjaffe/MIDI2LR/wiki#faqknown-issues number 2.

**Comment by tazle** [comment]
If it's backtick, the issue might be that it's a dead key on the Finnish keyboard, i.e. when entering text you first hit apostrophe and then the other key to get e.g. è.

Looking at the Swedish keyboard (which has, at least essentially, the same layout as Finnish) shortcuts at https://www.lightroomqueen.com/keyboard-shortcuts/languages/, it seems to be rebound to <. I wonder why it's ` for me.

Looking at the available shortcuts, I set up `cmd + cursor up` and `cmd + cursor down` on a rotary control to work around the issue. Ideally I'd like to be able to toggle pick -> reject -> unflagged using a single button, but setting that up doesn't seem to be feasible as-is.

**Comment by rsjaffe** [comment]
I think @tazle is correct. This is why the log is so useful. Lightroom does change the keystroke for different languages, and MIDI2LR is able to detect which keystroke is bound to the command in the current user language, so it also changes the keystroke from <key>`</key> to whatever's bound in that language. **However**, Lightroom rebinds the key based on the user language selected, not the keyboard language. MIDI2LR takes that keystroke, and, using the _keyboard language_, converts it to a keycode. That's where I think things go wrong. Try using [Keyboard Shortcuts](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#keyboard-shortcuts) to send the toggle flag command and see if that fixes the problem.

**Comment by tazle** [comment]
I tried to make a MIDI2LR shortcut for `, but that didn't work either, nor can I enter the shortcut using the keyboard (probable due to it being a dead key).

Adding a custom Mac OS Keyboard Shortcut for "Toggle Flag", and then creating a keyboard shortcut using MIDI2LR for the custom shortcut works.

**Comment by rsjaffe** [comment]
Lightroom choose shortcut behavior based on interface language, not keyboard language, even though keyboard is the reason shortcuts need language-specific versions. Nothing to fix on my end.
