### ISSUE TITLE
"Tint" slider does not respond to midi control but input is detected

### ISSUE THREAD

**Issue by Ancisace** [rsjaffe/MIDI2LR#81]
LR: Lightroom CC 2015.2.1
MIDI2LR: v0.70
Midi: Korg NanoKontrol2

I have set a slider to control the tint. MIDI2LR fully and accurately detects the motion, and the Basic> Tint function is assigned to it. Despite this, when I actually try to use the slider lightroom does not respond at all. The tint slider stays exactly where it is.

This is far from a critical issue, but it is a little annoying!

![screenshot 2015-12-09 10 21 50](https://cloud.githubusercontent.com/assets/10421114/11682778/ea7c632e-9e5e-11e5-946b-e01f0fed902c.png)

**Comment by estha** [comment]
same issue in midi2lr 0.70 but my problem in temperature slider, when i slide or pull knob, temp prameter in just stuck at warm temp, anyone can help?? please....

**Comment by retheos** [comment]
I have exactly the same problem with the Tint function, sometimes working, sometimes not. Also, can't save already mapped functions to profile file, which is not nice, because I have to map all needed commands before each session.... Help please!

**Comment by retheos** [comment]
I have exactly the same problem with the Tint function, sometimes working, sometimes not. Also, can't save already mapped functions to profile file, which is not nice, because I have to map all needed commands before each session.... Help please!

**Comment by rsjaffe** [comment]
Very odd. I'm going to start from the last comment and work back.
1. The profile file save function is working for most people. What happens when you try to save the profile?
2. What warm temp is the parameter stuck at? Can you slide back and "pick up" control again? How fast are you moving the slider (fast motion can cause the pickup mode to misfire--this is fixed in the upcoming release). What are your limits set at? (see https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog for info on setting limits).
3. Have you tried moving the slider through the whole range (over a couple of seconds) to see if it "picks up" the tint control? If you don't like the pick up behavior, it can be disabled by clicking the settings button on the app.

**Comment by retheos** [comment]
Thank you for answering this thread! Well...
1. Everything looks normal, except the profile file isn't created and so can't be loaded...
I recorded simple video: https://www.youtube.com/watch?v=qN-ECckuAFA

2. Tint - as you can see on the video, the Temp slider is working and the Tint doesn't (you can see changing values from midi slider, but the Tint slider in LR remains inactive)
https://www.youtube.com/watch?v=vmHWGL-c_ro

**Comment by rsjaffe** [comment]
OK. Problem 1: You're trying to save a configuration file to a program directory. Windows won't allow that unless you have elevated privileges. Save the configuration to a location outside of "C:\Program Files" and "C:\Program Files x86)". I also recommend saving your plugins to a different location as well. Perhaps a subdirectory under "Documents".

Problem 2: The tint reading on LR in your video is dimmed out. Was it somehow disabled? Try changing it directly in LR, then see if it works in MIDI2LR.

**Comment by Ancisace** [comment]
I have managed to get the slider to work by setting the limits for the tint slider smaller than default (-100 +100), then restoring to defaults.

**Comment by rsjaffe** [comment]
Very odd. We're significantly changing the limits logic for the next release so hopefully that won't happen again. The code is much cleaner and better-tested.

However, if the issue recurs with the next release, we're going to have to dig deeper into this.

My suspicion is that a nil value for an undefined tint limit was causing the control to be unresponsive.

Thanks for looking into this.

**Comment by rsjaffe** [comment]
File save is a bug. The program should alert you when the file save failed. I've added it to the consolidated list of changes #31.

**Comment by i4apicture** [comment]
I also have the Tint problem with 0.7.0. If I remove the plugin and then add it again then it works fine but then if I restart Lightroom it stops working, a re-install gets it working every time. 

I have only just started using Midi2LR today, nice bit of software - thanks!

**Comment by pdxbq** [comment]
**Reloading the plugin (not re-installing) make tint to work.**
I also have Tint problem as discrabed above. But when I close MIDI2LR after it autopened with lightroom and then go to File-Plugin manager and press Reload plugin button, then Tint works. So, to make Tint slider work MIDI2LR must be reloaded every time. It is a little annoying, to reload plugin every time.

**Comment by rsjaffe** [comment]
See [known issues](https://github.com/rsjaffe/MIDI2LR/wiki) for temporary workaround. Will be fixed in next release.

**Comment by i4apicture** [comment]
Thanks for that, the workaround obviously works but I got very confused when trying to change the limits for tint when in the Library module in LR, it behaves in a rather strange way.

**Comment by rsjaffe** [comment]
Yes. I've now looked into this further. This is a rather nasty bug because it isn't a problem with MIDI2LR code. It involves a Lightroom bug related to program startup.

This is related to timing of calls when Lightroom starts. If I delay the plugin initialization by 1 second, all is well. If I don't, getting parameter limits from Lightroom returns nil instead of the correct values.

I've also fixed the issue about modules, as getting limits from Lightroom is supposed to occur only in the develop module. So the plugin will briefly switch to develop then back to your chosen module when pulling limits.

0.8.0 fixes all this, and I may release it earlier than scheduled. The release is currently under testing. Still would like to fix the file save bug and add some features.

**Comment by krakozavr** [comment]
Great news! If you would like I can test it :-)

**Comment by rsjaffe** [comment]
You can test the limits fix by just downloading the latest build of the plugin here: https://github.com/rsjaffe/MIDI2LR/tree/3efb20e94e83a93d48af99285c8a37a164d8341c/Source/LRPlugin/MIDI2LR.lrplugin . This doesn't include any updates to the app, but this particular issue (limits) is a plugin-only issue.

Replace the lua files in your plugin with the downloaded files, then restart LR.

**Comment by krakozavr** [comment]
something going wrong with LIMITS:

![error message at start](http://minsk2000.to/temp/limits.lua.png)

The message in the sawed debug log:
>Plug-in error log for plug-in at: C:\Soft\LR6\Adobe Lightroom\MIDI2LR.lrplugin
>
>**** Error 1
>
>An error occurred while attempting to run one of the plug-in’s scripts.
>Limits.lua:144: attempt to call local 'historic' (a table value)
>
>**** Error 2
>
>The plug-in encountered an error when performing the menu item “Set options”.
>Limits.lua:144: attempt to call local 'historic' (a table value)
>

**Comment by rsjaffe** [comment]
Fixed the typo. try the limits.lua file at https://github.com/rsjaffe/MIDI2LR/tree/develop/Source/LRPlugin/MIDI2LR.lrplugin

**Comment by krakozavr** [comment]
@rsjaffe noop :(
re-downloaded limits and other recently updated modules. The initial error is different now:


The new error message from Plugins Manager:
![screenshot](http://minsk2000.to/temp/newone.png)

>
>Plug-in error log for plug-in at: C:\Soft\LR6\Adobe Lightroom\MIDI2LR.lrplugin
>
>**** Error 1
>
>An error occurred while attempting to run one of the plug-in’s scripts.
>Limits.lua:144: attempt to call local 'historic' (a table value)
>
>**** Error 2
>
>The plug-in encountered an error when performing the menu item “Set options”.
>Limits.lua:144: attempt to call local 'historic' (a table value)
>

**Comment by rsjaffe** [comment]
This is why beta testers are so valuable. This error doesn't get triggered on my machine because this error only affects those with previously-set limits. I've squashed it again, and I hope that's the last bug. :worried: https://github.com/rsjaffe/MIDI2LR/tree/develop/Source/LRPlugin/MIDI2LR.lrplugin

**Comment by krakozavr** [comment]
@rsjaffe - sorry, same there :(

>
>Plug-in error log for plug-in at: C:\Soft\LR6\Adobe Lightroom\MIDI2LR.lrplugin
>
>**** Error 1
>
>An error occurred while attempting to run one of the plug-in’s scripts.
>Limits.lua:144: attempt to index field '?' (a number value)
>
>**** Error 2
>
>The plug-in encountered an error when performing the menu item “Set options”.
>Limits.lua:144: attempt to index field '?' (a number value)
>

**Comment by rsjaffe** [comment]
Thanks for doing this. Latest attempt is in https://github.com/rsjaffe/MIDI2LR/tree/develop/Source/LRPlugin/MIDI2LR.lrplugin . Now I've added lots of error checking to try to avoid inappropriate assignment of old preferences. Could you download it and try again?

**Comment by krakozavr** [comment]
@rsjaffe - well done!
Just one small cosmetic issue: values doesn't matching to the space.
And, BTW, it will be cool to make the input fields there because it is not easy to set a precise values with a sliders :)

![screenshot](http://minsk2000.to/temp/limits-values.png)

**Comment by rsjaffe** [comment]
I'll give that a shot when I get home tonight.

**Comment by krakozavr** [comment]
anyway, it's working now :)
to be honest, It was worked even with these error, besides the OPTIONS menu was inaccessible :)

**Comment by rsjaffe** [comment]
Your work helped me polish that section. I think I've fixed the cosmetic issue too, but I haven't enable editing in the control.

**Comment by krakozavr** [comment]
@rsjaffe - with my pleasure :)
sorry for the stupid question. Do you know any conventional way to download LUAs from Github, besides to open each file, then open RAW, then save the page?

**Comment by mischnic** [comment]
On the home page (https://github.com/rsjaffe/MIDI2LR) you can click on "Download ZIP" and get all files.

**Comment by krakozavr** [comment]
@mischnic -thank you :) as far as I see, it the the "develop" branch should contain the latest test version of modules, right? ")

**Comment by rsjaffe** [comment]
Fixed in latest release.https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.8.0
