### ISSUE TITLE
Exposure - user selectable range

### ISSUE THREAD

**Issue by MrGBCF2000** [rsjaffe/MIDI2LR#82]
Hi,
I like MIDI2LR very much. Thanks for the efforts you've made so far. I've just donated for you. ;-)
I'm on WIN7, LRCC and BCF2000.
I read all the issues to make myself familiar with recent development of the program.
In issue #10 was a request for user selectable range for tint/color temp and also Exposure. Issue #10  was closed. I tried to find option to select exposure range just like tint and color temperature but I have not found it. Is there a way to change range for Exposure just like color temp in PLUG-IN extras ??
It would be fantastic as most of the time I don't need -5 to +5 eV. Narrower range with smaller increments would be better from my point of view. 
Many thanks

**Comment by rsjaffe** [comment]
It's in development now. Should be in next release. Because the different file types have markedly different exposure ranges (DNG, HDR, jpg, etc.) this will take a bit of coding.
