### ISSUE TITLE
Some features request :)

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#83]
Hello again :)
I understand that not any wishes can be realized, and not any wishes should :) But want to share some ideas.

1. Is it possible to implement  a screen-messages about currently using tools and adjustment's value, like it did in PADDY? 
2. Is it possible to make layouts auto-switching depend of current active module? For example, I'm switching into Library, and Library-related layout loaded, and after returning into Develop, the develop-related one returned? 
--- auto-save the last state should be great. For example, I may have 2 dewelop-related layouts and two Library-related. So, if I will switching between Library and Dewelop, I would like to auto-load the layout last used in the corresponding mode, not some default.
--- support of controller-based presets would be great! For example, I made my layouts with on-controller presets at my BCF2000. Probably, the app can send some command to controller to call the specific preset externally? 

3. And, of course, more module-specific functions :0 Develop and Library are essentials, for sure. Especially, keywording is most wanted :)

P.S. Sorry for my over-activity here; I'm the newcomer with this kind of devices and with this app, so I'm digging into and found many surprises, and some kind of a fresh look, I hope :)

**Comment by rsjaffe** [comment]
request number 2 is probably happening in the next release.
request 1 and 3 added to #31 consolidated listing of requests.
