### ISSUE TITLE
Connected ??

### ISSUE THREAD

**Issue by MaAn59** [rsjaffe/MIDI2LR#85]
Even when nanokontrol2 is not connected to my PC, when start up lightroom , midi2lr version 0.7.0 stated that its connected to lightroom ???
Did not have this in version 0.5.0

**Comment by rsjaffe** [comment]
MIDI2LR will always state "connected" when it "sees" the Lightroom plugin. There isn't a display of "connected" for the controller, so the behavior you see is as intended.
