### ISSUE TITLE
Handle endless rotary encoders

### ISSUE THREAD

**Issue by mbihn** [rsjaffe/MIDI2LR#86]
Hi, the Behringer BCR2000 has endless rotary encoders, so normaly there ist no need for "pickup mode". But if the picture and/or value change, the application has to reset to the corrosponding value (eg Lightroom = 0 MIDI=63, Lightroom=-100 MIDI=0, Lightroom=100 MIDI=127) for the encoder.

I'd think, that can be done with LR addObserve and I'd try to find out the nessecary changes in the source code but finaly I give up. Maybe you have time for this at some day. I'd glad to do debuging and beta-testing. Contact michael (at) m-bihn.de

**Comment by rsjaffe** [comment]
The best way to use the endless encoders is in differential mode, in which case the pickup issue goes away completely. However, I haven't worked with that mode and don't know how the MIDI messages appear, so I haven't touched it yet. And the BCR2000 has a number of different differential modes. If you could poke into that a little more and understand how that works, we could look into adding it in.

**Comment by rhythmmachine** [comment]
This was working for me in a previous version (when I moved to a new image in the develop module, the rotary encoders on the BCR2000 would light up according to the value in LR, and when I would turn one of them, it would automatically start from the current value). In recent versions, it has only seemed to work in pickup mode, which defeats the benefit of the rotary encoders relative to sliders which have an absolute position. I would love to be able to get out of pickup mode again - the only time I turn a dial is if I want to change a setting, so I never want to have to turn it up or down to get to the starting point - ideally, it should always start at the current value, increase the value if I turn the know clockwise and decrease the value if I turn it counter-clockwise.

**Comment by rsjaffe** [comment]
Please check in the new release. Communication with controller is improved.

**Comment by mbihn** [comment]
Work's fine! Thanks!
