### ISSUE TITLE
FileBox Extender

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#87]
I think this small app will be very useful for tuning MIDI2LR mapping (and probably may help to memorize complicated layouts). http://www.hyperionics.com/files/

With it, you can pin any app over any other on your scree. So, you can working with lightroom and keep MIDI2LR windows over the LR interface, and see together your mapping and LR respond.

(and this is useful app, in many way).
Windows only, 32/64bit, working with Windows 10.

**Comment by rsjaffe** [comment]
Could you post a screenshot showing what this looks like?

**Comment by krakozavr** [comment]
I made the short video. Sorry about quality, but you will understand what it is :)
https://youtu.be/QAu4aFX87Cw
