### ISSUE TITLE
On-OFF button's mode - can it be used?

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#89]
Hello again :)
I have an (probably stupid) idea.
Buttons can working in different modes, on of them is "on-off". Is it possible to using this mode to toggle a pair of actions? For example, one button could be set Pick-Up flag for ON and remove this flag for OFF (and we can create many actions like this).

**Comment by rsjaffe** [comment]
Not so stupid. Sounds interesting. We'd have to identify actions for which this makes sense. There could be a problem with synchronization between the controller and the app--the app only gets information when a button is pressed, so doesn't always know what state the button is in.

Would you have some suggestions?

**Comment by krakozavr** [comment]
As far I understand, for MIDI controller the buttons in the ON/OFF mode are working different way than when they are in the regular mode. Even indication is working different - the LED is lights when the button is "pressed" (ON status) and goes out when it is "depressed" (OFF status). When I tried a buttons in this mode, only the first (ON) pressing generated the action in LR, and the second pressing (OFF) was ignored and was not recognized by MIDI2LR like the new control for mapping. Probably, MIDI-controller send the different codes but MIDI2LM just know nothing about the second one? If I'm right there, you have to "learn" the app to recognize this kind of buttons and then users will be able to reprogramming any button to the ON-OFF mode and assign any pair of actions. An in this case, button's light will provide an additional visual info about active modes.

But, if this mode can be problematic in synchronization, may be the easiest way to do something like this should be joining of two LR's actions into the one MIDI2LR's action which can be mapped? For example, in LR we have "pick" and "remove flag" but in the MIDI2LR it will be one metaaction when two joined actions will cycled? Or in this case you will have the other problem to define which status is currently set to process a proper action?

What about actions. I think that appropriate pair for this mode can be:
Pick -- Remove flag
Reject -- Remove Flag
Set rating X -- Set rating 0
Filter by (flag, color, rating) - Remove filtration by (xxx)
Module DEVELOP - Module Library
Threatment Color -- B&W
Profile correction enable -- disable
Remove chromatic aberration enable 0- disable
Constant crop enable -- disable
Tools active -- closed

P.S. I'm sorry, I'm absolutely not a programmer, so don't be angry if some ideas will be crazy for realization, I know nothing about this. So, I thinking just about usability; but it's don't mean that I have some complain about your work (it is really brilliant - thank you very much!) or I'm sure that some changes should be done. It's just a friendly even not suggestions but questions. And sorry, I really have no idea how to implement it :)  

P.P.S. Sorry my English, I hope you can understand me properly :)

**Comment by krakozavr** [comment]
I'm looked at this mode (called TOGGLE - ON).
As far as I understand, In this mode button will generate only one command but it will produce a different values when it will be "pressed" - "ON" or "depressed" - "OFF". Looks that by default the ON value should be 127 and OFF value 0, but it should be programmable.

**Comment by rsjaffe** [comment]
The buttons in the MIDI controller can be programmed Toggle-on, in which case one press will signal 127 and turn on the light, and the second press will signal 0 and turn off the light. We've set up the app for toggle-off, which sends a 127 and lights the button when depressed and a 0 and turns off the light when released.

**Comment by rsjaffe** [comment]
See #31

**Comment by DGrove88** [comment]
I'd like to use this Toggle idea for D and G so I can switch between Develop and Library with one button.

**Comment by Jaegerstefan** [comment]
Has it even been implemeted? Especially showing the pick status with the LEDs would be a really nice feature for photo culling.
