### ISSUE TITLE
14 bit and higher resolution

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#90]
Is it may be used to increase sliders sensibility and precision? I tried to reprogramming the sliders to 14 bits and I saw no differences, but maybe I did something wrong.

**Comment by rsjaffe** [comment]
We need to add NPRN support to get 14-bit precision. It's on our list of planned enhancements #31. It may take a bit to do--Jucer is our MIDI library and they never added NPRN support, so we'll have to code it on our own.

**Comment by krakozavr** [comment]
Thank you for info :)
