### ISSUE TITLE
Assigning user created presets to buttons?

### ISSUE THREAD

**Issue by ajaxandy** [rsjaffe/MIDI2LR#91]
I noticed in Midi2LR you can assign buttons to Preset 1, Preset 2 etc, however where do my presets need to be for Midi2LR to pick them up when I press the button I've assigned to them?

At the moment I have 2 folders, User Presets & Current Presets... however it doesn't seem to pick up any of the presets from either when I press the relevant buttons.

**Comment by krakozavr** [comment]
BTW, how presets (from Plugin Extras - Options) are really working? I tried to understand but I can't :-\  WIKI can't help, maybe I'm too stupid.

Help please :-)

**Comment by rsjaffe** [comment]
Setting up presets is a two-step process.

Step 1: Follow the instructions at https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog. This assigns preset numbers to selected presets.

Step 2: In the app, assign the preset numbers to buttons.

It had to be two steps, as the app doesn't know what presets you have. When you press a button assigned to Preset 1, all the app does is send the code *Preset1* to the plugin. The plugin then looks up which preset you've assigned to slot 1, and applies that.

**Comment by rsjaffe** [comment]
[Wiki instructions updated.](https://github.com/rsjaffe/MIDI2LR/wiki/Commands:-Presets)
