### ISSUE TITLE
Install/setup

### ISSUE THREAD

**Issue by censrd** [rsjaffe/MIDI2LR#92]
Hi, I followed all the setup instructions but seem to have an issue with getting the plugin to start. Im running Win10, LR 2015.3, Cam Raw 9.3, midi2lr 0.7.0. Midi Device Akai APC40 mk2.
When attempting to start plug in I get error screen showing the following msg. 

"An internal error has occurred: Win32 API error 2 ("the system cannot find the file specified.") when calling ShellExecuteExW from AgWorkspace.shellExecute. 

In the LR plug in manager is shows the green light and states installed and running.

Any idea what i'm doing wrong? Or need to change?

**Comment by rsjaffe** [comment]
Is MIDI2LR.exe in the plugin folder? The error sounds like LR can't find it.

**Comment by censrd** [comment]
Hmm odd, there doesn't appear to be the above mentioned exe file. I'll re download and try again. 
Cheers

**Comment by rsjaffe** [comment]
Download from https://github.com/rsjaffe/MIDI2LR/releases/latest

**Comment by lucian1308** [comment]
hi! I have this issue two! I try to install this plugin on Windows 10 and lightroom cc. midi2lr plugin location is C:\Users\UserName\AppData\Roaming\Adobe\Lightroom\Modules. I have been tryed many other locations...but same error. any ideea please!

**Comment by lucian1308** [comment]
ooooh! MIDI2LR.exe is missing 💃  solved :)

**Comment by lucian1308** [comment]
now what? https://s21.postimg.org/783wpm2x3/err_MVCpp_RL_l170.png
