### ISSUE TITLE
Release cycle will be about once/month

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#93]
Gosh, there's a lot to do!

I have a full-time+ job and like to do photography and other activities in my spare time, so I can't do everything that's needed for this program all at once. I've also done a few improvements too hastily, and the code has gotten to the point where it needs to be carefully refactored into modules.

As a result, I'm going to slow down the release cycle to about once per month, instead of releasing a new version as soon as a feature is complete. Bugs, of course, will be squashed asap with an interim release.

You will also notice several branches showing up in the repository. **master** is the release branch, and is usually only updated at each release, so it contains working code representing the latest version. **develop** is the main development branch. Code there is assumed to be fully functioning, so if you're thinking of forking the repository for development, fork **develop**. Branches starting with **feature-** are where major coding work is going on and in which the code may not be functioning but is certainly interesting.

And if you want to help improve the code, please do! Contact me at rsjaffe@gmail.com if you have any quesitons.

**Comment by krakozavr** [comment]
Have you a plane to send out the last 2015’s release before the NY? :-) 

Just for info, no complains/urge!
Thank you for your job.
Merry Christmas :-)

**Comment by rsjaffe** [comment]
If I keep on schedule, it will arrive around January 1, since the last release was at the beginning of December. Festivities may alter the schedule slightly, but we already have a significant amount of improvements that have passed the testing phase.

**Comment by krakozavr** [comment]
Thank you for info :-). Have very happy holidays!
