### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#94]
Can you please add this option? It's not very important, but will be definitely logical because MIDI2LR is not the "program for everyday usage" itself - a small indicator in the tray (even hidden one) will be enough after initial setup.

**Comment by rsjaffe** [comment]
That was added in 0.7.0. On the app, press the *Settings* button. Adjust "Auto hide" to select how quickly the app minimizes to the task bar. Because of how the underlying cross-platform works, we have to show it at least briefly before minimizing.

**Comment by krakozavr** [comment]
It is a little different behavior :) I don't want to have MIDI2LR as active app in the task bar, but in the tray - next to the clock, together with other system apps.
