### ISSUE TITLE
iPad & TouchOSC & MIDI2LR

### ISSUE THREAD

**Issue by nachtgrapp** [rsjaffe/MIDI2LR#95]
Hello,

I am trying to set up TouchOSC on my iPad to control Lightroom via MIDI2LR. 

What works fine is the assignment of functions to buttons and sliders/faders.

What does not works i:
- When I select a different picture in Lightroom, the faders/sliders are not adjusted on my iPad accordingly. The sliders simply remain in the position where they were before, when editing the last picture.
- The tone control does not work.

Has anybody a hint for me?

All the best,
Oliver

**Comment by seweil** [comment]
(I don't have an answer, sorry.)

 I've been trying to to use Touch OSC as well, with no luck. Are you on Windows or a Mac?

**Comment by nachtgrapp** [comment]
I am on Mac
