### ISSUE TITLE
save mapping not working

### ISSUE THREAD

**Issue by retheos** [rsjaffe/MIDI2LR#96]
Hi rsjaffe,

First, thank you for all your efforts you put into creating this great plug-in!

I have just one problem - can't save already mapped functions as a profile,
don't know why? I click 'save', choose previously created folder, give a name 
to profile (something like a 'korg_01'), click 'save' again...and the folder is empty, 
no profile file is saved:(

Another little problem is that the Tint is not always working after mapping to slider.

I use Korg NanoKontrol2 with LR CC (currently in a trial mode) on Windows 10 Home x64.

Thank you in advance!

**Comment by rsjaffe** [comment]
See issue #81  for suggested approaches to debugging the issue.
