### ISSUE TITLE
Tint doesn't work

### ISSUE THREAD

**Issue by pdxbq** [rsjaffe/MIDI2LR#97]
Hello!
Thank you for your great software!
There is an issue in v0.7.0
After updating to version 0.7.0 Tint slider on my midi controler doesn't make any effect to Lightroom's Tint slider. Assaining Tint slider to other midicontrollers slider doesn't help.  It's assignable, MIDI2LR see the slider, but doesn't send comand to lightroom.
---
My system info:
Win7 64
Lightroom version 6.3.
Akai Midimix

**Comment by i4apicture** [comment]
I have just installed 0.7.0 as a first time user and I can't get Tint to work either

**Comment by pdxbq** [comment]
The Tint issue was discussed here: https://github.com/rsjaffe/MIDI2LR/issues/81

**Comment by rsjaffe** [comment]
If you set limits on tint, it will work. This is fixed in next release.
