### ISSUE TITLE
Upright: recalculate

### ISSUE THREAD

**Issue by krakozavr** [rsjaffe/MIDI2LR#98]
Is it possible to add the "upright:recalculate" action to MIDI2LR? It's look tricky because it is not a regular button, but maybe yes? :-)

**Comment by rsjaffe** [comment]
Not looking likely--no good way in LR SDK to do it. However, I did assign the various upright modes to individual buttons in 0.8.0. Out soon

**Comment by krakozavr** [comment]
@rsjaffe - sorry to return this closed team...
upright:recalculation working in a very different way. unlike direct upright mode assignment, it keep cropping untouched. So, using recalculate, you can synchronize settings, include cropping and upright mode, between series of photos then adjust upright with recalculation. It's huge time saver for many tasks.

So, if you think that implementation is (theoretically) possible, please keep it in mind :)

It's not a complain, just want to share with you my things about this option's importance :)
