### ISSUE TITLE
Translation assistance wanted

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#99]
I'm adding translation of menu items for the Lightroom plugin (but not the app) in the next release. For those interested in helping, the files to edit are in https://github.com/rsjaffe/MIDI2LR/tree/develop/Source/LRPlugin/MIDI2LR.lrplugin and are named **Translated_Strings_??.txt** where **??** is replaced with the language code. The German translation has already been done by Niklas Mischkulnig. :clap: 

To provide a translation for the project, download the txt file in the language you want to translate. The only languages supported by Lightroom are German (de), English (en), Spanish (es), French (fr), Italian (it), Japanese (ja), Korean (ko), Dutch (nl), Portuguese (pt), Swedish (sv), Chinese simplified (zh_cn) and Chinese traditional (zh_tw).

The following text editors are recommended for editing these files: 
* In Mac OS X simply use TextEdit and make sure you save the file type as “UTF-8” (rather than UTF-16 or UCS-2, for instance). 
* In Windows use Notepad, and be sure to save the file as type “UTF-8.” 

Each line in the file is formatted like `"$$$/MIDI2LR/Stuff/name=The text to translate"`. Leave everything to the left of the = sign alone, and replace the text to the right of the = sign with the translation. If you see a **^** sign followed by a number in the string, leave that alone as well--that gets replaced with a calculated value in the program. No newline characters or comments are allowed. The strings in this file must all be enclosed with double quotes. If you're wondering what a translated file looks like, compare Translated_Strings_en.txt with Translated_Strings_de.txt.

Send any translations to me at rsjaffe@gmail.com. Thanks for your assistance!

**Comment by davefoto** [comment]
I can and will help in Hungarian.

**Comment by rsjaffe** [comment]
Thanks for your offer. But Lightroom only supports German (de), English (en), Spanish (es), French (fr), Italian (it), Japanese (ja), Korean (ko), Dutch (nl), Portuguese (pt), Swedish (sv), Chinese simplified (zh_cn) and Chinese traditional (zh_tw). What language is the Lightroom interface in when your computer's preferred language is set to Hungarian?

**Comment by LeJimi** [comment]
I can help with Polish. Let me know if you want to go ahead.

**Comment by rsjaffe** [comment]
Please do. Thank you.

**Comment by davefoto** [comment]
Hi Rory,

My interface is English with Hungarian language settings in Windows. I
wasn't aware of the restriction, foolish me.

2015-12-22 6:32 GMT+01:00 rsjaffe <notifications@github.com>:

**Comment by Polekso** [comment]
Hello Rory,
I'm about to send you the french translation. Thank you for all you have done.
Merry Christmas to you.

**Comment by rsjaffe** [comment]
Thank you and joyeux Noël.
